### ISSUE TITLE
ERROR Create Subquery project from given path failed! Error: Please only provide one of chainId and genesisHash

### ISSUE THREAD

**Issue by arthas207** [subquery/subql#1031]
when I started the docker,I encountered the error log like 'Please only provide one of chainId and genesisHash'.
    I followed the steps by the example in the url: 
                https://doc.subquery.network/quickstart/quickstart-polkadot.html
     Here is my project.yaml file 
                          `specVersion: 1.0.0
                          name: subquery-demo
                          version: 1.0.0
                          runner:
                            node:
                              name: '@subql/node'
                              version: ^0.33.0
                            query:
                              name: '@subql/query'
                              version: 0.24.0
                          description: >-
                            This project can be use as a starting point for developing your SubQuery
                            project
                          repository: 'https://github.com/subquery/subql-starter'
                          schema:
                            file: ./schema.graphql
                          network:
                            chainId: '0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3'
                            endpoint: 'wss://polkadot.api.onfinality.io/public-ws'
                            dictionary: 'https://api.subquery.network/sq/subquery/dictionary-polkadot'
                            genesisHash: '0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3'
                          dataSources:
                            - kind: substrate/Runtime
                              startBlock: 1
                              mapping:
                                file: ./dist/index.js
                                handlers:
                                  - handler: handleEvent
                                    kind: substrate/EventHandler
                                    filter:
                                      module: balances
                                      method: Transfer`
     
      The network configuration is wrong?

**Comment by jiqiang90** [comment]
Hi , as indicated in the error log, in manifest 1.0.0 we only need chainId to identify/validate the network, you can remove the `genesisHash` here will fix the issue.

**Comment by jiqiang90** [comment]
This could related to https://github.com/subquery/subql/pull/1058, we have fixed and this can be closed
