### ISSUE TITLE
Update validator to handle multichain

### ISSUE THREAD

**Issue by jiqiang90** [subquery/subql#1035]
current validator only support substrate and  terra,  we need update this load project logic.

**Comment by jiqiang90** [comment]
Also, there is an issue with `parseSubstrateProjectManifest`, when load  `genesisHash` that not in string we got 
<img width="747" alt="Screen Shot 2022-05-16 at 11 36 19 AM" src="https://user-images.githubusercontent.com/10431657/168930462-e72eb318-bc21-4fe6-b344-d8c1ae7f6bfc.png">

**Comment by stwiname** [comment]
We should also support validating deployments

**Comment by ianhe8x** [comment]
It is a number because the value of chainId is not quoted in yaml.
