### ISSUE TITLE
Fix benchmark logging

### ISSUE THREAD

**Issue by stwiname** [subquery/subql#1076]
Quite often the benchmark logging will output something like `NaN bps, target: #1208163, current: #1208163, estimate time: NaN days NaN hours NaN mins`

This can happen either when the project is fully synced or the connection has dropped to the node.

We should display `0 bps, target: #1208163, current: #1208163, estimate time: unknown` if there is still blocks to sync otherwise `Fully synced, waiting for new blocks`

**Comment by jiqiang90** [comment]
Close with https://github.com/subquery/subql/pull/1083
