### ISSUE TITLE
CLI deploy to hosted service

### ISSUE THREAD

**Issue by stwiname** [subquery/subql#1084]
### Requirements
- Needs a non-interactive version for CI purposes
- Use same auth as with IPFS
- Commands:
  - Deploy
    - Should use IPFS deployments
    - Allow specifying query and node versions
    - Choose between stage and prod
    - Deploy to projects create by both the UI and CLI
  - Delete
  - Promote from staging to prod
  - Create Project
  - Update Project
  - Status 
  - re-Deploy

### Technical Info:
Api reference: https://api.thechaindata.com/doc/#/

Deploy: https://api.thechaindata.com/doc/#/DeploymentV2/DeploymentV2Controller_deploy
Delete: https://api.thechaindata.com/doc/#/Deployment/DeploymentController_delete
Promote: https://api.thechaindata.com/doc/#/Deployment/DeploymentController_release
Create: https://api.thechaindata.com/doc/#/Deployment/DeploymentController_deploy
Status: https://api.thechaindata.com/doc/#/Deployment/DeploymentController_deploymentStatus
             https://api.thechaindata.com/doc/#/Deployment/DeploymentController_syncStatus
Update: https://api.thechaindata.com/doc/#/Deployment/DeploymentController_upgrade
Get image versions: https://api.thechaindata.com/doc/#/Info/InfoController_getImageVersions

**Comment by jamesbayly** [comment]
See Darwinia's existing GitHub action that has some of this in place. https://github.com/darwinia-network/bridger/tree/master/.github/workflows

**Comment by zhex** [comment]
I think fewensa is also a member from darwinia team

**Comment by jamesbayly** [comment]
Can we get an outline of this on the docs that I can then edit and also implement it in our dictionary projects?
