### ISSUE TITLE
Issue trying to use frontier EVM support

### ISSUE THREAD

**Issue by KarishmaBothara** [subquery/subql#1106]
<img width="1281" alt="Screen Shot 2022-06-10 at 4 37 26 PM" src="https://user-images.githubusercontent.com/29415595/172991294-6bdbed0c-0c3e-45c4-8941-ae5d65273925.png">
It happens at a block where there exists event - evm(Log) without ethereum(transact) extrinsic.

**Comment by stwiname** [comment]
Hi @KarishmaBothara,

It's a little hard to know whats going on without more context. Can you please share what network/block is having trouble and possibly your code? 

Also we have move the frontier evm processor to https://github.com/subquery/datasource-processors. Are you able to try that instead please? It will require using the latest subquery node.

**Comment by KarishmaBothara** [comment]
Hi @stwiname,

I tried using frontier evm processor with "@subql/frontier-evm-processor". However it breaks at the same block 3450156
<img width="1335" alt="Screen Shot 2022-06-13 at 10 43 52 AM" src="https://user-images.githubusercontent.com/29415595/173256513-2c51906b-0d35-4fb8-836d-7d9fc84a222c.png">
https://rata.uncoverexplorer.com/block/3450156 more detail about the block

**Comment by ianhe8x** [comment]
@stwiname This is possible though, when the evmtransact is included in util.batch(all) or executed by council / scheduler. So we need to handle this case at least don't throw.

**Comment by stwiname** [comment]
Hi @KarishmaBothara 

Can you please try `@subql/frontier-evm-processor@0.0.3-0`. It shouldn't throw an error any more but the transaction hash will be missing.

Out of curiosity, are you wanting to index data with that event? It seems related to `ethStateOracle(Callback)` which isn't from frontierEVM.

**Comment by KarishmaBothara** [comment]
@stwiname thanks... It works... Just found some time to just this..

Yes, its related to ethStateOracle(Callback) which is EVM precompile module.
