### ISSUE TITLE
Make the BLOCK_TIME_VARIANCE constant configurable

### ISSUE THREAD

**Issue by GuillaumeMarquisBlockpulse** [subquery/subql#1117]
Hi,

I was wondering to change the interval of fetching new block to fit my own substrate blockchain. I saw that this parameter is defined in a constant named BLOCK_TIME_VARIANCE in the file `fetch.service.ts`. I think it could be really useful to put this parameter in the main configuration.
I can do it and send a PR if you think that would be nice to add this feature.

**Comment by GuillaumeMarquisBlockpulse** [comment]
Hi @jiqiang90,
Thanks for your reply. Indeed if you keep the default substrate block time (6 seconds), an interval of 5 seconds ensure to ingest block by block ; although I think it is not optimal because it creates a random delay to get the data after the block is created (up to 5 seconds).

A best approach could be to determine the `BLOCK_TIME_VARIANCE` dynamically by ingesting few blocks at the start of subql to determine an average of block time and to start the interval of fetching at the same time of block creation.

In my case, I have a substrate blockchain that create blocks every 2 seconds and I would like to access data from subql quickly after block creation (waiting 5 seconds more is not suitable).

**Comment by jiqiang90** [comment]
Hi @GuillaumeMarquisBlockpulse , thank you for the explanations, I think we have a much better understanding of your requirements.

I think rather than create a new config for this, we can use polkadot api to get the chain block creation time interval, and create a fetching interval slightly shorter than it. 

If this will solve your problem I can implement it soon

**Comment by GuillaumeMarquisBlockpulse** [comment]
Hi @jiqiang90,
That sounds great ! I think that it's a really good idea to base the time variance on the time interval given by the polkadot api. It will solve my problem.

Thank you!
