### ISSUE TITLE
Add init-user-db.sh in docker-compose file

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#1126]
If a subql project would like to use historical query feature, the btree_gist extension need to be enabled in the db.
The current docker-compose setup doesn't include this.

A way use create a init-user-db.sh file with
```
#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE EXTENSION btree_gist;
EOSQL
```

Then mount this script to `/docker-entrypoint-initdb.d/init-user-db.sh`

```
#docker-compose.yml

...
services:
  postgres:
    ...
    volumes:
      - .data/postgres:/var/lib/postgresql/data
      - ./docker/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
...
```

**Comment by stwiname** [comment]
https://github.com/subquery/subql-starter/pull/63
