### ISSUE TITLE
HTTP Keep alive

### ISSUE THREAD

**Issue by stwiname** [subquery/subql#1128]
Set `keepAlive: true` and `maxSockets: 10` for polkadot http connections

**Comment by jiqiang90** [comment]
While polkadot api forked node-fetch not supporting `agent` option, we can: 
- Override the provider class: https://gist.github.com/jiqiang90/935fb68736bc730664666ce67853a40e
- If https://github.com/polkadot-js/api/issues/4991 accept, we can implement agent with it
