### ISSUE TITLE
Failed to fetch events

### ISSUE THREAD

**Issue by ironoa** [subquery/subql#1186]
I'm having an issue running the indexer node, version v1.4.1, on kusama, specifically at block 492360:
```
<fetch> ERROR failed to fetch events at block 0xe71148e13fb2dcb6b84d8503458941b668d99f965ea465ce356cb2d07ef04223
<indexer> ERROR failed to fetch block Error: Unable to decode storage system.events:: createType(Vec<EventRecord>):: Vec<EventRecord>:: Decoded input doesn't match input, received 0x1800000000000000102700000101000001000000000010270000000100000200…3101000000000000000000000000000003000000000103050340420f00000100 (140 bytes), created 0x1800000000000000102700000101000001000000000010270000000100000200…0000000000000000000000000003000000000103050340420f00000100000000 (143 bytes)
```
The problem seems to arise after the indexer node version v1.1.2, which is the latest working version for me (I tried several node version in between)

Polkadot is not giving me that problem.

**Comment by stwiname** [comment]
Hi @ironoa, are you able to share your project?

There is most likely an issue with the chain types, but its hard to help without seeing your project.

**Comment by ironoa** [comment]
https://github.com/w3f/subql-polkadot-extrinsics/blob/master/project-kusama.yaml#L16-L17

**Comment by jiqiang90** [comment]
Hi @ironoa I suspect it was due to outdated polkadot/api in @subql/node 1.4.1. 

In the recent release @subql/node 1.5.0 we are using the latest 8.12.2, it should be able to decode this block.

**Comment by ironoa** [comment]
Switching to @subql/node 1.5.1 solved the issue indeed, thanks.
Closing...
