### ISSUE TITLE
subql init with npm fails without setting node-fetch to v2

### ISSUE THREAD

**Issue by wilwade** [subquery/subql#1210]
### Prerequisites

* [x] Are you running the latest version(s)?
* [x] Did you check the [debugging guide](https://doc.subquery.network/academy/tutorials_examples/debug-projects.html#how-to-debug-a-subquery-project)?
* [x] Did you check the [FAQs](https://doc.subquery.network/faqs/faqs.html) and [Discussions](https://github.com/subquery/subql/discussions)?
* [x] Are you reporting to the correct repository?
* [x] Did you search for an existing issue or pull request?

### Description

node-fetch v3 installs by default for `subql init` and that fails codegen.

### Details

These details can help to reproduce the environment the issue is occurring

**Local Environment:** @subql/cli/1.3.1 darwin-arm64 node-v16.14.0
**Query Version:** N/A
**Indexer Version:** N/A
**Network Details:**
  * Polkadot

### Steps to Reproduce

1. `subql init` Polkadot
2. Use the graphql from the starter https://academy.subquery.network/quickstart/quickstart_chains/polkadot.html#_1-update-your-graphql-schema-file
3. `npm i`
4. `npm run-script codegen` FAIL

**Example project:** https://academy.subquery.network/quickstart/quickstart_chains/polkadot.html

**Expected behavior:** Code generated

**Actual behavior:**
```
Error: require() of ES Module .../project/node_modules/node-fetch/src/index.js from .../project/node_modules/native-fetch/src/index.js not supported.
    Instead change the require of .../project/node_modules/node-fetch/src/index.js in .../project/node_modules/native-fetch/src/index.js to a dynamic import() which is available in all CommonJS modules.
    Code: ERR_REQUIRE_ESM
```

### Any other information

If you manually set `"node-fetch": "2.6.1"` it will work.

**Comment by jiqiang90** [comment]
Thanks @wilwade this is a known issue.

https://github.com/subquery/subql/blob/0bd6eebe7a625dbc44ec81291cda6f95b4d83934/packages/cli/package.json#L84
We are force `node-fetch` to 2.6.7 in our cli at the moment, and it works fine with `yarn`
You information is helpful, I will notify team regard this issue if they install with npm.

**Comment by jiqiang90** [comment]
I think we can close this now,  as long as enforce use v2.6.7 and yarn, this should resolve the issue.
