### ISSUE TITLE
Add rules for schema migration

### ISSUE THREAD

**Issue by jiqiang90** [subquery/subql#1227]
This follow ups from https://github.com/subquery/subql/pull/1226

We need to provide a list of rules to restrict and promote logs help user schema migration, current there is no restrictions, user might running into relation issues due to changes.

**Comment by jamesbayly** [comment]
We could release this as a beta feature first and provide a lot of warning/guidance in the docs

**Comment by jiqiang90** [comment]
We can close this, we will handle migration in https://github.com/subquery/subql/issues/1289
