### ISSUE TITLE
Strategies for Optimizing Performance

### ISSUE THREAD

**Issue by wpank** [subquery/subql#1248]
I'm not sure if there's a best way to do indexing or not, but I'm working on the following repository:

https://github.com/wpank/subql

For Polkadot, this takes a very long time to index these extrinsics, the estimated bps fluctuates bettween <1 bps and <10 bps, and the estimated time is usually over a week. I still haven't had this running yet where it's able to index the entirety of the Polkadot chain yet. 

Is there a way, or different strategies to improve the time it takes to index things? I tried adding the recent `--workers=<num>` flag, although not sure if it makes much of a difference. 

Ideally I feel like there's probably a way to parallelize things where you try to connect to multiple different rpc nodes, and send parallel queries to these, although I'm not sure how this might fit in with the current architecture of things.

Any advise or guidance would be appreciated.

**Comment by jamesbayly** [comment]
It looks like you've done everything right, the main issue that I can see is that for every handleNominate event, you make up to 4 RPC queries. Each of these might take 100ms which could be the primary reason why you're having issues.

Is there potentially some way you can cache these?
Could you also interpret this data from the on chain events

@jiqiang90 any other ideas?

**Comment by jiqiang90** [comment]
I think @jamesbayly is correct on this. I think you can combine api calls in one place, and we can use `api.queryMulti` to make parallel.

**Comment by jamesbayly** [comment]
@wpank would you like any further support with this? Otherwise will close
