### ISSUE TITLE
`subql_indexer_processed_block_height` metric is always `0`

### ISSUE THREAD

**Issue by quinndiggitypolymath** [subquery/subql#1255]
After this change: https://github.com/subquery/subql/commit/cabbd8e254f56831f15f2249bad3dcb252bf514a#diff-b98e912e6af8e46732fe190227024af218c831e98fb3d0c6e3f24c78087c20d0L145 `subql_indexer_processed_block_height` on `127.0.0.1:3000/metrics` is always `0`

`curl -s localhost:3000/metrics | grep -i processed`
```
# HELP subql_indexer_processed_block_height The last processed block height
# TYPE subql_indexer_processed_block_height gauge
subql_indexer_processed_block_height 0
```

`subql_indexer_processed_block_height` should either be removed or accurately reported.

**Comment by quinndiggitypolymath** [comment]
@wqsz7xn , is there an intended replacement for this metric whose implemented was forgotten entirely, was this an errant removal, or was its removal intentional + incomplete?

@ianhe8x , it seems this was missed during the review process, or there was insufficient testing/test cases surrounding the functionality: https://github.com/subquery/subql/pull/740#pullrequestreview-849703535

**Comment by ianhe8x** [comment]
Agree, it should be removed. @jiqiang90

**Comment by jiqiang90** [comment]
Hi @quinndiggitypolymath Thank you , it looks like your subql-node version is outdated, this metric has been removed already. Please checkout our latest version .
