### ISSUE TITLE
StoreService.getByField workaround for 100 entities limit

### ISSUE THREAD

**Issue by filo87** [subquery/subql#1258]
The current implementation of the `getByField()` method in the store service:

https://github.com/subquery/subql/blob/d4ac6e68ea450dd5c08c40f310406014ccc5b4f4/packages/node/src/indexer/store.service.ts#L662-L691

has a hard limit of 100 on the amount of entities that can be queried. In our implementation this could at some point become a problem. Is there a way to extend or circumvent this limitation? Or is there any other approach you could suggest?

Thanks

**Comment by stwiname** [comment]
Thanks for pointing this out. Looks like the value is not even configurable through the cli. 

We will look more into a solution for this. It will most likely be the ability to page the results

**Comment by jamesbayly** [comment]
https://github.com/subquery/documentation/pull/220
