### ISSUE TITLE
Improved Error Handling and Display

### ISSUE THREAD

**Issue by jamesbayly** [subquery/subql#1276]
### Description

When we have an error in the mapping function, all we get is a console log printing what mapping function failed. When this is a complicated or big function, it's really hard to identify the bug

![telegram-cloud-photo-size-5-6087141313809068407-y](https://user-images.githubusercontent.com/46693720/187603173-95585122-faf9-4e06-842a-0da41d20ac97.jpg)

Support sourcemaps for mapping handlers

**Comment by stwiname** [comment]
The solution to this would be to include source maps and resolve the stack trace from the sourcemaps.
