### ISSUE TITLE
atob is not defined / not supported ds @substrate/Moonbeam

### ISSUE THREAD

**Issue by Cupnfish** [subquery/subql#1277]
Has anyone encountered a similar error, where I have committed code to GitHub that was previously deployed correctly, but after pulling the code on a new computer the deployment ends up reporting this error:

```shell
{"level":"info","timestamp":"2022-09-01T13:33:52.702Z","pid":7,"hostname":"subquery-15905-indexer-deployment-676cd969c-g4b7d","category":"indexer","message":"indexer manager start"}
{"level":"error","timestamp":"2022-09-01T13:33:53.698Z","pid":7,"hostname":"subquery-15905-indexer-deployment-676cd969c-g4b7d","category":"ds-sandbox","payload":{"type":"error","name":"ReferenceError","message":"atob is not defined","stack":"ReferenceError: atob is not defined\n    at /tmp/dMmOcn/QmP1jrivfmv5KtvfSKXBzSfvhDVi7YPJscZXdEvEvKZd7S.js:2:52065\n    at Module.9823 (/tmp/dMmOcn/QmP1jrivfmv5KtvfSKXBzSfvhDVi7YPJscZXdEvEvKZd7S.js:2:52161)\n    at r (/tmp/dMmOcn/QmP1jrivfmv5KtvfSKXBzSfvhDVi7YPJscZXdEvEvKZd7S.js:2:463136)\n    at Object.972 (/tmp/dMmOcn/QmP1jrivfmv5KtvfSKXBzSfvhDVi7YPJscZXdEvEvKZd7S.js:2:95292)\n    at r (/tmp/dMmOcn/QmP1jrivfmv5KtvfSKXBzSfvhDVi7YPJscZXdEvEvKZd7S.js:2:463136)\n    at Object.9684 (/tmp/dMmOcn/QmP1jrivfmv5KtvfSKXBzSfvhDVi7YPJscZXdEvEvKZd7S.js:2:87424)\n    at r (/tmp/dMmOcn/QmP1jrivfmv5KtvfSKXBzSfvhDVi7YPJscZXdEvEvKZd7S.js:2:463136)\n    at Object.1048 (/tmp/dMmOcn/QmP1jrivfmv5KtvfSKXBzSfvhDVi7YPJscZXdEvEvKZd7S.js:2:96048)\n    at r (/tmp/dMmOcn/QmP1jrivfmv5KtvfSKXBzSfvhDVi7YPJscZXdEvEvKZd7S.js:2:463136)\n    at /tmp/dMmOcn/QmP1jrivfmv5KtvfSKXBzSfvhDVi7YPJscZXdEvEvKZd7S.js:2:463650"},"message":"not supported ds @substrate/Moonbeam"}
{"level":"error","timestamp":"2022-09-01T13:33:53.700Z","pid":7,"hostname":"subquery-15905-indexer-deployment-676cd969c-g4b7d","category":"subql-node","payload":{"type":"error","name":"ReferenceError","message":"atob is not defined","stack":"ReferenceError: atob is not defined\n    at /tmp/dMmOcn/QmP1jrivfmv5KtvfSKXBzSfvhDVi7YPJscZXdEvEvKZd7S.js:2:52065\n    at Module.9823 (/tmp/dMmOcn/QmP1jrivfmv5KtvfSKXBzSfvhDVi7YPJscZXdEvEvKZd7S.js:2:52161)\n    at r (/tmp/dMmOcn/QmP1jrivfmv5KtvfSKXBzSfvhDVi7YPJscZXdEvEvKZd7S.js:2:463136)\n    at Object.972 (/tmp/dMmOcn/QmP1jrivfmv5KtvfSKXBzSfvhDVi7YPJscZXdEvEvKZd7S.js:2:95292)\n    at r (/tmp/dMmOcn/QmP1jrivfmv5KtvfSKXBzSfvhDVi7YPJscZXdEvEvKZd7S.js:2:463136)\n    at Object.9684 (/tmp/dMmOcn/QmP1jrivfmv5KtvfSKXBzSfvhDVi7YPJscZXdEvEvKZd7S.js:2:87424)\n    at r (/tmp/dMmOcn/QmP1jrivfmv5KtvfSKXBzSfvhDVi7YPJscZXdEvEvKZd7S.js:2:463136)\n    at Object.1048 (/tmp/dMmOcn/QmP1jrivfmv5KtvfSKXBzSfvhDVi7YPJscZXdEvEvKZd7S.js:2:96048)\n    at r (/tmp/dMmOcn/QmP1jrivfmv5KtvfSKXBzSfvhDVi7YPJscZXdEvEvKZd7S.js:2:463136)\n    at /tmp/dMmOcn/QmP1jrivfmv5KtvfSKXBzSfvhDVi7YPJscZXdEvEvKZd7S.js:2:463650"},"message":"Node failed to start"}

```

I have no problem deploying it on my previous computer, but I don't know why.

**Comment by stwiname** [comment]
Hi @Cupnfish 

We have run into the same issue because of other dependencies updating. Can you please update to the latest version of the datasource processor (`@subql/moonbeam-evm-processor` by the looks of things). Within the lates version we also include a prebundled version that should avoid this issue. The path would be something like `./node_modules/@subql/moonbeam-evm-processor/dist/bundle.js`.

Hopefully that fixes your issue.

**Comment by Cupnfish** [comment]
Thanks, but it didn't solve my problem, I solved my problem by:

https://github.com/subquery/subquery-network-subql-project/pull/31/files

**Comment by Cupnfish** [comment]
I used the solution mentioned in https://github.com/subquery/subql/issues/1277#issuecomment-1246478722 , but I got a new error
```shell
subquery-node_1   | 2022-09-14T11:06:08.837Z <BlockDispatcherService> ERROR failed to index block at height 895460 handleTransfer(VMError: Cannot find module 'http'
subquery-node_1   |     at DefaultResolver.resolveFull (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:110:9)
subquery-node_1   |     at DefaultResolver.resolveFull (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:317:16)
subquery-node_1   |     at DefaultResolver.resolve (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:105:15)
subquery-node_1   |     at VM2 Wrapper.apply (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/bridge.js:485:11)
subquery-node_1   |     at requireImpl (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/setup-node-sandbox.js:84:28)
subquery-node_1   |     at require (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/setup-node-sandbox.js:165:10)
subquery-node_1   |     at Object.3685 (/app/dist/index.js:2:783212)
subquery-node_1   |     at r (/app/dist/index.js:2:851906)
subquery-node_1   |     at Object.8027 (/app/dist/index.js:2:376787)
subquery-node_1   |     at r (/app/dist/index.js:2:851906)) VMError: Cannot find module 'http'
subquery-node_1   | node:internal/process/promises:279
subquery-node_1   |             triggerUncaughtException(err, true /* fromPromise */);
subquery-node_1   |             ^
subquery-node_1   |
subquery-node_1   | VMError: Cannot find module 'http'
subquery-node_1   |     at DefaultResolver.resolveFull (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:110:9)
subquery-node_1   |     at DefaultResolver.resolveFull (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:317:16)
subquery-node_1   |     at DefaultResolver.resolve (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/resolver.js:105:15)
subquery-node_1   |     at VM2 Wrapper.apply (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/bridge.js:485:11)
subquery-node_1   |     at requireImpl (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/setup-node-sandbox.js:84:28)
subquery-node_1   |     at require (/usr/local/lib/node_modules/@subql/node/node_modules/vm2/lib/setup-node-sandbox.js:165:10)
subquery-node_1   |     at Object.3685 (/app/dist/index.js:2:783212)
subquery-node_1   |     at r (/app/dist/index.js:2:851906)
subquery-node_1   |     at Object.8027 (/app/dist/index.js:2:376787)
subquery-node_1   |     at r (/app/dist/index.js:2:851906) {
subquery-node_1   |   code: 'ENOTFOUND',
subquery-node_1   |   handler: 'handleTransfer'
subquery-node_1   | }
```

**Comment by kushagra1618** [comment]
https://github.com/subquery/subql/issues/1277#issuecomment-1246606699

I am also facing this issue at this step, kindly suggest some potential fix

**Comment by jiqiang90** [comment]
Hi @Cupnfish looks like a different issue, can you share a repo so I could look into it and test it locally? Thanks

**Comment by jamesbayly** [comment]
@kushagra1618 can you share your repo?

**Comment by jamesbayly** [comment]
@jiqiang90 
![telegram-cloud-photo-size-4-5938165936446094982-w](https://user-images.githubusercontent.com/46693720/213941675-7aa87459-19a8-4769-b838-32691f7e128d.jpg)

Error occurs due to this line 
https://github.com/heroesofnft/marketplace-subql/blob/main/src/mappings/mappingHandlers.ts#L236

**Comment by jiqiang90** [comment]
> @jiqiang90 ![telegram-cloud-photo-size-4-5938165936446094982-w](https://user-images.githubusercontent.com/46693720/213941675-7aa87459-19a8-4769-b838-32691f7e128d.jpg)
> 
> Error occurs due to this line https://github.com/heroesofnft/marketplace-subql/blob/main/src/mappings/mappingHandlers.ts#L236

Add     `abab` to project dependencies, and add following line to the top of `src/index.ts`, this should fix it

``` typesscripts
import {atob} from 'abab';
global.atob = atob;
```

**Comment by bilgin-kocak** [comment]
> > @jiqiang90 ![telegram-cloud-photo-size-4-5938165936446094982-w](https://user-images.githubusercontent.com/46693720/213941675-7aa87459-19a8-4769-b838-32691f7e128d.jpg)
> > Error occurs due to this line https://github.com/heroesofnft/marketplace-subql/blob/main/src/mappings/mappingHandlers.ts#L236
> 
> Add `abab` to project dependencies, and add following line to the top of `src/index.ts`, this should fix it
> 
> ```
> import {atob} from 'abab';
> global.atob = atob;
> ```

This solution did not work. Same error occurred. You can find the repo below.
https://github.com/heroesofnft/marketplace-subql

**Comment by jiqiang90** [comment]
> > > @jiqiang90 ![telegram-cloud-photo-size-4-5938165936446094982-w](https://user-images.githubusercontent.com/46693720/213941675-7aa87459-19a8-4769-b838-32691f7e128d.jpg)
> > > Error occurs due to this line https://github.com/heroesofnft/marketplace-subql/blob/main/src/mappings/mappingHandlers.ts#L236
> > 
> > 
> > Add `abab` to project dependencies, and add following line to the top of `src/index.ts`, this should fix it
> > ```
> > import {atob} from 'abab';
> > global.atob = atob;
> > ```
> 
> This solution did not work. Same error occurred. You can find the repo below. https://github.com/heroesofnft/marketplace-subql

Hi I was testing with your repo and it worked. Atob suppose add to `src/index.ts`, before everything else is imported

```
import {atob} from 'abab';
global.atob = atob;
export * from './mappings/mappingHandlers'
import "@polkadot/api-augment"
```
