### ISSUE TITLE
Error indexing blocks with subql-node > 1.6.1

### ISSUE THREAD

**Issue by prashantasdeveloper** [subquery/subql#1292]
### Prerequisites

* [x] Are you running the latest version(s)?
* [x] Did you check the [debugging guide](https://doc.subquery.network/academy/tutorials_examples/debug-projects.html#how-to-debug-a-subquery-project)?
* [x] Did you check the [FAQs](https://doc.subquery.network/faqs/faqs.html) and [Discussions](https://github.com/subquery/subql/discussions)?
* [x] Are you reporting to the correct repository?
* [x] Did you search for an existing issue or pull request?

### Description

I was trying to update subql-node version to v1.9.1 and started getting the following error while indexing the polymesh testnet chain at block [6198](https://polymesh-testnet.subscan.io/block/6918) - 
```
2022-09-13 04:51:57        RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: Unable to decode storage system.events:: createType(Vec<EventRecord>):: Vec<EventRecord>:: Decoded input doesn't match input, received 0x0c0000000000000050b27c120000000002000000010000002801040000000000…00000000000000000000000001000000000103070408c9479b00000000000000 (96 bytes), created 0x0c0000000000000050b27c120000000002000000010000002801040000000000…00000000000000000001000000000103070408c9479b00000000000000000000 (99 bytes)

2022-09-13T04:51:57.182Z <fetch> ERROR failed to fetch events at block 0x633b8e81e111b8e9353c99adef52c2def3224b69a2e47280ba34c15553b1cb4e 
```
I already had indexed this particular block using version 1.0.0 of subql-node and was trying to upgrade the version to use the `workers` functionality. I even tried version 1.6.1 for subql-node (after which polkadot 9 support was introduced) , but again I get stuck in the same block. 

Is this something that anyone else has faced where latest version is unable to fetch and decode the block ?

### Details

These details can help to reproduce the environment the issue is occurring

**Local Environment:** @subql/cli/1.6.0 darwin-x64 node-v16.14.2
**Query Version:** latest
**Indexer Version:** >=1.6.1
**Network Details:**
  * RPC - wss://testnet-rpc.polymesh.live/
  * Block height - 6918

**Comment by Neopallium** [comment]
For reference the events in that block:
```json
{"event": {"System": {"ExtrinsicSuccess": [{"class": {"Mandatory": null}, "pays_fee": {"Yes": ()}, "weight": 310162000}]}}, "phase": {"ApplyExtrinsic": 0}, "topics": []}

{"event": {"Treasury": {"TreasuryReimbursement": ["polymesh_primitives::identity_id::IdentityId", 0.131388]}}, "phase": {"ApplyExtrinsic": 1}, "topics": []}

{"event": {"System": {"ExtrinsicFailed": [{"Module": {"index": 7, "error": 4}}, {"class": {"Normal": null}, "pays_fee": {"Yes": null}, "weight": 2605173000}]}}, "phase": {"ApplyExtrinsic": 1}, "topics": []}
```
The chain was using Substrate 3.0.0 release for that block.  The `sp_runtime::ModuleError` type was only 2 bytes in that release.  We think that issues is that for newer Substrate releases that type is 5 bytes long.

**Comment by jiqiang90** [comment]
<img width="1374" alt="image" src="https://user-images.githubusercontent.com/10431657/190033642-31d42b74-efb8-4350-8af5-bac8257baeb9.png">

**Comment by Neopallium** [comment]
The chain is already up to date with the latest Substrate metadata.  That block is from when we were running with Substrate 3.0 which doesn't have the on-chain metadata for custom types.  We provide the schema for the custom types for each of our `spec_version` releases.

sub-query was working with the schema types that we provided before and fully processed our testnet & mainnet chains.  But the newer version is failing.  Was there a change to how we need to provide the schemas?

**Comment by prashantasdeveloper** [comment]
@jiqiang90 Any other suggestions on how we should proceed on this?

**Comment by prashantasdeveloper** [comment]
I was able to tackle this by adding `"DispatchErrorModule": "DispatchErrorModuleU8"` to the chain types.

**Comment by jamesbayly** [comment]
I suggest contributing this change directly back to the spec types back to the type definitions file for Polymesh (`@polymathnetwork/polymesh-types`) so you don't have to override it in each SubQuery project in the future.
