### ISSUE TITLE
IPFS Upload Limit

### ISSUE THREAD

**Issue by jamesbayly** [subquery/subql#1319]
### Description

Running `subql publish` on this project (https://github.com/Phala-Network/stakepool-subquery/tree/staging) causes the following error

![telegram-cloud-document-5-6165657726455121623](https://user-images.githubusercontent.com/46693720/192223428-597d0067-4a5a-4d20-b732-3fb84f41091d.jpg)

**Comment by jamesbayly** [comment]
It been set to max 50 mb

**Comment by jiqiang90** [comment]
Hi I manually published for you, please use `QmVDTNpheAk3ACTYtqqKKGrbjwPThGuW9SaWo9cvAkS1g9`
