### ISSUE TITLE
Codgen --file flag broken

### ISSUE THREAD

**Issue by jamesbayly** [subquery/subql#1332]
### Prerequisites

* [ ] Are you running the latest version(s)?
* [ ] Did you check the [debugging guide](https://doc.subquery.network/academy/tutorials_examples/debug-projects.html#how-to-debug-a-subquery-project)?
* [ ] Did you check the [FAQs](https://doc.subquery.network/faqs/faqs.html) and [Discussions](https://github.com/subquery/subql/discussions)?
* [ ] Are you reporting to the correct repository?
* [ ] Did you search for an existing issue or pull request?

### Description

Can't run `yarn codegen --file=./project_juno.yaml` in https://github.com/subquery/cosmos-subql-dictionaries
The file flag appears broken

**Comment by jamesbayly** [comment]
@bz888  FYI

**Comment by stwiname** [comment]
Command should use -f instead of -l for the path
