### ISSUE TITLE
Error indexing kusama blocks 14914880 / 14893350

### ISSUE THREAD

**Issue by killbond007** [subquery/subql#1350]
### Prerequisites

* [x] Are you running the latest version(s)?
* [x] Did you check the [debugging guide](https://doc.subquery.network/academy/tutorials_examples/debug-projects.html#how-to-debug-a-subquery-project)?
* [x] Did you check the [FAQs](https://doc.subquery.network/faqs/faqs.html) and [Discussions](https://github.com/subquery/subql/discussions)?
* [x] Are you reporting to the correct repository?
* [x] Did you search for an existing issue or pull request?

I have test in  https://github.com/subquery/subql-starter/tree/main/Kusama/kusama-starter 
 block start :14914880

### Any other information

<img width="1157" alt="Screenshot 2022-10-17 at 13 49 28" src="https://user-images.githubusercontent.com/22051991/196169751-d02a81b9-8dfb-437e-8a15-b94f104dff10.png">

**Comment by jamesbayly** [comment]
We're looking into it

**Comment by stwiname** [comment]
I cant reproduce this with subql-node v1.10.2. 

@killbond007 can you please confirm what version you're using? And I assume you haven't changed the endpoint
