### ISSUE TITLE
Frontier EVM Event Args Undefined

### ISSUE THREAD

**Issue by jamesbayly** [subquery/subql#1368]
### Prerequisites

* [x] Are you running the latest version(s)?
* [x] Did you check the [debugging guide](https://doc.subquery.network/academy/tutorials_examples/debug-projects.html#how-to-debug-a-subquery-project)?
* [x] Did you check the [FAQs](https://doc.subquery.network/faqs/faqs.html) and [Discussions](https://github.com/subquery/subql/discussions)?
* [x] Are you reporting to the correct repository?
* [x] Did you search for an existing issue or pull request?

### Description

Trying to insert the args into a FrontierEVMEvent like so

```
type TransferEventArgs = [string, string, BigNumber] & {
  from: string;
  to: string;
  value: BigNumber;
};

export async function handleLog(
  logEvent: AvalancheLog<TransferEventArgs>
): Promise<void> {
```

Args is printed as `undefined`

### Steps to Reproduce

https://github.com/GuiGou12358/Algem-index-1

Example Event logs: https://blockscout.com/astar/tx/0x7f3c768602daf82c7f55e6638f982eecac8ed91c786be132d40c1752435ec3aa/logs

**Comment by jamesbayly** [comment]
This is because the ABI is not provided https://github.com/GuiGou12358/Algem-index-1/blob/master/project.yaml#L29-L31

**Comment by GuiGou12358** [comment]
You are right! It works fine now :)
Many thanks @jamesbayly
