### ISSUE TITLE
Allow for Better Inheritance and Extendability of Generated Entity Models

### ISSUE THREAD

**Issue by filo87** [subquery/subql#1373]
It would be great to be able to extend the definitions of generated models (from `yarn codegen`) and instantiate sub-classes with enhanced functionalities and logic by still maintaining the methods of the original parent Entity (like save(), get(), ...).

As an example, given a generated model Entity `Account` it should be possible to do something like this:
```ts
// this is the model generated from yarn codegen
class Account implements Entity {
...
}

// this is a child class extending Account somewhere else in the code
class AccountService extends Account {

async doStuff() {
      const service = await this.get('xyz') // <- Should return an instance of AccountService and NOT of Account
   }
}

```

for this purpose, all static methods returning an instance of the model Entity class should call the constructor and their own static methods as `this` and NOT as `className`.

here some examples:
https://github.com/subquery/subql/blob/b0f0bbc7aee48c0cf09c3e9a6cb4e1833bc2e8f7/packages/cli/src/template/model.ts.ejs#L42

https://github.com/subquery/subql/blob/b0f0bbc7aee48c0cf09c3e9a6cb4e1833bc2e8f7/packages/cli/src/template/model.ts.ejs#L66

**Comment by jamesbayly** [comment]
Interesting idea, our models are autogenerated so we would need to make sure that we don't overwrite the extended definitions

**Comment by stwiname** [comment]
@filo87, it seems like you have a good understanding of this problem. If you would like to make a PR we would happily add the feature.

**Comment by filo87** [comment]
Here the PR: #1377 

Not much to change, only in the ejs model template:
- The .create() static method should use this as reference so that when called from a child class it returns an instance of the child (with all methods in the prototype).
- All getters should also be adapted to call the this.create() method
- The entityProps type should be exported so it can be used in the child classes when using the .create() method

this should already do the job!

I quickly tried the template in my project and was OK...what additional testing is required?

**Comment by jiqiang90** [comment]
Close this now, pr merged
