### ISSUE TITLE
SQ CLI init removes comments from the original starter repos

### ISSUE THREAD

**Issue by deverka** [subquery/subql#1376]
### Prerequisites

* [x] Are you running the latest version(s)?
* [x] Did you check the [debugging guide](https://doc.subquery.network/academy/tutorials_examples/debug-projects.html#how-to-debug-a-subquery-project)?
* [x] Did you check the [FAQs](https://doc.subquery.network/faqs/faqs.html) and [Discussions](https://github.com/subquery/subql/discussions)?
* [x] Are you reporting to the correct repository?
* [x] Did you search for an existing issue or pull request?

### Description

When initialising any SQ project via SQ CLI all the comments are removed. So, all the useful notes and code suggestions in the code are gone.

### Steps to Reproduce

1. Run `subql init`
2. Choose any Cosmos starter (I checked this only for Cosmos starters)

**Expected behavior:** 
Comments are in the code 

**Actual behavior:** 
Comments are gone

### Success Criteria

All starter projects retain all comments in the `project.yaml`, `graphql.schema`, and all manifest files when initialised using the CLI

**Comment by stwiname** [comment]
A possible solution is to switch library and use this function https://eemeli.org/yaml/#documents
