### ISSUE TITLE
Update dictionary query end height

### ISSUE THREAD

**Issue by stwiname** [subquery/subql#1381]
Dictionary queries currently set a `lessThan` filter. This is just queryStartBlock + 10000. We can be smarter about what we set.

If there are more datasources that have a start height we are not up to we can set `lessThan` to be the next height.
If there are no more datasources then we don't need to set `lessThan`

**Comment by jiqiang90** [comment]
Can you provide an example when no more datasources?  or run out datasources?

I think it always good to set the `lessThan`, without provide a range, the dictionary will likely timeout
