### ISSUE TITLE
Ethereum Dictionary support

### ISSUE THREAD

**Issue by stwiname** [subquery/subql#1383]
Now that we have an ethereum sdk we should make existing dictionaries with EVM data compatible. The data stored should already be compatible (EVMLogs, EVMTransactions) but the dictionary will currently fail validation because of different chainIds.

We should provide some extra metadata on dictionaries to get the EVM chainId and update the ethereum SDK dictionary validation to check this extra metadata. 

This would apply to a few networks already: Moonbeam, Avax, Cronos

**Comment by stwiname** [comment]
## Solution

### Update dictionaries

We update the dictionary project to have a new entity for chain aliases:

```gql
type ChainAliases @entity {
  id: String!
  value: String!
}
```

We can then set these values from handlers if unset. e.g. 

```ts

// Global value in the handlers
let checkedAliases = false;

function setAliases() {
  if (checkedAliases) reutrn;

  // Set any chain Alisases

  checkedAliases = true;
}

// Call setAliases in another handler

```

We shouldnt hard code any values for being set in the aliases. We should get them from the injected api. 

### Update Ethreum sdk

In the dictionary service we should update the dictionary validation to check the metadata chain id as well as the ChainAliases for any matches.

**Comment by DeveloperInProgress** [comment]
https://github.com/subquery/subql-ethereum/pull/17

**Comment by DeveloperInProgress** [comment]
https://github.com/subquery/cosmos-subql-dictionaries/pull/12
