### ISSUE TITLE
subql-near: Implementation plan for NEAR protocol indexer

### ISSUE THREAD

**Issue by DeveloperInProgress** [subquery/subql#1406]
# NEAR Protocol's Indexer Framework

The NEAR protocol has a [straight forward RPC API](https://docs.near.org/api/rpc/introduction) that can be directly plugged into subql code. 

But, the ecosystem has evolved into building their own indexers with a [standard indexer framework](https://docs.near.org/concepts/advanced/near-indexer-framework). However, this indexer framework has a hard requirement on hosting and there will be changes in the code as the protocol evolves over time. 

# NEAR Lake

To deal with that problem, NEAR Lake Indexer was released. It is an indexer built on top of NEAR Indexer framework. It watches the blockchain and stores all events/data from the blockchain as JSON files on AWS S3 or S3 compatible storage. 

There is a companion library to NEAR Lake Indexer called the [NEAR Lake Framework](https://docs.near.org/concepts/advanced/near-lake-framework). It allows us to build our own indexer that watches a stream of blocks from a NEAR Lake data source and allows us to create our logic to process that data. It is highly recommended to use this framework for our indexer solutions. 

# Implementing NEAR Lake in SubQuery

There are two possible ways to implement NEAR Lake in SubQuery:

1.) Use the [NEAR Lake Framework JS](https://github.com/near/near-lake-framework-js) package to stream data directly into subql and process them. But, since the data is directly streamed from AWS S3, AWS credentials are needed to access this data and the AWS user pays the bill for it. 

2.) we can use the NEAR Lake framework to pre-index block, transactions and event data in a postgres database and wrap an API around it. This API endpoint can in turn be used inside subql to retrieve the pre-indexed data.

**Comment by stwiname** [comment]
The chosen option is to go with the RPC API for decentralisation reasons. 

We can use the NEAR Lake to generate a dictionary at a later stage
