### ISSUE TITLE
[Ethereum] Block finalization

### ISSUE THREAD

**Issue by stwiname** [subquery/subql#1418]
The Ethereum SDK doesn't currently have support for block finalization status. But the ethereum sdk has support for multiple eth rpc chains including Avalanche, Polygon, Moonbeam, etc.

Requirements:

- Bring back unfinalizedBlocks service that is used in the main sdk
- Support Ethereum consensus with finalized blocks
    - We should be able to use the appropriate `BlockTag` with ethers js https://github.com/ethers-io/ethers.js/issues/3091
- A way to validate and determine if the right finalization protocol is being used. e.g throw an error if unfinalized blocks is used with Avalanche yet we don't have specific finalization support.
- Avoid using beacon APIs if possible, so we don't need to provide another endpoint

Other resources:

https://beaconscan.com/
https://ethereum.github.io/beacon-APIs/#/

**Comment by DeveloperInProgress** [comment]
https://github.com/subquery/subql-ethereum/pull/19
