### ISSUE TITLE
Workers failing to start

### ISSUE THREAD

**Issue by bz888** [subquery/subql#1450]
### Prerequisites

* [x] Are you running the latest version(s)?
* [x] Did you check the [debugging guide](https://doc.subquery.network/academy/tutorials_examples/debug-projects.html#how-to-debug-a-subquery-project)?
* [x] Did you check the [FAQs](https://doc.subquery.network/faqs/faqs.html) and [Discussions](https://github.com/subquery/subql/discussions)?
* [x] Are you reporting to the correct repository?
* [x] Did you search for an existing issue or pull request?

### Description
[bug]

### Details
These details can help to reproduce the environment the issue is occurring
Failing to start workers `subql-node` versions >= `1.14.2-2`

### Steps to Reproduce
Use any `subql-node` versions >=`1.14.2-2` , run locally in any starter project (any subql project)
with the command `subql-node -f . --workers=2` 

**Example project:** [A link to a minimal example that can reproduce the issue]
subql-starter, polkadot
**Expected behavior:** [What you expected to happen]
Expected to be functioning
**Actual behavior:** [What actually happened]
Throws ` <worker: 1> ERROR Worker exited with code 1 `

**Comment by jiqiang90** [comment]
Fixes #1453
