### ISSUE TITLE
qraphql composite index

### ISSUE THREAD

**Issue by pohmelie** [subquery/subql#1455]
It is not a bug or a feature issue. But, is it possible to create a composite index?
I have success with only something like:
```
...
from: String! @index
to: String! @index
...
```
in `schema.graphql` and I don't see any docs on this.

**Comment by jamesbayly** [comment]
It is not currently possible to make a composite index

**Comment by jiqiang90** [comment]
Thanks, we can add this feature soon.  

We will need to figure out a better way to define it in `graphql.schema`

Ref: https://sequelize.org/docs/v6/other-topics/indexes/

```
    // Creates a multi column partial index

    {
      name: 'public_by_author',
      fields: ['author', 'status'],
      where: {
        status: 'public'
      }
    },


```
