### ISSUE TITLE
Support string literals docs in subquery project schema. 

### ISSUE THREAD

**Issue by lamcc21** [subquery/subql#1468]
### Description

Improve generated schema docs (in playground) by supporting string literals in subquery project schema. 

e.g. 

``` gql
"""some information about this entity"""
type Indexer @entity {
     """this id is the indexer address"""
     id: String!
     ...other fields
}
```

This is useful because you can get a description about the fields/entities you are querying without going to the subquery project code.

**Comment by stwiname** [comment]
https://github.com/graphile/postgraphile/blob/main/examples/forum/TUTORIAL.md#table-documentation

**Comment by stwiname** [comment]
It turns out we already support this. @DeveloperInProgress is going to add some documentation.

**Comment by stwiname** [comment]
https://github.com/subquery/documentation/pull/334
