### ISSUE TITLE
`subql publish` failling

### ISSUE THREAD

**Issue by bz888** [subquery/subql#1477]
### Prerequisites

* [x] Are you running the latest version(s)?
* [x] Did you check the [debugging guide](https://doc.subquery.network/academy/tutorials_examples/debug-projects.html#how-to-debug-a-subquery-project)?
* [x] Did you check the [FAQs](https://doc.subquery.network/faqs/faqs.html) and [Discussions](https://github.com/subquery/subql/discussions)?
* [x] Are you reporting to the correct repository?
* [x] Did you search for an existing issue or pull request?

### Description

When using `subql publish` it fails in non unix environment
### Steps to Reproduce
`@subql/cli` version 1.10.1
run `subql publish` in the root of a project

**Comment by stwiname** [comment]
The error message:
```
TypeError: The "path" argument must be of type string. Received undefined
    Code: ERR_INVALID_ARG_TYPE
```

**Comment by DeveloperInProgress** [comment]
https://github.com/subquery/subql/pull/1502

home directory for windows and unix systems are different from each other. I added a fix to get home directory based on the platform. 

But, I think we should use a more platform agnostic way like this:
`const homedir = require('os').homedir();`

**Comment by stwiname** [comment]
Fixed in https://github.com/subquery/subql/pull/1502
