### ISSUE TITLE
indexer stuck with empty header

### ISSUE THREAD

**Issue by shunjizhan** [subquery/subql#1481]
### Prerequisites

* [x] Are you running the latest version(s)?
* [x] Did you check the [debugging guide](https://doc.subquery.network/academy/tutorials_examples/debug-projects.html#how-to-debug-a-subquery-project)?
* [x] Did you check the [FAQs](https://doc.subquery.network/faqs/faqs.html) and [Discussions](https://github.com/subquery/subql/discussions)?
* [x] Are you reporting to the correct repository?
* [x] Did you search for an existing issue or pull request?

### Description

`subql/node@v1.17.0` reported the error on Karura
```
Error: Unable to retrieve header and parent from supplied hash
failed to fetch events at block 0xdcdd89927d8a348e00257e1ecc8617f45edb5118efff3ea2f9961b2ad9b7690a
```

However, this block doesn't exist in Karura. @xlc mentioned it might be empty header hash.

Also this can occur at at different blocks:
- one of our partners saw this on block ~2611615 https://github.com/AcalaNetwork/bodhi.js/issues/620#issuecomment-1367455906
- we encounter it at block ~3356511

![Screenshot 2023-01-05 at 11 19 44](https://user-images.githubusercontent.com/16548786/210695997-5cfea505-b502-45f0-994c-a41ef92940be.png)

The issue was resolved by a manual full restart of the indexer (docker auto restart didn't work)

**Comment by jiqiang90** [comment]
We found this is due to invalid block on the endpoint, switch endpoint this works fine. 

It is easy to reproduce with following script;

![image](https://user-images.githubusercontent.com/10431657/213584690-26369d41-ec08-4800-80a2-f5a8c6dba755.png)


``` typescript

const { ApiPromise, WsProvider } = require(`@polkadot/api`)
const provider = new WsProvider('wss://karura-rpc-0.aca-api.network/');
async function main(){
    const api = await ApiPromise.create({
        provider,
    });
    const blockHash = await api.rpc.chain.getBlockHash(3467086);
    console.log(blockHash.toString())
    const block = await api.rpc.chain.getBlock(blockHash)
    console.log(block.block.header.hash.toString())
    process.exit(0)
}

main().catch(e=>process.exit(1));

```

We will improve logging for this.
