### ISSUE TITLE
Dynamic DS unable to retrieve data from store

### ISSUE THREAD

**Issue by bz888** [subquery/subql#1486]
### Prerequisites
* [x] Are you running the latest version(s)?
* [x] Did you check the [debugging guide](https://doc.subquery.network/academy/tutorials_examples/debug-projects.html#how-to-debug-a-subquery-project)?
* [x] Did you check the [FAQs](https://doc.subquery.network/faqs/faqs.html) and [Discussions](https://github.com/subquery/subql/discussions)?
* [x] Are you reporting to the correct repository?
* [x] Did you search for an existing issue or pull request?

### Description
The example project uses `subql-ethereum` https://github.com/subquery/subql-ethereum

When dealing with dynamicDatasources, it cannot `get` data from the store
[Example project](https://github.com/bz888/dynamic-ds-example)
In the example:

`handleInitialize` (core.ts)  is a dynamic datasource that updates `pool` when used
however, it fails to retrieve the `pool` data saved by `handlePoolCreated` (factory.ts)
<img width="1197" alt="Screenshot 2023-01-11 at 7 35 10 AM" src="https://user-images.githubusercontent.com/89335033/211636820-47a99023-d521-45a5-8e1c-2e9ebc8dcb46.png">

### Steps to Reproduce

1. [yarn && yarn codegen && yarn build ]
- For the example project, you would have to manually update the "@subql/types" to "@subql/types-ethereum" to succeed  `yarn build`
2. [ To run the project: `yarn start:docker` ]
- It would then output the error in the screenshot above, as `const pool = await Pool.get(event.address)` in `handleInitialize` outputs `undefined`

**Expected behavior:** [What you expected to happen]
- The dynamic datasource should be able to access `pool` 
**Actual behavior:** [What actually happened]
- It does not

**Comment by stwiname** [comment]
This was an issue with the project. 

This [line](https://github.com/bz888/dynamic-ds-example/blob/main/src/mappings/factory.ts#L47) should be `const pool = new Pool(event.args.pool)`
