### ISSUE TITLE
Expose some  Prometheus metrics to track cause of slow indexing

### ISSUE THREAD

**Issue by 454076513** [subquery/subql#1517]
Some developer complain indexing speed very slow.  but they no idea why it so slow . Now track the issue by enabled `--profiler` to check logs.  it is inconvenient to observe. We can expose this metric to prometheus, e.g. fetch block speed, speed for each handler and write database speed or more. With these metric output can be output Hosted Service. It can help developers improve their codes.

**Comment by jamesbayly** [comment]
Completed via https://academy.subquery.network/run_publish/monitor.html
