### ISSUE TITLE
@index when using historical feature

### ISSUE THREAD

**Issue by bz888** [subquery/subql#1518]
### Prerequisites

* [x] Are you running the latest version(s)?
* [x] Did you check the [debugging guide](https://doc.subquery.network/academy/tutorials_examples/debug-projects.html#how-to-debug-a-subquery-project)?
* [x] Did you check the [FAQs](https://doc.subquery.network/faqs/faqs.html) and [Discussions](https://github.com/subquery/subql/discussions)?
* [x] Are you reporting to the correct repository?
* [x] Did you search for an existing issue or pull request?

### Description
Currently, when adding @index to schema, `node` would fail due to assertion error ( when historical is enabled )

### Details

Should allow @index to be added when using historical feature.

### Steps to Reproduce
https://github.com/minhnhat-dnt/subql-test-unique-index/tree/master/subql-starter

Step to run: 
1. yarn install
2. yarn codegen
3. yarn start

when running, it would throw `Error: Failed to getOneByField Entity StarterEntity with field entityId: AssertionError [ERR_ASSERTION]: to query by field entityId, an unique index must be created on model StarterEntity`

**Comment by jiqiang90** [comment]
When historical enabled, `getOneByField` use `findOne` will looking for `_id` field, which isn't correct, and it will not find any match. It should have similar approach as `getByField`,  and we want to get `id` as the field .

**Comment by jiqiang90** [comment]
Problem still exist in v2.0.2, will have patch release to fix this.
