### ISSUE TITLE
Unexpected behavior for the --unsafe flag in query service

### ISSUE THREAD

**Issue by stepanLav** [subquery/subql#1522]
### Prerequisites

* [x] Are you running the latest version(s)?
* [x] Did you check the [debugging guide](https://doc.subquery.network/academy/tutorials_examples/debug-projects.html#how-to-debug-a-subquery-project)?
* [x] Did you check the [FAQs](https://doc.subquery.network/faqs/faqs.html) and [Discussions](https://github.com/subquery/subql/discussions)?
* [x] Are you reporting to the correct repository?
* [x] Did you search for an existing issue or pull request?

### Description

[Description of the bug or feature]
[Unsafe mode](https://academy.subquery.network/run_publish/references.html#unsafe-query-service) for query service doesn't clean up restrictions on 100 entities for one of our entity.

### Details

**Local Environment:**  @subql/cli/1.11.0 darwin-arm64 node-v16.17.0
**Query Version:**  onfinality/subql-query:v1.10.2
**Indexer Version:**  onfinality/subql-node:v1.18.0
**Network Details:**
  * Test network - https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fnovasama.uz#/extrinsics
  * [Block height, a block height where the issue is happening] - 21,697
  * [Dictionary endpoint, if used] -

### Steps to Reproduce

1. Deploy project with unsafe flag
2. Generate many DelegatorVoting entities
3. Try to get more than 100 entities in one request
```curl
curl --location --request POST 'https://api.subquery.network/sq/nova-wallet/nova-wallet-gov-test' \
--header 'Content-Type: application/json' \
--header 'Cookie: connect.sid=s%3A0ZBbY_265dkUwQt8s-cTdPpVsZAVYVyp.diCQTIJdfCAT3RvxFPkrvBt5mxnXvLZyl5mE0el2b0E' \
--data-raw '{"query":"query  {\n    delegatorVotings {\n        nodes{\n            delegator\n            id\n            parentId\n            parent {\n                referendumId\n                id\n                delegateId\n            }\n        }\n    }\n}","variables":{}}'
```

to get all delegations can be used request for particular delegator:
```curl
curl --location --request POST 'https://api.subquery.network/sq/nova-wallet/nova-wallet-gov-test' \
--header 'Content-Type: application/json' \
--header 'Cookie: connect.sid=s%3A0ZBbY_265dkUwQt8s-cTdPpVsZAVYVyp.diCQTIJdfCAT3RvxFPkrvBt5mxnXvLZyl5mE0el2b0E' \
--data-raw '{"query":"query ($address: String!){\n          delegations(filter: {delegateId: {equalTo: $address}}) {\n            nodes {\n              delegator\n              id\n              delegation\n            }\n          }\n        }","variables":{"address":"HNZata7iMYWmk5RvZRTiAsSDhV8366zq2YGb3tLH5Upf74F"}}'
```

**Example project:** 
- [example project](https://explorer.subquery.network/subquery/nova-wallet/nova-wallet-gov-test)
- [link to project on gh](https://github.com/nova-wallet/subquery-governance)

**Expected behavior:**
Return all available entities

**Actual behavior:** 
Return only 100

**Comment by jamesbayly** [comment]
Relates to https://github.com/subquery/subql/pull/1514/files#diff-4fb5004c488ef199f2cc2495105a47323e18b37a0795bcf73eeaf0b291e3a4f5

**Comment by jiqiang90** [comment]
I think this is fixed with `query-limit` flag, close now
