### ISSUE TITLE
Unfinalized blocks for EVM

### ISSUE THREAD

**Issue by stwiname** [subquery/subql#1524]
### Description

Support for unfinalized blocks on EVM networks where there is no finalization mechanism and we have to rely on probability and n number of new blocks to pass.

### Details

- The number of blocks to be finalized should be configurable
- If we can detect what the network finalization mechanism (ethereum)  is then we can use the appropriate solution

**Comment by stwiname** [comment]
Mostly completed with https://github.com/subquery/subql-ethereum/pull/36

The only remaining thing is to make the number of blocks to be configurable

**Comment by jamesbayly** [comment]
I would like to bump the priority up on this, potentially to include in the 2.0 release

**Comment by jamesbayly** [comment]
Needs docs on https://github.com/subquery/documentation/blob/master/docs/run_publish/references.md
