### ISSUE TITLE
Allow specifying `where` field on store `getOneByField` and `getByField`

### ISSUE THREAD

**Issue by stwiname** [subquery/subql#1531]
### Description
To allow more advanced querying of existing state from within mapping handlers we should update the getter methods to allow `AND` and `OR` filters

### Relevant code
https://github.com/subquery/subql/blob/main/packages/node-core/src/indexer/store.service.ts
https://github.com/subquery/subql/blob/main/packages/types/src/interfaces.ts#L17

**Comment by jamesbayly** [comment]
An example from a customer

"Say I index every block, storing a number called X and I want to query the average of X in a range of start_block, end_block."

**Comment by stwiname** [comment]
Now that we have the cache this gets a little more complex. 

But I think a short term solution is that we could flush and await if there's any pending operations for that entity. So we can always rely on querying the db and not incorporate any cached data into the result.

**Comment by jamesbayly** [comment]
If we just extend the pagination queries wouldn't that let them get around this? 
`options?: { limit?: number; offset?: number }` to all getters

**Comment by jamesbayly** [comment]
Working on via https://github.com/subquery/subql/issues/1756
