### ISSUE TITLE
Enum support broken

### ISSUE THREAD

**Issue by darwinsubramaniam** [subquery/subql#1573]
### Prerequisites

* [x] Are you running the latest version(s)?
* [ ] Did you check the [debugging guide](https://doc.subquery.network/academy/tutorials_examples/debug-projects.html#how-to-debug-a-subquery-project)?
* [x] Did you check the [FAQs](https://doc.subquery.network/faqs/faqs.html) and [Discussions](https://github.com/subquery/subql/discussions)?
* [x] Are you reporting to the correct repository?
* [x] Did you search for an existing issue or pull request?

### Description

`
enum PoolState {
  OPEN
  BLOCKED
  DESTROYING
}
`
Having the Enum in the schema.graphql , the 
SQL CREATE Type being triggered with following command 

`
STATEMENT:  CREATE TYPE "app".44c5edae3c as ENUM ('OPEN','BLOCKED','DESTROYING')
`
and the error from msgs 

`ERROR:  syntax error at or near ".44" at character 18`

The correct SQL could have been 
`
CREATE TYPE "app"."44c5edae3c" as ENUM ('OPEN','BLOCKED','DESTROYING')
`

### Details

These details can help to reproduce the environment the issue is occurring

**Local Environment:** [@subql/cli/1.12.3]
**Query Version:** [v1.11.0]
**Indexer Version:** [v1.20.0]
**Network Details:**
  * [Polkadot]

### Steps to Reproduce

1.  add in Enum into the schema.graphql
2.  npm run dev

**Comment by jiqiang90** [comment]
Hi Thanks @darwinsubramaniam , there is a fix https://github.com/subquery/subql/pull/1555/files, but haven't released yet.

**Comment by dutterbutter** [comment]
Experiencing the same issue.

**Comment by stwiname** [comment]
This has been released now in version `1.21.1`
