### ISSUE TITLE
How to link EOS to subquery? Have any tutorials？

### ISSUE THREAD

**Issue by raspberry-hu** [subquery/subql#1605]
I want to link EOS to subquery, but I don't know where to start, have any tutorials?

**Comment by seandotau** [comment]
not yet, but it's on our backlog.

**Comment by raspberry-hu** [comment]
can i join this project for eos？

**Comment by seandotau** [comment]
> can i join this project for eos？

Hey @raspberry-hu , do you mean help add EOS indexing? If yes, then sure. We'd welcome your contribution to this open source project :)

**Comment by jamesbayly** [comment]
@stwiname  any high level idea on what we need to do to support EOS

**Comment by raspberry-hu** [comment]
> > can i join this project for eos？
> 
> Hey @raspberry-hu , do you mean help add EOS indexing? If yes, then sure. We'd welcome your contribution to this open source project :)

yep, Thank you！

**Comment by stwiname** [comment]
Hi @raspberry-hu 

We don't have a concrete guide for how to support new chains but i'll point you in the right direction and can give you some support. 

We have this main repo that contains the Substrate implementation as well as common core functionality. We then have other repos that are essentially forks of this but remove the common functionality and add code specific to the chain.

The 2 i would suggest referring to are:
* https://github.com/subquery/subql-cosmos/
* https://github.com/subquery/subql-ethereum/

To break down the packages that need changes:
* `/common-eos`
    * This contains definitions for the project.yaml definition, the handler types and their filters.
* `/node`
    * This is the indexer that will fetch blocks from an EOS endpoint and will apply filters defined by the users project. 
    * This will also integrate the dictionary (we can discuss this in further detail later)
* `/types`
    * This defines the type of a block

We can communicate via other means if that is easier (discord/telegram etc.)
