### ISSUE TITLE
Manifest node options

### ISSUE THREAD

**Issue by stwiname** [subquery/subql#1634]
## Description

Certain features are currently configured through CLI arguments but should be configurable through the project manifest. This is fine when users run their project themselves or on the managed service but there's no option on the network. These settings are also generally not changed after the project is started

## Details

- We should support all existing relevant flags. historical, unfinalized blocks, unsafe?
- Aim to only make changes to common package and keep it as chain agnostic as possible
- Be general enough that we can easily add more options later
- Options provided in the manifest should be considered the "Default", but can still be overridden by CLI flags

**Comment by jamesbayly** [comment]
Docs needed

**Comment by jamesbayly** [comment]
@stwiname  need docs here
