### ISSUE TITLE
ABI codegen for event handlers

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#1671]
### Description
It's not always straightforward for developer to know all events in a contract, even they have the source code but due to contract inherit it might not be clear all events for a contract.
So developer will need to do a lot of researching before they can start defining handlers in project manifest.

### Details
1. A new cli subcommand to list all events for a given abi
2. A new cli subcommand to add event handler of selected event to project manifest
   1. good to have some interactions
   2. generate the handler function scaffold

**Comment by stwiname** [comment]
See what subsquid have done. Maybe some influence we can get
