### ISSUE TITLE
expose `chainId` and `runtimeChain` to use in handler

### ISSUE THREAD

**Issue by bz888** [subquery/subql#1681]
### Prerequisites

* [x] Are you running the latest version(s)?
* [x] Did you check the [debugging guide](https://doc.subquery.network/academy/tutorials_examples/debug-projects.html#how-to-debug-a-subquery-project)?
* [x] Did you check the [FAQs](https://doc.subquery.network/faqs/faqs.html) and [Discussions](https://github.com/subquery/subql/discussions)?
* [x] Are you reporting to the correct repository?
* [x] Did you search for an existing issue or pull request?

### Description
Allow users to get `chainId` and `networkName` it would be useful when running a multi-chain project

**Comment by stwiname** [comment]
Fixed in https://github.com/subquery/subql/pull/1684
