### ISSUE TITLE
Document Graphql Differences with the graph

### ISSUE THREAD

**Issue by stwiname** [subquery/subql#1691]
Including:
- Filters
- Pagination

FIrst step is to figure out what the differences are 

Including updating the docs for the graph migration document

**Comment by stwiname** [comment]
Based on research we are going to have a separate query service that will be compatible with the graph. Users will have to specify a different query runner in their project

Options:
* Get the graph node to connect to subquery db (fork or extract query client)
* A new query service, possibly built with golang
* A new query service using postgraphile

**Comment by jamesbayly** [comment]
@youssefea  a version of this should be published on our website docs https://onfinality.atlassian.net/wiki/spaces/~6293e449cd636500697a7972/pages/1932197891/subGraph+and+subql+graphQL+Compatibility
