### ISSUE TITLE
Dictionary for subql-ethereum not working

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#1699]
### Description

Dictionary is not used by the node.

### Details
Network: polygon, chainId: 137
Run with `-d=<dictionary-endpoint>`

No log say anything about dictionary but it is not used.

**Indexer Version: subql-node-ethereum v2.1.2

### Steps to Reproduce

**Expected behavior:** 
1. dictionary should be used
2. If it is not, there needs to be logs telling user that, and the reason.

**Actual behavior:**
only log I have is a debug log, `<dictionary> DEBUG Dictionary doesn't have an evmChainId set`

### Any other information

Is there any other information you would like to add?

**Comment by stwiname** [comment]
I think this has been resolved now. There was a problem with not logging that the dictionary start height was greater than the project start height.

Feel free to reopen if it still exists
