### ISSUE TITLE
BlockHandler ReferenceError [Error]: URL is not defined

### ISSUE THREAD

**Issue by jiqiang90** [subquery/subql#1701]
### Prerequisites

* [ ] Are you running the latest version(s)?
* [ ] Did you check the [debugging guide](https://doc.subquery.network/academy/tutorials_examples/debug-projects.html#how-to-debug-a-subquery-project)?
* [ ] Did you check the [FAQs](https://doc.subquery.network/faqs/faqs.html) and [Discussions](https://github.com/subquery/subql/discussions)?
* [ ] Are you reporting to the correct repository?
* [ ] Did you search for an existing issue or pull request?

### Description

Running project with block handler may face similar issue: 

```
ReferenceError [Error]: URL is not defined
    at Object.moduleId [as 22] (/Users/jiatwork/subql2/subql-starter/Kusama/kusama-starter/dist/webpack:/kusama-starter/node_modules/@polkadot/api-base/packageInfo.js:1:103)
    at n (/Users/jiatwork/subql2/subql-starter/Kusama/kusama-starter/dist/webpack:/kusama-starter/webpack/bootstrap:19:22)

```

This is due to update for polkadot api in the project if you have `    "@polkadot/api": "^10",`

To **temp** fix the project :

1. Remove yarn.lock
2. Change to `    "@polkadot/api": "10.1.4"`
3. yarn and build again.

### Details

These details can help to reproduce the environment the issue is occurring

**Local Environment:** [You can get this information from executing `subql version`.]
**Query Version:** [What is the version of the query service?]
**Indexer Version:** [What is the version of the indexer service?]
**Network Details:**
  * [Network]
  * [Block height, a block height where the issue is happening]
  * [Dictionary endpoint, if used]

### Steps to Reproduce

1. [First Step]
4. [Second Step]
5. [and so on...]

**Example project:** [A link to a minimal example that can reproduce the issue]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Any other information

Is there any other information you would like to add?

**Comment by stwiname** [comment]
We can safely add `url` package into the sandbox. It's a useful package and doesn't make any external requests

**Comment by jamesbayly** [comment]
This looks like a major right? What's the outcome? - update all the package versions to `"@polkadot/api": "^10.1.4",`?
