### ISSUE TITLE
UnhandledPromiseRejection

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#1731]
### Prerequisites

* [x] Are you running the latest version(s)?
* [ ] Did you check the [debugging guide](https://doc.subquery.network/academy/tutorials_examples/debug-projects.html#how-to-debug-a-subquery-project)?
* [ ] Did you check the [FAQs](https://doc.subquery.network/faqs/faqs.html) and [Discussions](https://github.com/subquery/subql/discussions)?
* [ ] Are you reporting to the correct repository?
* [ ] Did you search for an existing issue or pull request?

### Description

```
subql-node -f ipfs://QmNYsNZvM9XZuzkF3n6XcqFVxvMLfWYtEQHzszMFfNCkgt --network-endpoint=wss://polkadot.api.onfinality.io/public-ws -d "_" --dictionary-resolver=https://kepler-auth.subquery.network
```

```
2023-05-18T04:32:20.905Z <subql-node> INFO Current @subql/node version is 2.2.1 
2023-05-18T04:32:21.855Z <db> WARN Database does not support SSL connection, will try to connect without it 
2023-05-18T04:32:24.946Z <indexer> INFO indexer manager start 
2023-05-18T04:32:27.228Z <store> INFO Historical state is enabled 
2023-05-18T04:32:27.273Z <UnfinalizedBlocks> INFO Unfinalized blocks is disabled 
Flushing 6 records 1000
2023-05-18T04:32:28.682Z <dynamic-ds> INFO Loaded 0 dynamic datasources 
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "AxiosError: Request failed with status code 500".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

```

### Details

These details can help to reproduce the environment the issue is occurring

**Local Environment:** nodejs: v18.16.0
**Query Version:** [What is the version of the query service?]
**Indexer Version:** 2.2.1
**Network Details:**
  * [Network] polkadot
  * [Block height, a block height where the issue is happening]
  * [Dictionary endpoint, if used]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Example project:** [A link to a minimal example that can reproduce the issue]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Any other information

Is there any other information you would like to add?

**Comment by jiqiang90** [comment]
Unsure what happen there, but seems working with latest main 

<img width="1451" alt="image" src="https://github.com/subquery/subql/assets/10431657/1a67f02f-8b34-4def-bcaf-df061a0cb769">

**Comment by stwiname** [comment]
I think this was resolved in https://github.com/subquery/subql/pull/1739
