### ISSUE TITLE
how to support ethereum's network, like Sepolia or private ethereum blockchain?

### ISSUE THREAD

**Issue by zhangxizhang** [subquery/subql#1740]
how to support ethereum's network, like Sepolia or private ethereum blockchain?
a contract has been deployed in the Sepolia network and wants to index the transaction data within it. Now, I have replaced the chainId and dataSources in the project.yaml file, and started using the existing docker-compose file but reported an error. May I ask if the replacement was incorrect? What further configuration information needs to be changed?
![issue](https://github.com/subquery/subql/assets/34093938/ee3a4df2-0a90-447f-a3d3-b9790300a7a3)

**Comment by stwiname** [comment]
Hi @zhangxizhang  you need to update the network endpoint as well to point to Sepolia or private chain RPC endpoint.

**Comment by zhangxizhang** [comment]
> Hi @zhangxizhang you need to update the network endpoint as well to point to Sepolia or private chain RPC endpoint.

I try to change the endpoint in project.yaml and run the project. But  when the "docker-compose up" command runs, the image of priv-graphql-engine is not running healthily. I think the problem is priv-subquery-node, but I do not  know how to solve it, could you give me some advice ?
![1](https://github.com/subquery/subql/assets/34093938/b34640f3-611b-41fb-be87-cc538694e086)
![2](https://github.com/subquery/subql/assets/34093938/f548f366-9612-406e-99ea-f7d064e57ffc)
![3](https://github.com/subquery/subql/assets/34093938/2fda211b-4a9b-48c8-8c49-8da6b79c56fb)

**Comment by jamesbayly** [comment]
@zhangxizhang as per https://academy.subquery.network/build/manifest/ethereum.html#network-spec, you need to specify the (HTTP or WSS) RPC endpoint of the blockchain to be indexed - this must be a full archive node.

You can find some public listed RPCs here https://chainlist.org/chain/11155111

Etherscan's API is not an RPC endpoint

**Comment by jamesbayly** [comment]
@zhangxizhang did you manage to update the network endpoint, It should work after that?
