### ISSUE TITLE
Implement Retry logic for SafeEthProvider

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#1748]
### Prerequisites
* Use multi endpoints
* One of the endpoint is unstable

### Description
Currently when one endpoint that is picked to perform a contract query in the mapping failed, the node will crash.
It doesn't benefit from having multiple endpoints.

To overcome that, we can implement some retry logic in SafeEthProvider, try all endpoints before throw error.

### Details

it is wanted in subql-ethereum-node most and then in the node for other networks as well.

**Comment by DeveloperInProgress** [comment]
https://github.com/subquery/subql-ethereum/pull/110
