### ISSUE TITLE
Improve Substrate api requests

### ISSUE THREAD

**Issue by stwiname** [subquery/subql#1751]
Here are some screenshots of RPC requests for dictionary projects. It seems we are fetching headers and runtime versions twice for every block we fetch. 

We should only need to fetch the header and runtime version once for each block.

![Screenshot 2023-05-24 at 4 59 12 PM](https://github.com/subquery/subql/assets/3432810/a7ec1693-13ad-470a-a5af-1247826d4cca)
![Screenshot 2023-05-24 at 4 59 00 PM](https://github.com/subquery/subql/assets/3432810/1d1724c3-de91-4e8c-b091-ae14ec350a4b)

**Comment by jamesbayly** [comment]
@jiqiang90  would you be able to rerun this once this feature is in https://onfinality.atlassian.net/wiki/spaces/SQ/pages/1904214062/Performance+Comparisons?focusedCommentId=1906016338
