### ISSUE TITLE
Improved GetByField

### ISSUE THREAD

**Issue by jiqiang90** [subquery/subql#1756]
```
enum Expressions = {
'=',
'<',
'<=',
'>',
'>='
'in'
}
```

`getByFields(field_name: string, value: any, expression: Expression = '=')`
`getByFields(field_name: string, value: any, expression: Expression, field_name: string, value: any, expression: Expression)`

Always treat multiple conditions as an AND

**Comment by jiqiang90** [comment]
https://github.com/subquery/subql/issues/1531 Relate to this task

**Comment by ianhe8x** [comment]
@jiqiang90 are you proposing a chained builder pattern query method?
```
store.buildQuery().getByFields('field1', value).getByFields('field2',value).query();
```
They is new to the project and may cause some code style concerns.
We could just do this, align with the gql filter styles (and simpler)
```
getByFields({
[field]: {
  [comparer]: value
  } 
})
```
