### ISSUE TITLE
Better retry limit control for subql-ethereum

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#1776]
### Prerequisites

* [X] Are you running the latest version(s)?
* [x] Did you check the [debugging guide](https://doc.subquery.network/academy/tutorials_examples/debug-projects.html#how-to-debug-a-subquery-project)?
* [x] Did you check the [FAQs](https://doc.subquery.network/faqs/faqs.html) and [Discussions](https://github.com/subquery/subql/discussions)?
* [x] Are you reporting to the correct repository?
* [x] Did you search for an existing issue or pull request?

### Description
It's easily to reach max retries in subql-ethereum than subql-substrate, which makes it quite fragile.

I think the reason is we use BatchJsonrpcProvider, so maybe it is only one batch request failed, but we treat it as each individual sub requests failed, and easily it exceed the retry limit.

### Details

These details can help to reproduce the environment the issue is occurring

**Local Environment:** [You can get this information from executing `subql version`.]
**Query Version:** [What is the version of the query service?]
**Indexer Version:** subql-ethereum-node v2.2.2
**Network Details:**
  * [Network]
  * [Block height, a block height where the issue is happening]
  * [Dictionary endpoint, if used]

**Comment by stwiname** [comment]
Closing this as it can be addressed with https://github.com/subquery/subql/issues/1925
