### ISSUE TITLE
Improve mmr cache flush

### ISSUE THREAD

**Issue by jiqiang90** [subquery/subql#1795]
### Prerequisites

* [ ] Are you running the latest version(s)?
* [ ] Did you check the [debugging guide](https://doc.subquery.network/academy/tutorials_examples/debug-projects.html#how-to-debug-a-subquery-project)?
* [ ] Did you check the [FAQs](https://doc.subquery.network/faqs/faqs.html) and [Discussions](https://github.com/subquery/subql/discussions)?
* [ ] Are you reporting to the correct repository?
* [ ] Did you search for an existing issue or pull request?

### Description

1. Mmr cache flush should be independent from fetch service storeCache flush
2. mmr currently flush every 6 seconds or 1000 records (if handler triggered and post process block), we want it flush by its own frequency and its own threshold. 6 seconds seems too many mmr records were created, and blocking db transaction.
3. Establish its own db connection, unblock from fetching service

### Details

These details can help to reproduce the environment the issue is occurring

**Local Environment:** [You can get this information from executing `subql version`.]
**Query Version:** [What is the version of the query service?]
**Indexer Version:** [What is the version of the indexer service?]
**Network Details:**
  * [Network]
  * [Block height, a block height where the issue is happening]
  * [Dictionary endpoint, if used]

### Steps to Reproduce

1. [First Step]
6. [Second Step]
7. [and so on...]

**Example project:** [A link to a minimal example that can reproduce the issue]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Any other information

Is there any other information you would like to add?

**Comment by ianhe8x** [comment]
and stop using tx for mmr commits.
