### ISSUE TITLE
When will subquery support EOS indexing, or are there any suggestions for implementation?

### ISSUE THREAD

**Issue by liuliluren** [subquery/subql#1799]
if I want to implement EOS indexing,where should I start?

**Comment by stwiname** [comment]
Hi @hanhandehanpi 

This has been asked before, here is the previous issue where I left some details about how support could be added for EOS

https://github.com/subquery/subql/issues/1605

**Comment by stwiname** [comment]
Closing this as there is no plan to support EOS. A PR is always welcome.
