### ISSUE TITLE
`/mmrs` query always fail

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#1810]
### Prerequisites

* [ ] Are you running the latest version(s)?
* [ ] Did you check the [debugging guide](https://doc.subquery.network/academy/tutorials_examples/debug-projects.html#how-to-debug-a-subquery-project)?
* [ ] Did you check the [FAQs](https://doc.subquery.network/faqs/faqs.html) and [Discussions](https://github.com/subquery/subql/discussions)?
* [ ] Are you reporting to the correct repository?
* [ ] Did you search for an existing issue or pull request?

### Description

When I request 'http://localhost:3000/mmrs/latest' , I always get `{"statusCode":500,"error":"MMR Service sync has not been called"}`

### Details

These details can help to reproduce the environment the issue is occurring

**Indexer Version:** subql-node:v2.7.0
**Network Details:**

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Example project:** [A link to a minimal example that can reproduce the issue]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Any other information

Is there any other information you would like to add?

**Comment by stwiname** [comment]
I cant seem to reproduce this.

**Comment by ianhe8x** [comment]
I couldn't reproduce it either. Probably some edge cases that the node will run into this.
