### ISSUE TITLE
Resolve some Critical Dependencies

### ISSUE THREAD

**Issue by jamesbayly** [subquery/subql#1816]
### Prerequisites

* [x] Are you running the latest version(s)?

### Description

`yarn audit` on Algorand Starter

### Details

See attached file

```
31 vulnerabilities found - Packages audited: 924
Severity: 6 Moderate | 8 High | 17 Critical
✨  Done in 1.03s.
```

**Comment by jamesbayly** [comment]
[audit.txt](https://github.com/subquery/subql/files/11810799/audit.txt)

**Comment by stwiname** [comment]
https://github.com/subquery/subql/security you can see the report here.

I've turned on Dependabot security updates so it should make PRs updating deps automatically

**Comment by stwiname** [comment]
Im going to consider this done. We have dependabot setup on all SDKs now and the main repo is down to 5 alerts with others less than that
