### ISSUE TITLE
improve get latest mmr Poi query

### ISSUE THREAD

**Issue by jiqiang90** [subquery/subql#1840]
### Prerequisites

* [ ] Are you running the latest version(s)?
* [ ] Have you searched the [documentation for your issue](https://academy.subquery.network/)?
* [ ] Did you search for an existing issue or pull request?

### Description
SQL we used to get last poi with mmr value seems take very long to query, and blocking other process.

```

SELECT id, "chainBlockHash", hash, "parentHash", "operationHashRoot", "mmrRoot", "projectId", "createdAt", "updatedAt" FROM "avalanche-dictionary"._poi AS _poi 
WHERE _poi."mmrRoot" is not null
ORDER BY _poi.id desc
LIMIT 1;

```

To resolve this, we can store this block height inside of metadata, it will be easy to get this value from table by height

### Details

These details can help to reproduce the environment the issue is occurring

**Local Environment:** [You can get this information from executing `subql version`.]
**Query Version:** [What is the version of the query service?]
**Indexer Version:** [What is the version of the indexer service?]
**Network Details:**
  * [Network]
  * [Block height, a block height where the issue is happening]
  * [Dictionary endpoint, if used]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Example project:** [A link to a minimal example that can reproduce the issue]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Any other information

Is there any other information you would like to add?

**Comment by stwiname** [comment]
Would we be better off adding an index or something else? The MMR process runs similar queries to fill in `mmrRoot`

**Comment by jiqiang90** [comment]
> Would we be better off adding an index or something else? The MMR process runs similar queries to fill in `mmrRoot`

good idea
