### ISSUE TITLE
Testing framework: should be able to accept `undefined` as an expect value

### ISSUE THREAD

**Issue by bz888** [subquery/subql#1845]
### Description

When running `subqlTest` with an expected entity that contains an optional field (e.g. `string|undefined`) 

```
ExampleEntity.create({
id: 'id',
name: undefined
})
```

This will fail the test as it expects `null` rather than undefined. we should align the value with the `codegen` schema.

[Description of the bug or feature]

### Details

These details can help to reproduce the environment the issue is occurring

**Local Environment:** [You can get this information from executing `subql version`.]
**Query Version:** [What is the version of the query service?]
**Indexer Version:** [What is the version of the indexer service?]
**Network Details:**
  * [Network]
  * [Block height, a block height where the issue is happening]
  * [Dictionary endpoint, if used]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Example project:** [A link to a minimal example that can reproduce the issue]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Any other information

Is there any other information you would like to add?

**Comment by stwiname** [comment]
Fixed in https://github.com/subquery/subql/pull/1809/
