### ISSUE TITLE
Data race in event indexing project

### ISSUE THREAD

**Issue by vovunku** [subquery/subql#1846]
### Prerequisites

* [x] Are you running the latest version(s)?
* [x] Have you searched the [documentation for your issue](https://academy.subquery.network/)?
* [x] Did you search for an existing issue or pull request?

### Description

When processing events that are in close blocks, a data race occurs. In particular, [handleReward](https://github.com/novasamatech/subquery-staking/blob/2a23c896ca0eb0e3c67ba4714fa6dfbe9de33c5d/src/mappings/rewards/history/common.ts#L17) is executed for block 10628991, but it is not stored in the database, but in the cache (apparently). Therefore, when processing block 10628993, the handleReward is also called, but it does not see the changes for block 10628991 (specifically the [AccumulatedReward](https://github.com/novasamatech/subquery-staking/blob/2a23c896ca0eb0e3c67ba4714fa6dfbe9de33c5d/src/mappings/rewards/history/common.ts#L38) field).

### Details

**Local Environment:** @subql/cli/3.1.1 linux-x64 node-v18.16.0
**Query Version:** image: onfinality/subql-query:latest
**Indexer Version:** image: onfinality/subql-node:latest
**Network Details:**
  * polkadot
  * 10603267 (more precisely 10628991 and 10628993)
  * https://api.subquery.network/sq/subquery/polkadot-dictionary

### Steps to Reproduce

```bash
git clone git@github.com:novasamatech/subquery-staking.git
git checkout feature/reward_data_race
yarn
yarn codegen
yarn build
yarn start:docker
```

Now we connect http://localhost:3000/ and wait a several minutes. Next we use query

```
query {
  rewards(first: 10, filter: {address : {equalTo: "1ChFWeNRLarAPRCTM3bfJmncJbSAbSS9yqjueWz7jX7iTVZ"}}) {
    nodes {
      id,
      amount,
      accumulatedAmount,
    }
  }
}
```

**Example project:** https://github.com/novasamatech/subquery-staking/tree/feature/reward_data_race

**Expected behavior:** To accumulate reward like this

![Screenshot from 2023-06-23 13-59-26](https://github.com/subquery/subql/assets/33938211/eb89b43a-fa42-46fe-a7e0-80dcb3b77bcc)

**Actual behavior:** Actually we miss reward for 10628991 block in accumulated reward(as we use previous block that is 10603267). 

![Screenshot from 2023-06-23 13-57-04](https://github.com/subquery/subql/assets/33938211/9dafe865-6cf4-44d1-8ba8-8b6cae016155)

### Any other information

It should also be noted that if you **uncomment the store flags (i.e. disable the cache), the problem disappears**. 
https://github.com/novasamatech/subquery-staking/blob/2a23c896ca0eb0e3c67ba4714fa6dfbe9de33c5d/docker-compose.yml#L41

I was also able to see one of the rewards without the other in the query. It's as if subquery works correctly with the cache.

Nothing interesting in logs

[with_bug.log](https://github.com/subquery/subql/files/11848653/with_bug.log)

[store_fix.log](https://github.com/subquery/subql/files/11848654/store_fix.log)

If you start from 10628991 the behavior will be the same.

Probably it is not a problem multichain flag, because without it there is still a problem

**Comment by jiqiang90** [comment]
This can be reproduced with historical disabled, I found it seems depend on when flush is triggered. 

We have 3 cached records create at block 10603267, 10628891, 10628893  in the example. 

- The `accumulatedAmount ` is corrected when no flush between 10628891 and 10628893, the value is sum of all 3 rewards.

I suspect the `accumulatedAmount ` could be incorrect when flush happened between 10628891 and 10628893, while `accumulatedAmount` get nothing from cache and directly read from db.
