### ISSUE TITLE
Accelerate indexing via blocks/events cache

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#186]
Need to look into https://github.com/paritytech/substrate-archive first

**Comment by jiqiang90** [comment]
Phases:

- [ ] Use event/call map to accelerate the indexing speed
- [ ] Use specVersion map to improve fetch runtime version range
- [ ] Re-design project configurations and manifest to support multiple dictionary(maps) for different spec networks

**Comment by jiqiang90** [comment]
if map query return batch size is 0 (no block height is returned), we need to find a way to update lastProcessedHeight

**Comment by jiqiang90** [comment]
We have take the dictionary approach, we can close this now
