### ISSUE TITLE
`totalCount` graphql timeout

### ISSUE THREAD

**Issue by bz888** [subquery/subql#1864]
### Description

running query service: `v2.3.0`

Larger `totalCount` timeout on graphql client
Despite no issues executing the SQL(using `query-explain`) directly through the database, especially a query that is far from the timeout limit.

e.g. 
Query execution on postgresDB 200ms
Query timeout limit on graphql client 10_000ms 

still resulting to timeout on client side.

**Comment by stwiname** [comment]
Not enough details and no clear way to reproduce this.
