### ISSUE TITLE
atob is not defined error

### ISSUE THREAD

**Issue by youssefea** [subquery/subql#1866]
I keep getting this error whenever I work on a EVM-chain indexer:

`base-goerli-starter-subquery-node-1   | 2023-07-04T14:40:47.789Z <BlockDispatcherService> ERROR failed to index block at height 6642547 handleDrip(ReferenceError: atob is not defined
base-goerli-starter-subquery-node-1   |     at Lo (webpack://base-subql-starter/node_modules/@ethersproject/base64/lib.esm/base64.js:4:4)
base-goerli-starter-subquery-node-1   |     at 903 (webpack://base-subql-starter/node_modules/@ethersproject/hash/lib.esm/ens-normalize/include.js:32:35)
base-goerli-starter-subquery-node-1   |     at r (webpack://base-subql-starter/webpack/bootstrap:19:31)
base-goerli-starter-subquery-node-1   |     at 575 (webpack://base-subql-starter/src/mappings/mappingHandlers.ts:7:17)
base-goerli-starter-subquery-node-1   |     at r (webpack://base-subql-starter/webpack/bootstrap:19:31)
base-goerli-starter-subquery-node-1   |     at 341 (webpack://base-subql-starter/src/index.ts:5:26)
base-goerli-starter-subquery-node-1   |     at r (webpack://base-subql-starter/webpack/bootstrap:19:31)
base-goerli-starter-subquery-node-1   |     at webpack://base-subql-starter/webpack/startup:4:26
base-goerli-starter-subquery-node-1   |     at null:null:null
base-goerli-starter-subquery-node-1   |     at VM2 Wrapper.apply (/usr/local/lib/node_modules/@subql/node-ethereum/node_modules/vm2/lib/bridge.js:485:11)) ReferenceError: atob is not defined
base-goerli-starter-subquery-node-1   |
base-goerli-starter-subquery-node-1   | node:internal/process/promises:288
base-goerli-starter-subquery-node-1   |             triggerUncaughtException(err, true /* fromPromise */);
base-goerli-starter-subquery-node-1   |             ^
base-goerli-starter-subquery-node-1   | ReferenceError [Error]: atob is not defined
base-goerli-starter-subquery-node-1   |     at Lo (webpack://base-subql-starter/node_modules/@ethersproject/base64/lib.esm/base64.js:4:4)
base-goerli-starter-subquery-node-1   |     at 903 (webpack://base-subql-starter/node_modules/@ethersproject/hash/lib.esm/ens-normalize/include.js:32:35)
base-goerli-starter-subquery-node-1   |     at r (webpack://base-subql-starter/webpack/bootstrap:19:31)
base-goerli-starter-subquery-node-1   |     at 575 (webpack://base-subql-starter/src/mappings/mappingHandlers.ts:7:17)
base-goerli-starter-subquery-node-1   |     at r (webpack://base-subql-starter/webpack/bootstrap:19:31)
base-goerli-starter-subquery-node-1   |     at 341 (webpack://base-subql-starter/src/index.ts:5:26)
base-goerli-starter-subquery-node-1   |     at r (webpack://base-subql-starter/webpack/bootstrap:19:31)
base-goerli-starter-subquery-node-1   |     at webpack://base-subql-starter/webpack/startup:4:26
base-goerli-starter-subquery-node-1   |     at null:null:null
base-goerli-starter-subquery-node-1   |     at VM2 Wrapper.apply (/usr/local/lib/node_modules/@subql/node-ethereum/node_modules/vm2/lib/bridge.js:485:11) {
base-goerli-starter-subquery-node-1   |   handler: 'handleDrip'
base-goerli-starter-subquery-node-1   | }
base-goerli-starter-subquery-node-1   |
base-goerli-starter-subquery-node-1   | Node.js v18.16.1 `

I get to solve it if I add this to mappingHandlers.ts:
`global.atob = require("atob");
global.Blob = require('node-blob'); `

However, this is not an ideal solution.

**Comment by jiqiang90** [comment]
Duplicate with https://github.com/subquery/subql/issues/1277, we can close this
