### ISSUE TITLE
[ethereum] event.transaction.gas doesn't match its typing (bigint)

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#1880]
### Description

My mapping function saves event.transaction.gas to db, and it failed with the error
```
original: error: invalid input syntax for type numeric: "00x13263"
```

With some debug i confirmed that some fields of event.transaction don't match their ts typing.

To be specific, they are `blockNumber`, `gas`, `gasPrice`, `maxPriorityFeePerGas`, `maxFeePerGas`,`nonce`,`transactionIndex`, `value`, `v`

### Details

**Indexer Version:** @subql/node-ethereum: v2.9.1

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Example project:** [A link to a minimal example that can reproduce the issue]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Any other information

Is there any other information you would like to add?

**Comment by jiqiang90** [comment]
Fixed in https://github.com/subquery/subql-ethereum/pull/128
