### ISSUE TITLE
Identify and show the bottleneck of a deployment

### ISSUE THREAD

**Issue by jiqiang90** [subquery/subql#1881]
### Prerequisites

* [ ] Are you running the latest version(s)?
* [ ] Have you searched the [documentation for your issue](https://academy.subquery.network/)?
* [ ] Did you search for an existing issue or pull request?

### Description

Different than a benchmarking, in order to improve overall speed for a project deployment, we need to identify where the bottleneck are. There are 3 key infomations:

- fetching speed, by look at block number queue 
- processing speed, by look at processing queue, might provide useful detail from --profiler
- writing speed, we might check the flushing duration and num of blocks data been flushed (or any better metric)

Then we can give suggestion to improve deployments, also good to visualize these in some way (host service or network)

### Details

These details can help to reproduce the environment the issue is occurring

**Local Environment:** [You can get this information from executing `subql version`.]
**Query Version:** [What is the version of the query service?]
**Indexer Version:** [What is the version of the indexer service?]
**Network Details:**
  * [Network]
  * [Block height, a block height where the issue is happening]
  * [Dictionary endpoint, if used]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Example project:** [A link to a minimal example that can reproduce the issue]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Any other information

Is there any other information you would like to add?

**Comment by stwiname** [comment]
I think this can be considered done with https://github.com/subquery/subql/blob/main/packages/node-core/src/indexer/blockDispatcher/block-dispatcher.ts#L114

The queue with the lowest free space is the bottle neck. This will either be from fetching or processing.
