### ISSUE TITLE
Provide an option to skip fetch block & extrinsics for event handler

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#1889]
### Description

For `substrate/EventHandler` & `ethereum/LogHandler`, we always fetch the corresponding block and transaction, so we can offer access from the wrapped event object.
What if user has no use of things like `event.block`, `event.extrinsic` or `event.transaction`, can we only fetch header without the full detailed blocks and transactions?

### Details
* Add a new runner option for node, `skipBlock(default: false)`
    * when enabled, if project only contains `substrate/EventHandler` or `ethereum/LogHandler`, then node will not fetch block. 
    * for substrate project, extrinsics will not be fetched as well, since extrinsics are embedded in the block.
* Add a new runner option for node, `skipTransaction(default: false)`
    * when enabled, if project only contains `ethereum/LogHandler`, then node will not fetch transactions.
    * enable `skipTransaction` implies `skipBlock`, `skipBlock is set to false` will cause a conflict and should leads to exit(1)
* when project has other type of handlers that don't work with skipBlock or skipTransaction, but user set them true. the node will print a warning to console to tell user that these two options will be ignored.

These details can help to reproduce the environment the issue is occurring

**Local Environment:** [You can get this information from executing `subql version`.]
**Query Version:** [What is the version of the query service?]
**Indexer Version:** [What is the version of the indexer service?]
**Network Details:**
  * [Network]
  * [Block height, a block height where the issue is happening]
  * [Dictionary endpoint, if used]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Example project:** [A link to a minimal example that can reproduce the issue]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Any other information

Is there any other information you would like to add?

**Comment by stwiname** [comment]
Im going to close this. We have a minimal implementation for Substrate and Ethereum, there can be further improvements with Ethereum and other SKDs but that will have another ticket for them
