### ISSUE TITLE
Rework proof of index

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#1905]
### Description
Currently we offer two levels of cryptographic proof for index, 
1. `hash` in the poi table, which is `HashFn(height,chainBlockHash,parentHash,operationHash,projectId)`
    1. poi table is not continuous (only when there is operation in the block)
    2. parentHash is the hash of last block with operation
    3. if a block is skipped, we use a fixed hash for that block
2. We also build a mmr and calculate the root hash, because this proof is continuous we use if for the final proof

Theoretical, hash is enough to tell if two indexers are generating same data (because parenthash is included in the digest)
the only problem for it is not continuous.
So we can actually simplify poi by removing mmr and only use the hash, as long as we can solve the only blocking issue.

### Details
1. Make data in _poi table continuous
    1. We can keep the current place we insert poi record with block of operations, but we should leave `hash` empty
    2. Change where we used to insert mmr table to insert poi table, fill in empty blocks in the table. This step we can generate `hash` for records inserted in step 1
    3. For skipped blocks, we use empty hash for chainblockHash and operationHash, but the parentHash is no more the last block with operation, we use its parent block literally.
2. further tidy up _poi table, deprecating parentHash column since it is redundant data and now can be easily found by id.
3. change api, add `/poi/` and deprecate `/mmrs/`, change response body.

**Local Environment:** [You can get this information from executing `subql version`.]
**Query Version:** [What is the version of the query service?]
**Indexer Version:** [What is the version of the indexer service?]
**Network Details:**
  * [Network]
  * [Block height, a block height where the issue is happening]
  * [Dictionary endpoint, if used]

### Steps to Reproduce

1. [First Step]
5. [Second Step]
6. [and so on...]

**Example project:** [A link to a minimal example that can reproduce the issue]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Any other information

Is there any other information you would like to add?

**Comment by jiqiang90** [comment]
Because we will rework on POI, this bug here we can close it https://github.com/subquery/subql/issues/1902
