### ISSUE TITLE
Unable to scaffold a project using subql cli

### ISSUE THREAD

**Issue by saadjhk** [subquery/subql#1920]
### Prerequisites

* [X] Are you running the latest version(s)?
* [X] Have you searched the [documentation for your issue](https://academy.subquery.network/)?
* [X] Did you search for an existing issue or pull request?

### Description

Unable to scaffold project using cli `init` command.

### Details

Unable to scaffold a project using subql cli. Fails the error
```
Error: ENOENT: no such file or directory, stat '/tmp/5KdOCO/Arbitrum 
    One/arbitrum-one-starter'
    Code: ENOENT
```

**Local Environment:** Node JS LTS Gallium

### Steps to Reproduce

1. `npm install -g @subql/cli`
2. `subql init`

**Comment by stwiname** [comment]
@saadjhk thanks for your report. What OS are you using?

**Comment by saadjhk** [comment]
Ubuntu 23.04
