### ISSUE TITLE
Introduce primary network endpoint

### ISSUE THREAD

**Issue by stwiname** [subquery/subql#1924]
Users have requested being able to specify a primary end point that is always used unless there are issues with that endpoint. 

We can introduce a new flag `--primary-network-endpoint` to achieve this. 

![image (7)](https://github.com/subquery/subql/assets/3432810/81a8b666-b184-45dc-af19-4f83cf817333)

**Comment by ianhe8x** [comment]
We can also introduce a flag `network-endpoint-strategy`, default: `auto`, which is current behaviour.
if set to `prioritized` , always use first endpoint if possible.

**Comment by stwiname** [comment]
This is a short term solution until we can introduce https://github.com/subquery/subql/issues/1925
