### ISSUE TITLE
Upgrade the IPFS client library

### ISSUE THREAD

**Issue by stwiname** [subquery/subql#1928]
The IPFS client library has been deprecated and we should switch to Helia as the replacement. 

This should clean up most of the deprecated warnings. It would be great to see if we can also fix the other deprecated warnings at the same time

![telegram-cloud-document-4-5945158185697414568](https://github.com/subquery/subql/assets/3432810/49d14a46-0768-4685-962e-682840adf1f6)

**Comment by DeveloperInProgress** [comment]
https://github.com/ipfs/helia/issues/153#issuecomment-1603458487

looks like we need to be using [`kubo-rpc-client`](https://github.com/ipfs/js-kubo-rpc-client) as replacement for ipfs-http-client. But it is still a work in progress.

https://github.com/ipfs/js-kubo-rpc-client#work-in-progress
