### ISSUE TITLE
Support TS based project schemas

### ISSUE THREAD

**Issue by stwiname** [subquery/subql#1938]
### Description
As the project manifest gets more complex its harder to know what options are needed.

Users could define their project manifests in typescript files with typescript types and rely on IDE support for typescript
An article explaining another projects decisions: https://stellate.co/blog/moving-from-yaml-to-typescript

### Advantages
* Probably more flexible/powerful type/schema control than JSON-Schema

### Disadvantages
* Tied to SDK support and compatibility
* Possible security issues with loading untrusted code and leaking sensitive data

## Requirements

* Create a `types-core` package to pull interfaces/types from common. As well as the store interface. types-* will use this as a dependency
* Add JSDOC descriptions and examples to fields
* Update publish command to transform TS to yaml deployment
* Update loading to support TS manifests

**Comment by jamesbayly** [comment]
I'm okay with renaming the schema

**Comment by ianhe8x** [comment]
I will choose Typescript, security isn't an issue because we load the typescript formed manifest in local development only.
Once get distributed, it will still be converted to yaml. It should not be seen as tied to a particular language since we still support yaml/json as manifest.

**Comment by jamesbayly** [comment]
@jiqiang90 I can help write the descriptions for all the types etc
So maybe put a placeholder in there and i can update when it's in review
