### ISSUE TITLE
Fix Update Indexing Workflow on Dashboard

### ISSUE THREAD

**Issue by joesixpack** [subquery/subql#1946]
Currently, when syncing or before announcing ready, a project must be first be stopped for the "Update Indexing" button to become visible in the dashboard.  This is different from post-sync/post-ready behavior and makes it difficult to see the project configuration settings without affecting the sync and/or availability.

**Comment by mzxyz** [comment]
Hi @joesixpack thanks for reporting this issue, seems this one is related with the Kepler network other than SDK special, we would recommend you create a topic in the [forum](https://forum.subquery.network/c/kepler-network/16) to report this issue, thanks.
