### ISSUE TITLE
Allow Customers to set Initial Store State on Project Genesis

### ISSUE THREAD

**Issue by jiqiang90** [subquery/subql#1962]
### Why

Customers want to be able to insert 'genesis data' into their SubQuery project. This could include seed data or constants that they want to reference.
 
### Description

Create some kind of Genesis handler that is always run when a project starts for the first time on a fresh database.
- Create genesis data in Subquery projects.
- Get called before all other handlers
- Only called once , in metadata we could record if it been called once, it should never call again. 
- Should have access to all standard store queries

**Comment by jamesbayly** [comment]
Via https://github.com/subquery/subql/pull/1987

**Comment by stwiname** [comment]
This can be achieved by having a startBlock equal to the endBlock with [this feature](https://github.com/subquery/subql/pull/2064)

**Comment by jamesbayly** [comment]
Correct, if you have the following it will index just one block (block 1) for that set of mapping functions (remember you can have multiple of these)

```
startBlock: 1,
endBlock: 1,
```

Take a read of this https://academy.subquery.network/indexer/miscellaneous/faq.html#inserting-seed-data-at-project-initiation
