### ISSUE TITLE
Skip dictionary when difference between lastProcessedHeight and latestHeight is small

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#1963]
### Prerequisites

* [ ] Are you running the latest version(s)?
* [ ] Have you searched the [documentation for your issue](https://academy.subquery.network/)?
* [ ] Did you search for an existing issue or pull request?

### Description
We want to reduce unnecessary dict queries

### Details

Skip dictionary when difference between lastProcessedHeight and latestHeight is small. (mandatory value or use batch size)

**Local Environment:** [You can get this information from executing `subql version`.]
**Query Version:** [What is the version of the query service?]
**Indexer Version:** [What is the version of the indexer service?]
**Network Details:**
  * [Network]
  * [Block height, a block height where the issue is happening]
  * [Dictionary endpoint, if used]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Example project:** [A link to a minimal example that can reproduce the issue]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Any other information

Is there any other information you would like to add?

**Comment by stwiname** [comment]
This has been updated to match the last block, but we can be even looser and stop using the dictionary if its within a certain number of blocks
