### ISSUE TITLE
Error: Publish project to default cluster failed, AxiosError: maxContentLength size of 52428800 exceeded

### ISSUE THREAD

**Issue by icezohu** [subquery/subql#1964]
### Prerequisites

* [ ] Are you running the latest version(s)? `v3.5.1`
* [ ] Have you searched the [documentation for your issue](https://academy.subquery.network/)?
* [ ] Did you search for an existing issue or pull request?

### Description

Error happens when `subql publish` [network subql project](https://github.com/subquery/subquery-network-subql-project/tree/SQN-1721).

### Details

These details can help to reproduce the environment the issue is occurring

**Local Environment:** @subql/cli/3.5.1 darwin-arm64 node-v16.20.0
**Query Version:** [What is the version of the query service?]
**Indexer Version:** [What is the version of the indexer service?]
**Network Details:**
  * [Network]
  * [Block height, a block height where the issue is happening]
  * [Dictionary endpoint, if used]

### Steps to Reproduce

1. run `yarn deploy:kepler` or `subql publish -f ./project-kepler.yaml` in [network subql project](https://github.com/subquery/subquery-network-subql-project/tree/SQN-1721)

**Example project:** [A link to a minimal example that can reproduce the issue]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Any other information

Is there any other information you would like to add?

**Comment by stwiname** [comment]
This should now be fixed since v3.6.1
