### ISSUE TITLE
Support `--block-confirmations` in project manifest as runner option

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#1974]
### Prerequisites

* [ ] Are you running the latest version(s)?
* [ ] Have you searched the [documentation for your issue](https://academy.subquery.network/)?
* [ ] Did you search for an existing issue or pull request?

### Description

We have dictionary projects that run against high throughput chains. the default 20 confirmation blocks sometime is not big enough to avoid block forks.
By adding it to runner option, we can adjust it for different chains.

### Details

These details can help to reproduce the environment the issue is occurring

**Local Environment:** [You can get this information from executing `subql version`.]
**Query Version:** [What is the version of the query service?]
**Indexer Version:** [What is the version of the indexer service?]
**Network Details:**
  * [Network]
  * [Block height, a block height where the issue is happening]
  * [Dictionary endpoint, if used]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Example project:** [A link to a minimal example that can reproduce the issue]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Any other information

Is there any other information you would like to add?

**Comment by stwiname** [comment]
Would it make more sense for this to be under the network settings?

**Comment by stwiname** [comment]
This should already be possible
