### ISSUE TITLE
npm install -g @subql/cli subql/types-flare@2.2.4.

### ISSUE THREAD

**Issue by stallonepeck** [subquery/subql#1988]
While trying to install @subql/cli globally using npm, I encountered an error indicating that a specific version (2.2.4) of the dependency @subql/types-flare could not be found on the npm registry.

Steps to Reproduce
Run the command npm install -g @subql/cli.
Observe the error message related to @subql/types-flare@2.2.4.
Expected behavior:

I expected @subql/cli to be installed globally without any issues.
Actual behavior:

I received an error indicating that version 2.2.4 of @subql/types-flare could not be found.
Any other information
The error message was:

sql
Copy code
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @subql/types-flare@2.2.4.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
I would appreciate any guidance on resolving this issue and successfully installing @subql/cli.

**Comment by bz888** [comment]
I haven't been able to replicate this, are you able to provide more details ? e.g. node version, os, enviornment

**Comment by stallonepeck** [comment]
sorry i think i will close this it might this be my pc pnpm worked but here are my specs
node -v  : v20.5.1
npm -v : 10.0.0
os : pop os

**Comment by bz888** [comment]
this PR should resolve errors like such in the future
https://github.com/subquery/subql/pull/1992
