### ISSUE TITLE
randomly get empty _block_range on table that we do delete operation

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#1995]
### Prerequisites

* [ ] Are you running the latest version(s)?
* [ ] Have you searched the [documentation for your issue](https://academy.subquery.network/)?
* [ ] Did you search for an existing issue or pull request?

### Description

[Description of the bug or feature]

### Details

These details can help to reproduce the environment the issue is occurring

**Local Environment:** [You can get this information from executing `subql version`.]
**Query Version:** [What is the version of the query service?]
**Indexer Version:** [What is the version of the indexer service?]
**Network Details:**
  * [Network]
  * [Block height, a block height where the issue is happening]
  * [Dictionary endpoint, if used]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Example project:** [A link to a minimal example that can reproduce the issue]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Any other information

Is there any other information you would like to add?

**Comment by jiqiang90** [comment]
![image](https://github.com/subquery/subql/assets/10431657/f5a0123c-b97a-44d4-9370-3b2df8406e1a)
To reproduce this, use polkadot-starter project, add this in the handler

```
await Transfer.remove(transfer.id);
```

it will remove the data within same block height
