### ISSUE TITLE
Integration with Filecoin EVM Fails Due to 'Could not detect network' Error

### ISSUE THREAD

**Issue by youssefea** [subquery/subql#2016]
**Issue Description:**
When trying to integrate Filecoin EVM with SubQuery, the initialization process fails, raising an error related to "Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)".

**Log Output:**
`filecoin-evm-starter-postgres-1        | 2023-09-12 15:12:59.023 UTC [1] LOG:  starting PostgreSQL 12.16 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
filecoin-evm-starter-postgres-1        | 2023-09-12 15:12:59.023 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432  
filecoin-evm-starter-postgres-1        | 2023-09-12 15:12:59.023 UTC [1] LOG:  listening on IPv6 address "::", port 5432       
filecoin-evm-starter-postgres-1        | 2023-09-12 15:12:59.027 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
filecoin-evm-starter-postgres-1        | 2023-09-12 15:12:59.059 UTC [62] LOG:  database system was shut down at 2023-09-12 15:12:58 UTC
filecoin-evm-starter-postgres-1        | 2023-09-12 15:12:59.082 UTC [1] LOG:  database system is ready to accept connections
filecoin-evm-starter-subquery-node-1   | 2023-09-12T15:13:03.163Z <subql-node> INFO Current @subql/node-ethereum version is 2.12.5
filecoin-evm-starter-subquery-node-1   | 2023-09-12T15:13:03.164Z <subql-node> INFO Current @subql/node-ethereum version is 2.12.5
filecoin-evm-starter-subquery-node-1   | 2023-09-12T15:13:03.358Z <api.ethereum> INFO Api host: api.node.glif.io, method: https

filecoin-evm-starter-subquery-node-1   | 2023-09-12T15:13:03.385Z <db> WARN Database does not support SSL connection, will try to connect without it
filecoin-evm-starter-subquery-node-1   | 2023-09-12T15:13:05.497Z <api> ERROR Failed to init api service Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
filecoin-evm-starter-subquery-node-1 exited with code 0
filecoin-evm-starter-subquery-node-1   | 2023-09-12T15:13:08.007Z <subql-node> INFO Current @subql/node-ethereum version is 2.12.5
filecoin-evm-starter-subquery-node-1   | 2023-09-12T15:13:08.008Z <subql-node> INFO Current @subql/node-ethereum version is 2.12.5
filecoin-evm-starter-subquery-node-1   | 2023-09-12T15:13:08.200Z <api.ethereum> INFO Api host: api.node.glif.io, method: https

filecoin-evm-starter-subquery-node-1   | 2023-09-12T15:13:08.251Z <db> WARN Database does not support SSL connection, will try to connect without it
filecoin-evm-starter-subquery-node-1   | 2023-09-12T15:13:11.288Z <api> ERROR Failed to init api service Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
dependency failed to start: container filecoin-evm-starter-subquery-node-1 is unhealthy`

**Steps to Reproduce:**

- Set up a SubQuery EVM Project.
- Add details from [Filecoin EVM](https://chainlist.org/chain/314) chain and this [WFIL token](https://filfox.info/en/address/f410f3gtsjbakiy3qyanfbqpfceehvm5ap62tvtf44oq) to index transfers and approvals.
- Run yarn dev.
- This branch has a project on it already: [Filecoin branch](https://github.com/subquery/ethereum-subql-starter/tree/filecoin-starter)

**Suggested Solutions:**
Investigate the cause of the error if it comes from the SubQuery SDK.
Close this issue if you believe the problem comes from RPC endpoint.

**Comment by stwiname** [comment]
Closing this as Filecoin and FIlecoin EVM is not supported
