### ISSUE TITLE
Rework scaffold `codegen:generate` for ts-manifest

### ISSUE THREAD

**Issue by bz888** [subquery/subql#2098]
### Prerequisites

* [x] Are you running the latest version(s)?
* [x] Have you searched the [documentation for your issue](https://academy.subquery.network/)?
* [x] Did you search for an existing issue or pull request?

### Description

With the introduction of ts-manifest, the `generate` command is no longer working. Hence a new work around is needed for the scaffold generate command is needed to accommodate for ts-manifest

### Details

These details can help to reproduce the environment the issue is occurring

**Local Environment:** [You can get this information from executing `subql version`.]
**Query Version:** [What is the version of the query service?]
**Indexer Version:** [What is the version of the indexer service?]
**Network Details:**
  * [Network]
  * [Block height, a block height where the issue is happening]
  * [Dictionary endpoint, if used]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Example project:** [A link to a minimal example that can reproduce the issue]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Any other information

Is there any other information you would like to add?

**Comment by jamesbayly** [comment]
Just use regex that finds `handlers:\s*\[`,  and append to that array. If it does not find that, then throw and error and print what the ts object should be in the cli console
