### ISSUE TITLE
Query service de-duplicate fields

### ISSUE THREAD

**Issue by stwiname** [subquery/subql#2126]
Its possible to make queries which repeat fields this can lead to slow queries. 

example:
```gql 
{
  entity {
    field1
    field2
    field1
    field2
    field1
    field2
    ...repeats many times
  }
}
```

**Comment by bz888** [comment]
There are no differences in the SQL or the SQL fragment build time. But having duplication does overall increase the query complexity. I don't think this should be the case, and the query complexity plugin should be able to handle this better.
