### ISSUE TITLE
[$250 in SQT] Store orderBy 

### ISSUE THREAD

**Issue by stwiname** [subquery/subql#2140]
## Description

The store `getBy` methods don't currently support specifying the order and will always use ASC order. 

We should add to the options for these methods to specify the order `"ASC" | "DESC"`. It should be optional and retain the default order to not be a breaking change.

### Other requirements
- [Documentation](https://github.com/subquery/documentation) should be updated to include the feature
- Changes should have test coverage of 80% on the relevant code.

**Comment by stwiname** [comment]
@Sanyam-jain30 feel free to start this and make a PR when ready.

**Comment by Sanyam-jain30** [comment]
@stwiname can we run the code in Windows?

**Comment by stwiname** [comment]
It should run on Windows, although we don't regularly develop on windows

**Comment by Sanyam-jain30** [comment]
I am unable to set it up on windows, @stwiname can you please assign it to somebody with a Mac, sorry for the inconvenience.

**Comment by singulart** [comment]
Hey @stwiname I am ready to pick this up!
