### ISSUE TITLE
[$200 in SQT] Improve error handling on Codegen for schema entities

### ISSUE THREAD

**Issue by bz888** [subquery/subql#2211]
### Description
If an entity has a lowercase name it can result in invalid generated gode

```
// graphql.schema
type exampleField @entity {
 id: ID!
}
```
This will generate a fie `ExampleField.ts` However, the index.ts codegen will import `exampleField.ts`

The generated `index.ts` should have the correct case sensitive import

**Comment by Faizalhidayat** [comment]
try this 

// Assuming `entities` is an array of your entity names
const importStatements = entities.map((entity) => {
  const normalizedName = normalizeEntityName(entity);
  return `import { ${normalizedName} } from './${normalizedName}.ts';`;
}).join('\n');

**Comment by stwiname** [comment]
@Faizalhidayat did you want to make a PR with your suggested changes?

**Comment by Faizalhidayat** [comment]
my suggest wrong ?

**Comment by stwiname** [comment]
@Faizalhidayat We're not after suggestions and pseudo code. We want pull requests that fix the issue
