### ISSUE TITLE
[$1000 in SQT] Support env file & env commend.

### ISSUE THREAD

**Issue by HuberTRoy** [subquery/subql#2217]
### Description

When I develop a project, I want to test on `Polygon` & `Mumbai`. I created two config file `project.ts` & `project.mainnet.ts`. Those two files only have some fields different. So support env file would be good in project.

I use [dotenv](https://github.com/motdotla/dotenv) locally for this feature. If subql can supply an out of box way may good to use.

### Expected

The files looks like this:

```
-.env
-.env.local # git ignore it, override the fields 
-.env.develop
-.env.develop.local # git ignore it
project.ts
```

In `project.ts`, I can use it for different data:

```ts
const project: EthereumProject = {
   .....
  network: {
    chainId: process.env.chainId,
    endpoint: [process.env.endpoint],
  },
```

In package.json:

```json
    "build": "subql codegen && subql build", // default is production
    "build:develop": "subql codegen --mode develop && subql build --mode develop",
```

### Other requirements
- [Documentation](https://github.com/subquery/documentation) should be updated to include the feature
- Changes should have test coverage of 80% on the relevant code.

**Comment by jamesbayly** [comment]
You are welcome to take it on and leave any questions here. I'll assign it to you for the next two weeks

**Comment by hitesh23k** [comment]
Hi @jamesbayly , the task is currently in progress. Could I please request a one-week extension for this?

**Comment by jamesbayly** [comment]
> Hi @jamesbayly , the task is currently in progress. Could I please request a one-week extension for this?

Are you able to share an in progress PR branch?

**Comment by asifalisaifi81** [comment]
What is that

*Thanks & Regards
Asif ali
Motivate
Singage/Display,Branding/Exhibition
H-78/20, 1st floor leftside
batla house jamia nagar
Okhla New Delhi - 110025
https://motivate-advertising-agency.business.site/
+919540042745*

**Comment by AK46rocks** [comment]
Hi, @jamesbayly 
@hitesh23k Hitesh was unavailable, therefore he instructed me to submit the pull request.
This the PR for Support env and env commands
https://github.com/subquery/subql/pull/2345
