### ISSUE TITLE
Unable to generate types for overloaded Solidity functions

### ISSUE THREAD

**Issue by livthomas** [subquery/subql#2231]
### Prerequisites

* [x] Are you running the latest version(s)?
* [x] Have you searched the [documentation for your issue](https://academy.subquery.network/)?
* [x] Did you search for an existing issue or pull request?

### Description

When I try to use [BLSRegistryCoordinatorWithIndices.sol](https://github.com/Layr-Labs/eigenlayer-middleware/blob/v0.1.0-m2-goerli/src/BLSRegistryCoordinatorWithIndices.sol) contract in my project, SubQuery fails to generate `deregisterOperatorWithCoordinator` and `registerOperatorWithCoordinator` functions which are both overloaded. Once I remove them from the ABI JSON, the build starts to work.

### Details

**Local Environment:** `@subql/cli/4.2.5 darwin-arm64 node-v18.18.2`
**Network Details:** Ethereum Goerli testnet

### Steps to Reproduce

1. Create a new project using [ethereum-goerli-starter](https://github.com/subquery/ethereum-subql-starter/tree/main/Ethereum/ethereum-goerli-starter) template.
2. Copy JSON ABI of [BLSRegistryCoordinatorWithIndices](https://goerli.etherscan.io/address/0x9A70ED111FaFEC41856202536AFAA38841a9a0e4#code) contract.
3. Paste it to a new `./abis/BLSRegistryCoordinatorWithIndices.abi.json` file.
5. Run `yarn codegen && yarn build`

**Example project:** https://github.com/rockawayx-labs/bug-reproducers/tree/dev/subquery/subql/ethereum-abi-ts

**Expected behavior:** SubQuery should generate all types for `BLSRegistryCoordinatorWithIndices` contract.

**Actual behavior:** The build fails with the following error:

```
yarn run v1.22.19
$ subql build
Project manifest generated to /Users/livthomas/Projects/rockawayx-labs/bug-reproducers/subquery/subql/ethereum-abi-ts/project.yaml
 ›   Error: [tsl] ERROR in /Users/livthomas/Projects/rockawayx-labs/bug-reproducers/subquery/subql/ethereum-abi-ts/src/types/abi-int
 ›   erfaces/BLSRegistryCoordinatorWithIndicesAbi.ts(59,154)
 ›         TS2339: Property 'deregisterOperatorWithCoordinator(bytes,tuple)' does not exist on type '{ 
 ›   OPERATOR_CHURN_APPROVAL_TYPEHASH(overrides?: CallOverrides | undefined): Promise<[string]>; blsPubkeyRegistry(overrides?: 
 ›   CallOverrides | undefined): Promise<...>; ... 37 more ...; updateSocket(socket: string, overrides?: (Overrides & { ...; }) | 
 ›   undefined): Promise<...>; }'.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by bz888** [comment]
The latest CLI relase 4.2.6 should include the fix for this
@livthomas
