### ISSUE TITLE
`subql publish` broken output flag

### ISSUE THREAD

**Issue by bz888** [subquery/subql#2248]
### Prerequisites

* [x] Are you running the latest version(s)?
* [x] Have you searched the [documentation for your issue](https://academy.subquery.network/)?
* [x] Did you search for an existing issue or pull request?

### Description
on `subql publish -o -f.` `-o` is expected to output only the cid for pipeline purposes, however currently it is not behaving otherwise. I believe the functionality of the `output` flag was removed unintentionally.

**Comment by swizzmagik** [comment]
once this is fixed you can likely discard my [PR](https://github.com/subquery/cosmos-subql-starter/pull/79)
