### ISSUE TITLE
Support Enum creation and removal for schema migrations

### ISSUE THREAD

**Issue by bz888** [subquery/subql#2249]
### Prerequisites

* [x] Are you running the latest version(s)?
* [x] Have you searched the [documentation for your issue](https://academy.subquery.network/)?
* [x] Did you search for an existing issue or pull request?

### Description
Currently the Schema Migration feature does not support enum introduction or removal.

**Comment by stwiname** [comment]
Fixed in https://github.com/subquery/subql/pull/2251
