### ISSUE TITLE
missing transaction on eth-sdk

### ISSUE THREAD

**Issue by bz888** [subquery/subql#2254]
### Prerequisites

* [x] Are you running the latest version(s)?
* [x] Have you searched the [documentation for your issue](https://academy.subquery.network/)?
* [x] Did you search for an existing issue or pull request?

### Description
https://moonbeam.moonscan.io/tx/0x222b9f724670efc21bedb9560079ada2ea400dda64f01980dde0e9e11ae845a3

on transaction like such, the transaction is missing from the even. 

### Details

These details can help to reproduce the environment the issue is occurring

**Local Environment:** [You can get this information from executing `subql version`.]
**Query Version:** [What is the version of the query service?]
**Indexer Version:** [What is the version of the indexer service?]
**Network Details:**
  * [Network]
  * [Block height, a block height where the issue is happening]
  * [Dictionary endpoint, if used]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Example project:** [A link to a minimal example that can reproduce the issue]

**Expected behavior:** [What you expected to happen]

Should have a transaction field on the event object

**Actual behavior:** [What actually happened]

When logging the `event.transaction` its undefined, but when looking the event, the args data does show the transaction data

### Any other information

Is there any other information you would like to add?

**Comment by stwiname** [comment]
This was an issue from the project cloning the event which removes the getter for the transaction
