### ISSUE TITLE
`_block_range` filter not applied inside an order by select

### ISSUE THREAD

**Issue by bz888** [subquery/subql#2362]
### Prerequisites

* [x] Are you running the latest version(s)?
* [x] Have you searched the [documentation for your issue](https://academy.subquery.network/)?
* [x] Did you search for an existing issue or pull request?

### Description

```
query nfts {
	items(
		orderBy: LISTINGS_MAX_PRICE_AMOUNT_ASC
	) {
		nodes {
			listings {
				nodes {
					priceAmount
				}
			}
		}
	}
}
```

The orderBy on this query does not apply block_range on it. This is shown through `query-explain` flag on query-service.

### Details

These details can help to reproduce the environment the issue is occurring
`@subql/query: v2.10.0`
### Steps to Reproduce
Use any starter project, and when using orderBy (entity value) and ensure historical is enabled

_block_range filter is expected to be applied over the ORDER_BY value.

**Comment by stwiname** [comment]
Can you please add an example project and the SQL from query explain

**Comment by asifalisaifi81** [comment]
how add it

**Comment by pyncz** [comment]
Hey @stwiname !
Not sure if you saw it but the issue was created based on my feedback in our shared slack channel.

The result `pgsql` looks like this:
```pgsql
with __local_0__ as (select to_json((json_build_object('__identifiers'::text, json_build_array(__local_1__."_id"), '@listings'::text, (with __local_2__ as (select to_json((json_build_object('__identifiers'::text, json_build_array(__local_3__."_id"), 'priceAmount'::text, ((__local_3__."price_amount"))::text))) as "@nodes" from (select 
	__local_3__.*
	from "app"."listings" as __local_3__
	
	where (__local_3__."item_id" = __local_1__."id") and (__local_3__._block_range @> $1::bigint) and (__local_3__._block_range @> $1::bigint) and (TRUE) and (TRUE)
	order by __local_3__."_id" ASC
	limit 100
	) __local_3__), __local_4__ as (select json_agg(to_json(__local_2__)) as data from __local_2__) select json_build_object('data'::text, coalesce((select __local_4__.data from __local_4__), '[]'::json)) )))) as "@nodes" from (select 
	__local_1__.*
	from "app"."items" as __local_1__
	
	where (__local_1__._block_range @> $1::bigint) and (TRUE) and (TRUE)
	order by (select max(__local_5__."price_amount") from "app"."listings" __local_5__ where (__local_5__."item_id" = __local_1__."id")) ASC,__local_1__."_id" ASC
	limit 100
	) __local_1__), __local_6__ as (select json_agg(to_json(__local_0__)) as data from __local_0__) select coalesce((select __local_6__.data from __local_6__), '[]'::json) as "data" 
```
...So it looks like a `__local_5__._block_range` filter inside the `order by (select ... )` is missing. With additional ` and (__local_5__._block_range @> $1::bigint)` filter added, it works like a charm.

We added @bz888 to our project already, let me know if you need access as well. Not minimal reproduction tho, but still might be useful to check the relations / config, I guess.

Feel free to reach out if I can provide any additional info.
Thank you!
