### ISSUE TITLE
[$1000 in SQT] Graph Project Migration, migrate graphql schema

### ISSUE THREAD

**Issue by stwiname** [subquery/subql#2388]
### Description

Update the CLI migration command to migrate a graphql schema from a subgraph to a graphql schema that works with SubQuery.

### Requirements

* Test coverage of at least 80% on new code changes
* Throws an error if there is a feature from the graph that is not currently possible with SubQuery, this should include any data types and directives. [The Graph Schema Doc](https://docs.thegraph.academy/official-docs/developer/create-a-subgraph#the-graph-ql-schema) [SubQuery Schema Doc](https://academy.subquery.network/build/graphql.html#defining-entities)

There is an entry point to implement this functionality which can be found [here](https://github.com/subquery/subql/blob/main/packages/cli/src/controller/migrate/schema/migrate-schema.controller.ts#L6)

**Comment by intensodefi** [comment]
Hello @stwiname,
I'm interested in this task and want to start to work on it.

**Comment by stwiname** [comment]
@intensodefi i've assigned it to you

**Comment by stwiname** [comment]
Hi @intensodefi have you made any progress on this?

**Comment by stwiname** [comment]
@intensodefi I have unassigned you from this task so others can also work on it. If you are still working on it please provide an update and I can reassign you
