### ISSUE TITLE
[Bug of Graphql] Or filter return wrong value

### ISSUE THREAD

**Issue by HuberTRoy** [subquery/subql#2399]
### Prerequisites

* [x] Are you running the latest version(s)?
* [x] Have you searched the [documentation for your issue](https://academy.subquery.network/)?
* [x] Did you search for an existing issue or pull request?

### Details

https://explorer.subquery.network/subquery/subquery/subquery-mainnet

### Steps to Reproduce

Use the query:

```
query GetDashboard {
  delegations(filter: {
      exitEra: {isNull: true}, 
      or: {
        exitEra: {greaterThan: 12}
      }
  }) {
    totalCount
  }
  onlyNull: delegations(filter: {exitEra: {isNull: true}}) {
    totalCount
  }
  onlyNumber: delegations(filter: {exitEra: {greaterThan: 12}}) {
    totalCount
  }
}
```

The first result return 0, `onlyNull` or `onlyNumber` actually have values.

**Comment by stwiname** [comment]
The `or` query is not correct. It should be like below:

```gql
query GetDashboard {
  delegations(filter: {
      or: [
        {exitEra: {isNull: true}}, 
        {exitEra: {greaterThan: 12},}
      ]
  }) {
    totalCount
  }
  onlyNull: delegations(filter: {exitEra: {isNull: true}}) {
    totalCount
  }
  onlyNumber: delegations(filter: {exitEra: {greaterThan: 12}}) {
    totalCount
  }
}

```
