### ISSUE TITLE
[query] prevent deep nested query

### ISSUE THREAD

**Issue by zhex** [subquery/subql#241]
the deep nested query will cause the slow SQL issue and effect all the database. we need to prevent this happen.

Option 1:
add middleware to check the query nested level and throw an error if it is too deep.

Option 2:
add cut the deeper nest query and continue to run.

**Comment by jiqiang90** [comment]
https://github.com/subquery/subql/pull/923

It will require improvement for complexity estimation, currently we count single field as complexity 1, which is not quit right.
