### ISSUE TITLE
Error parsing Kusama v1002005 

### ISSUE THREAD

**Issue by killbond007** [subquery/subql#2439]
### Prerequisites

* [x ] Are you running the latest version(s)?
* [x ] Have you searched the [documentation for your issue](https://academy.subquery.network/)?
* [ x] Did you search for an existing issue or pull request?

### Description

subquery-node_1  | 2024-06-11 19:31:01             VEC: Unable to decode on index 2 createType(ExtrinsicV4):: createType(Call):: findMetaCall: Unable to find Call with index [0, 24]/[0,24]
subquery-node_1  | 2024-06-11 19:31:01        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: findMetaCall: Unable to find Call with index [0, 24]/[0,24]
subquery-node_1  | 2024-06-11T19:31:01.246Z <fetch> ERROR failed to fetch Block hash="0xdfc73276f348d549d4f3a161f32180bf212195adc7ec2989cd5a312f6513ed5c" height="23566295" 

### Details

These details can help to reproduce the environment the issue is occurring

**Local Environment:** [You can get this information from executing `subql version`.]
**Query Version:** [What is the version of the query service?]
**Indexer Version:** [What is the version of the indexer service?]
**Network Details:**
  * [Network]
  * [Block height, a block height where the issue is happening]
  * [Dictionary endpoint, if used]

example subql-starter

**Comment by stwiname** [comment]
This PR should hopefully fix the issue https://github.com/subquery/subql/pull/2440
