### ISSUE TITLE
Kusama indexing malfunction since recent runtime upgrade (bumping polkadot-api version not working?)

### ISSUE THREAD

**Issue by wangminqi** [subquery/subql#2444]
It seems, after latest Kusama runtime upgrade on block 23565293, the subquery will not be able to decode blocks with extrinsic (closet one should be 23565529)

The console reports 
"VEC: Unable to decode on index 2 createType(ExtrinsicV4):: createType(Call):: Call: failed decoding system.setStorage:: Struct: failed on args: {"items":"Vec<(Bytes,Bytes)>"}:: decodeU8aStruct: failed at 0x0300c4eaa8768680c44d6df00027c4bb… on items (index 1/1): Vec<(Bytes,Bytes)>:: Vec length 2833957888 exceeds 65536" 

"failed to fetch Block hash="0x90c6bc492d4b17c6a49d032c49c9124373c1b3d2867154a9fe88217138c6f5e5" height="23565529"

**The way to reproduce it is running any subql project on Kusama till corresponding block (e.g. 23565529,  23565535, 23566139)**

I have tried different npm version, but not help.
currently I am using: 
├── @polkadot/api@11.2.1
├── @subql/cli@4.13.1
├── @subql/testing@2.1.1
├── @subql/types@3.6.1
└── typescript@5.4.5

<img width="1031" alt="image" src="https://github.com/subquery/subql/assets/46511820/2d533a89-fb4a-4863-b84d-6180039df216">

**Comment by wangminqi** [comment]
I see a previous issue with https://github.com/subquery/subql/issues/2439
But it seems to be a different fix, and the fix of bumping polkadot-api version to 11.2.1 is not solving this one as I tried.

**Comment by jiqiang90** [comment]
Hi @wangminqi which version of subql-node you used? We have recently update polkadot dependencies in our sdk, I tested locally it should work for these blocks. Please try v4.6.4 https://www.npmjs.com/package/@subql/node/v/4.6.4

**Comment by wangminqi** [comment]
It seems subql node is not a neccessary part for indexing locally in old template code.
https://github.com/subquery/subql-starter/blob/main/Polkadot/Polkadot-starter/package.json#L28.
Some templates still do not have it.

 But after you comment I added it rerun **npm install** and try.
My current local 
npm list return:
├── @polkadot/api@11.2.1
├── @subql/cli@4.13.1
├── @subql/node@4.6.4
├── @subql/testing@2.1.1
├── @subql/types@3.6.1
└── typescript@5.4.5

Which is not working.

But after I run,  npm install -g @subql/node
Everything works then! Thank you.
