### ISSUE TITLE
The query app being killed due to idle TCP connections to postgresql db

### ISSUE THREAD

**Issue by mpastecki** [subquery/subql#2520]
### Prerequisites

* [x] Are you running the latest version(s)?
* [x] Have you searched the [documentation for your issue](https://academy.subquery.network/)?
* [x] Did you search for an existing issue or pull request?

### Description

The query app being killed due to idle connections to postgresql db.

### Details

In our environment the tcp connections between services are killed if found to be inactive. To be more precise we use a Service Mesh with Envoy Proxies attached to each services. [Envoy proxy](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/tcp_proxy/v3/tcp_proxy.proto) by default kills connections that are inactive for 1 hour.

The query package uses a [pg.Pool](https://node-postgres.com/apis/pool) instance to manage database clients.

There are two pg.Clients explicitly used that cause us some issues:

https://github.com/subquery/subql/blob/e9f357d0ea1d6ffa41a3c807ec6f3ce755c4b737/packages/query/src/configure/configure.module.ts#L13-L24

Here, as I get it, it is to test whether the provided SSL configuration is valid, and clear it otherwise. The problem is that the client is not released once the check happens. So if there is any mechanism that checks for idle connections, the client will be killed eventually and that causes the subql/query app to be killed as there is no error listener attached to the client. Attaching an error listener to the pool is not enough to handle these kind of exceptions. One has to be attached to the client too.

The simplest fix would be to modify the code to release the client once it is no longer in use:

```ts
 async function ensurePool(poolConfig: PoolConfig): Promise<Pool> { 
   const pgPool = new Pool(poolConfig); 
   try { 
     const pgClient = await pgPool.connect();
   } catch (e: any) { 
     if (JSON.stringify(e.message).includes(CONNECTION_SSL_ERROR_REGEX)) { 
       poolConfig.ssl = undefined; 
       return ensurePool(poolConfig); 
     } 
   } finally {
     // Release the client back to the pool
     pgClient.release();
   }
   return pgPool; 
 } 
```

The other pg.Client is explicitly initialized here:

https://github.com/subquery/subql/blob/e9f357d0ea1d6ffa41a3c807ec6f3ce755c4b737/packages/query/src/graphql/graphql.module.ts#L163-L176

This one is a bit more tricky, if I am not mistaken, as its goal is to listen for `schema_updated` notifications and call the `schemaListener` method to handle it. There is a real need for keeping this client idle and releasing it doesn't seem to be an option.

In our case, even if I explicitly enabled keepAlive connection parameter, this wouldn't reset the Envoy's idle timeout timers. I had to look for a different approach. And one of them would be to periodically send a simple SQL query, something like this:

```ts
 if (!argv['disable-hot-schema']) { 
   try { 
     const pgClient = await this.pgPool.connect(); 
     await pgClient.query(`LISTEN "${hashName(dbSchema, 'schema_channel', '_metadata')}"`); 

     // Set up a keep-alive interval to prevent the connection from being killed
     const keepAliveInterval = setInterval(async () => {
       try {
         await pgClient.query('SELECT 1');
       } catch (err) {
         getLogger('db').error('Schma listener client keep-alive query failed: ', err);
       }
     }, 180000); // 180 seconds interval
  
     pgClient.on('notification', (msg) => { 
       if (msg.payload === 'schema_updated') { 
         void this.schemaListener(dbSchema, options); 
       } 
     }); 
   } catch (e) { 
     logger.warn('Failed to init hot-schema reload', e); 
   } 
 } 
```

### Steps to Reproduce

It would be rather complex to reproduce, I can provide steps if requested however.

**Expected behavior:** 
- pg Clients are returned to the Pool if not needed
- Schema change listener keeps the connection active to avoid being killed

**Actual behavior:** 
- pg.Client responsible for testing SSL config is not released to the pool
- The pg.Client responsible for listening for DB schema change keeps the connection idle unless there are any schema changes

### Any other information

I'm opening the issue first to see if there are any concerns, or suggestions. Happy to open a PR when the issue is reviewed.

**Comment by stwiname** [comment]
Hey @mpastecki, thanks for the deep dive. 

This all makes sense to me and we would happily accept a PR. My only suggestion, which is minor, would be to have a keep alive interval that is configurable.

**Comment by mpastecki** [comment]
Thanks @stwiname, [PR](https://github.com/subquery/subql/pull/2525) created.
