### ISSUE TITLE
The files in the /tmp directory can accumulate to a very large size(more than 70GB after 1 week running)

### ISSUE THREAD

**Issue by icezohu** [subquery/subql#2545]
### Prerequisites

* [ ] Are you running the latest version(s)?
* [ ] Have you searched the [documentation for your issue](https://academy.subquery.network/)?
* [ ] Did you search for an existing issue or pull request?

### Description

cid: QmPkTXq1hw1MNt8rVEySAL3izgYa5jRdQbEK9AmERhcM2S
indexer version: v5.2.2

### Details

These details can help to reproduce the environment the issue is occurring

**Local Environment:** [You can get this information from executing `subql version`.]
**Query Version:** [What is the version of the query service?]
**Indexer Version:** [What is the version of the indexer service?]
**Network Details:**
  * [Network]
  * [Block height, a block height where the issue is happening]
  * [Dictionary endpoint, if used]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Example project:** [A link to a minimal example that can reproduce the issue]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Any other information

Is there any other information you would like to add?

**Comment by yoozo** [comment]
If a project is deployed using a CID, it needs to download all deployment files each time. If Docker is used to start the project and it is set to auto-restart, when the project encounters a problem or reaches the target height, the container restarts and fetches the new CID deployment files again. Over time, this will take up a lot of space in the TEMP directory.
