### ISSUE TITLE
Near Price Oracle example does not work as expected

### ISSUE THREAD

**Issue by Tguntenaar** [subquery/subql#2546]
### Prerequisites

* [x] Are you running the latest version(s)?
* [x] Have you searched the [documentation for your issue](https://academy.subquery.network/)?
* [x] Did you search for an existing issue or pull request?

### Description

I completed the [NEAR Quickstart tutorial](https://academy.subquery.network/indexer/quickstart/quickstart_chains/near.html) and cloned the [NEAR Price Oracle Example](https://github.com/subquery/near-subql-starter/tree/main/Near/near-priceoracle-example) to my local machine. I also followed the instructions in the README.md file.

I want to mention that after installing the SubQuery CLI via npm, the subql help command no longer works, though simply running subql does. This seems like a minor discrepancy in the documentation.

When I ran `yarn install` followed by `yarn dev`, everything appeared to start up correctly. However, after letting it run for a while and querying the example in the playground, I noticed that data is not being indexed. I've tried running the indexer from the example's start block `50838152` and also adjusted the start block to `126408196`, removing the Postgres data and Docker container between attempts. It’s worth noting that if you change the start block and then run `yarn dev` again, the service won’t start up. As you can see in the screenshot below:

<img width="1364" alt="Screenshot 2024-08-23 at 15 51 10" src="https://github.com/user-attachments/assets/79a8efce-abe8-4e16-9e23-48f88ba7f4eb">

### Details

These details can help to reproduce the environment the issue is occurring

**Local Environment:** @subql/cli/5.2.4 darwin-arm64 node-v20.9.0
**Query Version:** subquerynetwork/subql-query:latest
**Indexer Version:** subquerynetwork/subql-node-near:latest
**Network Details:**
  * NEAR mainnet, RPC https://archival-rpc.mainnet.near.org
  * `50838152` from the example and a more recent block `126408196`
  * The default near dictonaries also give an error.
<img width="1153" alt="Screenshot 2024-08-27 at 15 51 31" src="https://github.com/user-attachments/assets/e8dfa122-e6eb-4f16-b88f-6d819e1da8cf">

### Steps to Reproduce

1. npm install
2. npm run dev
3. go to http://localhost:3000
4. Run this query
<details><summary> Run this query </summary> 

```graphql
query {
  prices(first: 50, orderBy: BLOCK_HEIGHT_DESC) {
    nodes {
      id
      assetID
      price
      decimals
      oracleId
      oracle {
        id
      }
    }
  }
  oracles(first: 50, orderBy: PRICES_COUNT_DESC) {
    nodes {
      id
      creator
      blockHeight
      timestamp
    }
  }
}
```

</details>

5. See that there is no data.

**Example project:** [The price oracle example](https://github.com/subquery/near-subql-starter/tree/main/Near/near-priceoracle-example)

**Expected behavior:** Expected to have output with data in the playground environment on http://localhost:3000.

**Actual behavior:** 

The actual behavior seems to index blocks in batches of 5 but it does not store anything in the postgress database. 
<img width="1312" alt="Screenshot 2024-08-27 at 15 58 45" src="https://github.com/user-attachments/assets/5ff90454-3fca-405a-b898-2ca192fbf31d">

<img width="1153" alt="Screenshot 2024-08-27 at 15 46 01" src="https://github.com/user-attachments/assets/279a1756-af5a-4988-bf15-fc7bd3be822a">

**Comment by stwiname** [comment]
@Tguntenaar please try the latest version of the SDK and starter project. Everything should work now.

**Comment by jamesbayly** [comment]
I've also made some minor optimisations and confirmed data being saved https://github.com/subquery/near-subql-starter/tree/main/Near/near-priceoracle-example
