### ISSUE TITLE
Strange display bug in playground

### ISSUE THREAD

**Issue by 99Kies** [subquery/subql#2560]
Both my coworker and I have encountered this display bug in the subquery playground this month.

<img width="503" alt="image" src="https://github.com/user-attachments/assets/884cfb4c-3785-4518-b9d9-8bab39b6b970">

**Comment by jamesbayly** [comment]
What version of subql-query are you seeing this in?

**Comment by jamesbayly** [comment]
Image:         onfinality/subql-query:latest
    Image ID:      docker.io/onfinality/subql-query@sha256:ff97272bb60666440839e33c29d541306d3e1aa605082858d422c841523b8a13
