### ISSUE TITLE
Alternative ID types

### ISSUE THREAD

**Issue by stwiname** [subquery/subql#2562]
### Background

Currently all entities need to have `id: ID` to follow the graphql spec. Internally with postgres this creates a TEXT primary key column. This can have some limitations when using numbers as the id and ordering because it will order lexicographically.

### Solution

We can add an additional directive to the graphql schema to allow specifying a different underlying type.

```graphql
type Entity @entity {
  id: ID @dbType(type: "serial")
}
```

### Requirements

* This should still be compatible with historical indexing
* Limit the type to compatible types. 
* Compatible with schema migrations
* Update the store interface for Id to be optional when creating new entities and return the generated id. This could be pushed to a future release.

**Comment by jorgecuesta** [comment]
This is something we are looking forward for our project at Pocket Network https://github.com/pokt-network/pocketdex
