### ISSUE TITLE
ghost dependencies (compatibility with pnpm linker)

### ISSUE THREAD

**Issue by turadg** [subquery/subql#2621]
### Prerequisites

* [x] Are you running the latest version(s)? `"@subql/cli": "^5.3.3"`
* [x] Have you searched the [documentation for your issue](https://academy.subquery.network/)?
* [x] Did you search for an existing issue or pull request?

### Description

When using the Yarn `nodeLinker: pnpm`, the `yarn dev` command fails with,
```
Error: Cannot find module 'chalk'
Require stack:
- /opt/agoric/agoric-subql/node_modules/.store/@subql-cli-npm-5.3.3-f97be50ff8/package/bin/run
```

It looks like this is because [the run module/script requires chalk](https://github.com/subquery/subql/blob/d3c2a582ee297031e44363f0bcd652e9b307e0a8/packages/cli/bin/run#L5) but [the package.json doesn't declare it](https://github.com/subquery/subql/blob/main/packages/cli/package.json). I.e. a ghost dependency

### Steps to Reproduce

1. `echo "nodeLinker: pnpm" > .yarnrc.yml
2. `yarn install`
3. `yarn dev`

**Expected behavior:** [What you expected to happen]

`run` runs

**Actual behavior:** [What actually happened]

```
Error: Cannot find module 'chalk'
Require stack:
- /opt/agoric/agoric-subql/node_modules/.store/@subql-cli-npm-5.3.3-f97be50ff8/package/bin/run
```

I tried patching it up with this in `.yarnrc.yml`,
```
packageExtensions: {
  "@subql/cli@*": {
    dependencies: {
      chalk: "^4.0.0",
    },
  },
  "@subql/common@*": {
    dependencies: {
      "form-data": "^4.0.0"
    },
  },
}
```
but there was yet another and I don't know how many ghosts there are.

### Any other information

A good way to find ghosts is to change [the repo's nodeLinker](https://github.com/subquery/subql/blob/main/.yarnrc.yml) to pnpm. You might also adopt Corepack for specifying the packageManger.

**Comment by stwiname** [comment]
I've added the missing deps in this PR, there is more work required to support other package managers

https://github.com/subquery/subql/pull/2622

**Comment by turadg** [comment]
@stwiname this was closed "as completed" but as you point out, more work is required.

The title says “compatibility with pnpm linker” and the repo is still failing.

Mind reopening until the project is compatible with the pnpm linker?
