### ISSUE TITLE
replace bigint to BN instance

### ISSUE THREAD

**Issue by zhex** [subquery/subql#266]
the largest number for BigInt is 2^53 -1, it is not large enough for the cryptocurrency amount sometimes. So we need to use BN lib instead.

there are a few places we need to change:

- `codegen` command should generate bigint / bigdecimal type to BN
- support BN lib in sandbox globally
- add decimal parser for `Sequelize` to auto-convert  type between BN and decimal value

**Comment by ianhe8x** [comment]
This is misreading.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt
also https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER
2^53-1 is not max of BigInt but max of Number. And official suggests to use BigInt for number larger than this value.

**Comment by zhex** [comment]
yes, this is a misreading, the BigInt is int64, max limit base on the OS. will close this issue.
Also we need to make sure Sequelize will convert DB record to BigInt correctly.
