### ISSUE TITLE
Condition query  failed when use 'or' filter

### ISSUE THREAD

**Issue by sxlwar** [subquery/subql#290]
I want to query some transfers that send to or from a specific account, but it does not work as expected.

![image](https://user-images.githubusercontent.com/20088392/115990034-bb1fee00-a5f3-11eb-941f-18e51bcb9be5.png)

But it can work normally when querying separately.

query transfer from:
![image](https://user-images.githubusercontent.com/20088392/115989953-6ed4ae00-a5f3-11eb-8766-87859399b384.png)

query transfer to:
![image](https://user-images.githubusercontent.com/20088392/115990071-e73b6f00-a5f3-11eb-8c8e-d2f09cc6073d.png)

why does this happen, any idea?

**Comment by zhex** [comment]
please try the query below.

```
query {
    transfers(
        filter: {
            or: [
                {fromId: { equalTo: "xxxxx"} },
                {toId: { equalTo: "yyyyyy"} },
            ]
        }
    ) {
        
    }
}
```

**Comment by sxlwar** [comment]
@zhex amazing,  but how to find the right syntax?

**Comment by jamesbayly** [comment]
@sxlwar if you run your local SubQuery project with the `--playground` argument (e.g. `subql-query --name <project_name> --playground`) you will have a playground with documentation automatically generated from your GraphQL schema.

You can find information on the filter here (look for the docs button on the right)
![Uploading image.png…]()
