### ISSUE TITLE
 Unknown error occurred: Client, UnknownBlock, State already discarded for BlockId::Hash

### ISSUE THREAD

**Issue by qalqi** [subquery/subql#295]
I am getting this error for https://github.com/qalqi/snql and unable to deploy
`ERROR failed to fetch block Error: -32603: Unknown error occurred: Client, UnknownBlock, State already discarded for BlockId::Hash, 0x414f054028185a8d26da37dba1700636fd6d69720c6b7757d2f83382ee0ea9bb`

How to fix it?

**Comment by jiqiang90** [comment]
Hi I tried to connect to your endpoint with polkadot app, it appears failed to retrieve the block details, I got the same error from the api, and it only works with most recent blocks.

I guess this is what happened to you [State already discarded for BlockId](https://github.com/polkadot-js/api/issues/2629)
