### ISSUE TITLE
Detect chain ability and handle differences of chains smartly

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#299]
`subql` aims to support all substrate-based chains, but how we define substrate-based chains? Differences exist among substrate-based chains, some of them due to deriving from a different commit of substrate, some of them are chooses made by developer team of the chain.
For the same chain, how a node is configured also makes a difference. (--rpc-methods=Unsafe or not)

In a recent PR, we optimize our muti query logic to use `rpc.queryStorageAt` but what if the connected node doesn't support this rpc?

Another example is we implemented a way to query a range of historical events via `rpc.queryStorage` but then made it optional branch since we don't know if this rpc is supported and enabled for the node.

My thought is the ability of chain (the node we connect to) is defined by the rpc methods it supported. we can use `rpc.rpc_methods` or make probe calls to detect whether a certain rpc is supported. We store this info and use it to chose best approach for a certain task of subql.

Once https://github.com/paritytech/substrate/pull/7780 is used by polkadot/kusama or other ecosystem projects. we can make use of this rpc and support state filter. This is another use case for this task.

**Comment by jiqiang90** [comment]
This can be replaced by https://github.com/subquery/subql/issues/1654, close now
