### ISSUE TITLE
subql node error: can not read subarray of null

### ISSUE THREAD

**Issue by sxlwar** [subquery/subql#314]
After chain types updated, an error occurs as the screenshot below:
![image](https://user-images.githubusercontent.com/20088392/118951750-ef39c500-b98d-11eb-92f7-44986748b181.png)

repo https://github.com/darwinia-network/subql/tree/pangolin

**Comment by ianhe8x** [comment]
This is because the latest height of your network is only 7467 but you set startBlock: 30700 in project.yaml
