### ISSUE TITLE
can't get the chain properties through  `api.rpc.system.properties`

### ISSUE THREAD

**Issue by qwer951123** [subquery/subql#329]
When I tried to get the currency's decimal and token symbol, The universal way is to query `api.rpc.system.properties`,  but the RPC call is not historical, it was be banned.

Is there some way to get the chain properties at the fetch service to begin?

**Comment by ianhe8x** [comment]
This is a good point. But after a second thought, query system properties in mapping function is weird because it is going to be called every times your handler is triggered.

**Comment by ianhe8x** [comment]
You can use `api.registry.chainDecimals`, `api.registry.chainTokens` and `api.registry.chainSS58` to retrieve these infos
