### ISSUE TITLE
 how can i print log in SubQuery Project(created by subql init --starter PROJECT_NAME)

### ISSUE THREAD

**Issue by baidang201** [subquery/subql#335]
hi, how can i print log in SubQuery Project(created by subql init --starter PROJECT_NAME), i try use console.log ,but can not see log in the docker output. 

i saw packages/node/src/utils/logger.ts in subql repository. but maybe there are better way subquery team had used.

**Comment by jiqiang90** [comment]
Hi, please use `logger.<method>` in your project. eg `logger.info(xxx)`/ `logger.error(xxx)`

**Comment by baidang201** [comment]
thanks
