### ISSUE TITLE
do subql support union in schema.graphql?

### ISSUE THREAD

**Issue by baidang201** [subquery/subql#340]
https://graphql.org/learn/schema/#union-types

**Comment by ianhe8x** [comment]
Union looks doable for JSONObjectType, will need some more research on it.
And it doesn't make sense for entity relation.
Maybe you can share your use case to help us understand the value of supporting it.

**Comment by baidang201** [comment]
there are custome token and system token, and show it in account assert history

**Comment by ianhe8x** [comment]
Can they share same struct to avoid using union-types?

**Comment by baidang201** [comment]
emm, same struct would slove it this time, may add type field, and waste some space.

**Comment by jiqiang90** [comment]
This is duplicate with https://github.com/subquery/subql/issues/393

Please track in another ticket
