### ISSUE TITLE
adjust timeout stragety

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#341]
The reality is we can not terminate execution of code in the sandbox once it is submitted.
There's a scenario, the code execution lasts very long time and because the timeout mechanism we reject the transaction and start a new execution. So eventually there will be multiple execution concurrently running in the V8 runtime, and make things even worse.
I think to avoid that, we should change timeout a longer time like 30min, and exit the process when it actually happens. The rationality is if we can not kill sandbox we kill the app together with the sandbox.

**Comment by jamesbayly** [comment]
Can we also improve the error message in the case of a timeout

**Comment by ianhe8x** [comment]
We do print a message, but in the other case, logs are flooded so can't see it very clearly. We've added log filter for category (our hosted service), now it should be easier.

**Comment by jiqiang90** [comment]
I think this is done
