### ISSUE TITLE
will subql support import custom resolvers that can we search  like inter join and nested query ?

### ISSUE THREAD

**Issue by baidang201** [subquery/subql#346]
1  resolver link:
https://www.apollographql.com/blog/graphql/filtering/how-to-search-and-filter-results-with-graphql/
https://www.apollographql.com/docs/apollo-server/data/resolvers/#the-context-argument
```
// Constructor
const server = new ApolloServer({
  typeDefs,
  resolvers,  //init with resolver here
  context: ({ req }) => ({
    authScope: getScope(req.headers.authorization)
  })
}));

// Example resolver
(parent, args, context, info) => {
  if(context.authScope !== ADMIN) throw new AuthenticationError('not admin');
  // Proceed
}
```

2 question:
https://stackoverflow.com/questions/51958018/nested-query-with-variable-in-apollo-graphql

3 subql is not init resolver this time
packages/query/src/graphql/graphql.module.ts
```
    const server = new ApolloServer({
      schema,  //there not resolver after schema
      context: {
        pgClient: this.pgPool,
      },
      cacheControl: {
        defaultMaxAge: 5,
      },
      debug: this.config.get('NODE_ENV') !== 'production',
      playground: this.config.get('playground'),
      subscriptions: {
        path: '/subscription',
      },
    });
```

**Comment by ianhe8x** [comment]
Not quite sure what you want us to do. Subql exposes a standard graphql endpoint, so you can do whatever with it, like use it in apollo federation or else. If you want to change subql-query's behaviour, you can fork the project and make your changes, but then it won't be supported by our hosted service, you need to run your customized copy in your own infra.

**Comment by jiqiang90** [comment]
Close for now
