### ISSUE TITLE
yarn global not work for subql-node & subql-query

### ISSUE THREAD

**Issue by jiqiang90** [subquery/subql#355]

**Comment by jiqiang90** [comment]
Due to `chalk` dependencies conflict,  we will disable use yarn global, and update this in document

**Comment by ianhe8x** [comment]
To correct jiqiang90's statement, it is actually due to poor dependency management of `yarn global` that lead to an error. We should remove `yarn global` in the documentation. and suggest everyone just use `npm i -g`.

**Comment by jamesbayly** [comment]
Additionally we're going to need to update subql-starter and other repos
