### ISSUE TITLE
[bug] subql-node --help shows only 2 options

### ISSUE THREAD

**Issue by paulvi** [subquery/subql#374]
subql-node --help shows only 2 options:
```
% subql-node --help
Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
  ```
  Not all as shown in https://github.com/subquery/subql/tree/main/packages/node#readme
  
  > @subql/cli/0.10.0 darwin-x64 node-v14.16.0

**Comment by ianhe8x** [comment]
Thanks for reporting, `subql-node` will show all options though.

**Comment by paulvi** [comment]
yes, `subql-node` without `--help` does show more/full help

**Comment by jamesbayly** [comment]
This should be something we resolve @ianhe8x  - thanks @paulvi
