### ISSUE TITLE
support to configure with `project.js`

### ISSUE THREAD

**Issue by amphineko** [subquery/subql#383]
Allows creating a SubQuery project with default exports from `project.js`.

Benefits:
- Projects may programmatically import Substrates type definitions (e.g import from other packages)

**Comment by ianhe8x** [comment]
It can be done as at some level, but with Metadata v14, no extra type definitions will be needed anymore. I think we can stay where we are at the moment.
https://github.com/polkadot-js/api/pull/3759

**Comment by jiqiang90** [comment]
We have supported load chain types from js, https://github.com/subquery/subql/pull/698. This can be closed
