### ISSUE TITLE
Override block height when deploying new version

### ISSUE THREAD

**Issue by ef1rspb** [subquery/subql#389]
Hi there!
In Fearless wallet we have 2 projects for Polkadot & Kusama nw and I have to push commits like 'Set startBlock {X}' for debugging purposes. It would be great to add field 'Override block height (optional)' for such cases.
Thx
<img width="491" alt="Screenshot 2021-07-13 at 10 15 54" src="https://user-images.githubusercontent.com/17689921/125408186-5048ac80-e3c3-11eb-9ac2-3bdff0604619.png">

**Comment by zhex** [comment]
hi, 
the `startBlock` in the project.yaml only works for a fresh deployment, do you mean to override the setting for a fresh deployment?

or the feature you like to have is re-index from a particular block height when a new commit be deployed?

**Comment by zhex** [comment]
@ef1rspb if it is just for fresh deployment, it is really easy to test your preferred `startBlock` on your local firstly. I don't find the value to support it in the hosted service.
