### ISSUE TITLE
CamelCase method naming introduce ambiguity

### ISSUE THREAD

**Issue by ef1rspb** [subquery/subql#390]
i.e. `payout_stakers` -> `payoutStakers, `batch_all` -> `batchAll` and so on. It is not obviously that CallBase.method transforms to camelCased, which is why our team spent several hours looking for bugs related to this feature :(
It would be nice to add this remark to documentation.
Thx

**Comment by ianhe8x** [comment]
I think you raised this issue in the wrong place, it is `https://github.com/polkadot-js/api` makes this conversion.
