### ISSUE TITLE
Can't get typesBundle to work

### ISSUE THREAD

**Issue by chipgogo** [subquery/subql#401]
I've been trying to get typesBundle to work on our subql-starter project but with no luck. I've checked with the tests in this project that polkadotjs api is being loaded with the typesBundle. If I don't have all my latest types in `network.types` in `project.yaml` then the type will fail on construction. Are there any working examples other than the tests here? I haven't found any examples from other subql projects that uses `typesBundle`. 

side note:

When specifying `spec_version` in the typesBundle `minmax`, I need to pass `undefined` to the array but it seems like the yaml parser in `loadProjectManifest` doesn't allow that since null is represented as null.

logging the manifest object parsed by `plainToClass` in `loadProjectManifest` gives me:
```
{ 
  minmax: [ 105, null ], 
  ...
}
```

@subql/cli  version "0.10.0"
@subql/common   version "0.9.0"
@subql/types   version "0.8.0"
@subql/validator   version "0.2.0"
@poladot/api   version "4.17.1"

**Comment by ianhe8x** [comment]
Basically if you can make it work against polkadot-js, then you shall be good to use it in subql. And any problems you have you should raise in polkadot-js's repo instead of here.

Regards of the error you got in `loadProjectManifest`, can you share your project and post the whole error message so we can help looking into it?

**Comment by igorgogo** [comment]
ah yes thanks for the response. i got typesBundle to work now by adding a replacing the `null` with a larger specVersion number. I believe polkadotjs expects minmax to contain number or undefined. my problem has been resolved but if only the null in `minmax` for typesBundle can parsed as undefined that'd be good.
