### ISSUE TITLE
Is The Historical Type Right If The Metadata Changed

### ISSUE THREAD

**Issue by qwer951123** [subquery/subql#404]
Sometimes, we upgrade the chain with the changed extrinsic, event data types, or some types. I am not sure that the type system will work right of the historical type.

I notice that the types bundle doesn't include versioned type, may the query will return some wrong data decoded?

**Comment by ianhe8x** [comment]
I think these cases have been well handled in polkadot-js. Types bundle allow you pass a specVersion range that a specific bundle will be applied to, which is used for polkadot/kusama themselves without questions.
We also do proper wrapping for you, redecorate queries for the historical block. If you encountered any issue, you can raise here so we can help solving it.

**Comment by qwer951123** [comment]
Thanks for the response, I will update the typesBundle which adds a spec version range, and do some tests for this case.

**Comment by jiqiang90** [comment]
Can be close now
