### ISSUE TITLE
Support query by block number (historical state)

### ISSUE THREAD

**Issue by jiqiang90** [subquery/subql#415]
**Problem:** 

Currently, subquery only supports storing the final state of index data. For example, we indexed a network called `ABC` and synchronized it to its latest height of 5000,  then the data in the database is reflected the result at this block height. 
But we don't know the state of the data when the altitude of 4000 is queried. Therefore, we need a way to record state changes with block heights. 

**Approach**

- Add an extra field to the table to record the range of blocks, eg [35, 38) means from block 35 to 37 it remain in this status. And when this record need to be "update", we create a new record with block range [38, ) 
- Insert a new record rather than update means we need to resolve the conflict of id, so rather let user created ID to primary key, we will generate another field to be PK. But we will face challenge for update entity relationships.  
- Ensure that the solution is scalable to current large projects (e.g. SubVis)

**Comment by ianhe8x** [comment]
## Scope 
### subql-node
1. new table schema for entity
  1. new an internal primary key (real primary key), auto-generated
  2. make id a normal column (indexed)
  3. add a extra column to store available range of blocks for each records
  4. Remove all foreign keys
2. handle primary key generation
3. maintain the block range for each set operation
4. adapt `store`'s set() and get()

### subql-query
1. Refactor/extend/fork postgraphile plugins
    1. Hide special columns: _id, block_range
    2. adapt to using the virtual primary id
        1. map id to ID in graphql schema instead of the real primary key (_id)
        2. Single entity query accept virtual id
    3. Rework relation implementation
        1. Abandon the way to detect relation from foreign key, there will be no foreign keys any more.
        2. Read relation from user’s graphql schema
        3. Refactor sql to use virtual id in the join statements
    4. Query schema supports additional parameters: blockheight/blocknumber 
    5. Wrap all query sql statements with blockrange condition

**Comment by jamesbayly** [comment]
https://github.com/subquery/grants/issues/7

**Comment by Zedonboy** [comment]
Hello.

I am a bit confused, I have a few questions.

1. What State<aspect of network> do you want to version.

2. Are we to create a Subquery project or contribute @subquery/node to have this feature.

Thank you.
