### ISSUE TITLE
db configuration does not work

### ISSUE THREAD

**Issue by ii-ii-ii** [subquery/subql#421]
![image](https://user-images.githubusercontent.com/69485494/128456804-e1fb14eb-6f6b-4ceb-927b-d576245c3dfd.png)

I have a config.yml file, and then DB_PORT is set to 5434

I started the project like this: `subql-node -c config.yml`

But it seems that the DB_PORT I configured does not work.

**Comment by ianhe8x** [comment]
db parameters are loaded from env not config file
