### ISSUE TITLE
Support BigInt on jsonField

### ISSUE THREAD

**Issue by jiqiang90** [subquery/subql#442]
The current implementation does not support BigInt type on jsonField object, which will cause issues due to JSON.stringfy. We should support this soon.

**Comment by jiqiang90** [comment]
```
//pg/lib/utils.ts
function prepareObject(val, seen) {
  if (val && typeof val.toPostgres === 'function') {
    seen = seen || []
    if (seen.indexOf(val) !== -1) {
      throw new Error('circular reference detected while preparing "' + val + '" for query')
    }
    seen.push(val)

    return prepareValue(val.toPostgres(prepareValue), seen)
  }
  return JSON.stringify(val)
}
```

- [ ] Convert this interface to Class
- [ ] toJson()
- [ ] toPostgres()
- [ ] toString()

**Comment by HZHAIX** [comment]
Do you still plan to support this in the future?

**Comment by jiqiang90** [comment]
Example: 

<img width="447" alt="image" src="https://github.com/subquery/subql/assets/10431657/8fbf0bb7-382e-4ecf-b5d6-8c9b255af451">

![image](https://github.com/subquery/subql/assets/10431657/f57eadcb-22a3-4328-9fbd-802f627b5d95)



```
  record.field3 = {value:(balance as Balance).toBigInt()};
```

This is supported
