### ISSUE TITLE
Documentation on how a usr can make health checks to the subql/node service

### ISSUE THREAD

**Issue by jamesbayly** [subquery/subql#447]
When running your own node, how you can ensure that it is alive:
- Health check endpoints
- Other valuable metadata bout the current block height etc

**Comment by jamesbayly** [comment]
@seandotau can we bump this in priority - i've shared this ticket to 3 customers in the last week

**Comment by seandotau** [comment]
Will do.

**Comment by seandotau** [comment]
https://github.com/subquery/subql/pull/465
