### ISSUE TITLE
Support distinct when querying data

### ISSUE THREAD

**Issue by Leouarz** [subquery/subql#450]
**Problem :**
Currently, if you have thousands of records with some similar properties (for example a serie Id and a corresponding image url), you can't query using distinct on one or multiple fields (to have for example only 1 image per serie).
It means, we have to filter the response and it can mess with other things like pagination.

**Solution :**
It would be nice to have the possibility to add distinct in the graphql query as it's possible with Postgres.

(Don't hesitate to tell me if I got something wrong or if you need more information, thank you all)

**Comment by ianhe8x** [comment]
It's possible to add distinct via a custom postgraphile plugin. We did some investigation before but failed to find any existing lib. Welcome contribution here.
