### ISSUE TITLE
is it possible reconnect in subql-node after ws link is broken and resume

### ISSUE THREAD

**Issue by baidang201** [subquery/subql#458]
i run a subql node, when my ws is brroken, it report "having a problem when get finalized block error: disconnected from wss://xxxxxx: 1006:: Connection dropped by remote peer.",
when my ws is ready, subql-node do not go on fetch block.

![1630412326800](https://user-images.githubusercontent.com/3405789/131501673-e3f8525e-165d-4057-9f89-68e06d226340.jpg)

**Comment by ianhe8x** [comment]
We will take a look.

**Comment by ianhe8x** [comment]
We actually exit in this case, following fast failure principle. We run the subql in k8s which will restart for unexpected exit.
If you run it locally, you can use nodemon or other wrapper to help you restart it automatically.

**Comment by baidang201** [comment]
thx
