### ISSUE TITLE
Access denied to require 'https'

### ISSUE THREAD

**Issue by jonalvarezz** [subquery/subql#462]
Hi everyone,

ignorant question: Why is it that the `https` module is excluded from the [built-in NodeJS modules](https://doc.subquery.network/create/mapping.html#built-in-modules)?

Some of my events hold IPFS CIDs where more metadata is stored and I am looking to resolve that CID and populate the extra metadata in the indexer entity.

That's quite easy to achieve but then I found out that `node-fetch` and the `https` would stop the VM from starting which made me think that most likely I am missing the big picture here.

Thanks,

**Comment by jamesbayly** [comment]
A core premise of SubQuery is that it is deterministic. It will always result in the same output for the same block for the same project. This is a key rule that we must hold as we work towards a decentralised network to ensure validity of data.

I understand that the VM is configured to not start in the situation where we potential external inputs are detected - like https

**Comment by jamesbayly** [comment]
One potential option here would be to allow an `--unsafe` flag of sorts that allows you to bypass these checks

**Comment by jonalvarezz** [comment]
Thanks, @jamesbayly 

I think I see the point here. Even though fetching data from IPFS doesn't go against that premise, having the `https` module available will open the door to make it no longer deterministic.

Would fetching from IPFS only be another option? like a built-in module to do that

**Comment by Moehringen** [comment]
> One potential option here would be to allow an `--unsafe` flag of sorts that allows you to bypass these checks
hi James， where to set this flag? any detials? thanks

**Comment by bianyunjian** [comment]
As a temporary solution,  the docker image file can be edit and change the builtin modules. 

1. first we need to start the docker instance 
2. eter the docker instance terminal, 
    the file locations at `/usr/local/lib/node_modules/@subql/node/dist/indexer/sandbox.js`
 you can add "https" 
![image](https://user-images.githubusercontent.com/12878885/132094628-9078270a-75b8-43fa-8cc0-0b3ca0b4449d.png)


3. we can use 'https' module and add some test codes.
![image](https://user-images.githubusercontent.com/12878885/132094611-1934b973-fa09-4f57-a210-129960eacb17.png)

4. restart the docker instance and it works
![image](https://user-images.githubusercontent.com/12878885/132094678-c85bacbc-1a4e-40c0-889a-1b85eb30e1f7.png)


5. we can the docker instance to a new docker images , as it's a standalone version with trick.

**Comment by bianyunjian** [comment]
@jamesbayly @Moehringen

**Comment by bianyunjian** [comment]
Another way to change the sandbox.js

1.  create a clone of sandbox.js and rename it to sanbox-trick.js  ( can be any valid file name)
![image](https://user-images.githubusercontent.com/12878885/132114582-cc08c781-8831-4dd7-976f-5619f2f2411f.png)

2. edit  sanbox-trick.js
![image](https://user-images.githubusercontent.com/12878885/132114627-5313e1b4-cc96-4023-bc8b-8da66689a31e.png)

3. update docker-compose.yml
![image](https://user-images.githubusercontent.com/12878885/132114604-66a76d86-568e-409e-bedd-f46f8ce69ddc.png)

4. run script:
```
docker-compose up
```

this solution should be more flexible and controllable.

**Comment by ianhe8x** [comment]
> Thanks, @jamesbayly
> 
> I think I see the point here. Even though fetching data from IPFS doesn't go against that premise, having the `https` module available will open the door to make it no longer deterministic.
> 
> Would fetching from IPFS only be another option? like a built-in module to do that

In a way you are right but not totally, my understanding even with a given ipfs address, there's no guarantee the file is available all the time, and reachable by everyone. 
Also it introduces another dependency for whoever run the indexer node.
So it will not be an easy decision for us to make supporting ipfs.

**Comment by jiqiang90** [comment]
Now it can be supported by pass `--unsafe` in node, https://github.com/subquery/subql/pull/629.

Close this now
