### ISSUE TITLE
Document how to debug a subquery project locally

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#468]
Many people asked for it. Before we have a proper `subql test` command, at least we can help user set breakpoint and debug locally.

To begin with, we can only teach how to debug with local subql-node and database (not in the docker container).

Use chrome inspect as the debugger.
basically just run `node --inspect-brk /usr/local/bin/subql-node ...` and connect the debugger.

**Comment by seandotau** [comment]
https://github.com/subquery/subql/pull/480
