### ISSUE TITLE
Publish package-lock.json to npmjs.com

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#484]
Even though the project is organized in mono repo way via yarn workspace, we don't recommend user install the package to their global using `yarn global add`. It was detailed in #355.

The problem is we only have yarn.lock in the code base without package-lock.json. `npm -g install` doesn't recognize yarn.lock so when user tries to install our app, there are actually no lockfile used. It caused a lot dependency issues.

I can think of one solution, that we still use yarn and yarn.lock in the code base, but convert yarn.lock to package-lock.json via tools like `synp` when publishing packages to npmjs.com.

**Comment by jiqiang90** [comment]
https://github.com/imsnif/synp/issues/74

**Comment by stwiname** [comment]
NPM doesn't allow publishing `package-lock.json`. We don't have any complaints as this being an issue, im going to close
