### ISSUE TITLE
Limit query record number & depth

### ISSUE THREAD

**Issue by jiqiang90** [subquery/subql#513]
In our current implementation, user can query up to 100 records when have conditions like`first`, `last`,`last`... inside the filter.
https://github.com/subquery/subql/blob/c31d3e12c68517d9d40b7a05316740129dd88e2e/packages/query/src/graphql/plugins/PgConnectionArgFirstLastBeforeAfter.ts#L9

However, when without the condition filter, it seems the user allow to query an unlimited number of records, which potentially can break down our query service. We need to set this limit with/without any filter. 

For depth: 

https://www.graphile.org/postgraphile/production/#limiting-graphql-query-depth

**Comment by ianhe8x** [comment]
@zhex

**Comment by wqsz7xn** [comment]
assigning myself to this

**Comment by ianhe8x** [comment]
@wqsz7xn  We have a customer actually do fetch whole table data, to not break their usage, I'm think adding a flag `--unsafe`.

**Comment by wqsz7xn** [comment]
would it be a hack just to clamp if there are no limits? I'm still looking through the docs because i'm not very familiar w/ graphql 
```typescript
if(!after && !before && !first && !last && !offset) {
    queryBuilder.limit(MAX_RECORD_COUNT);
}
```
does work though

**Comment by jiqiang90** [comment]
Feature added, close this now

**Comment by jiqiang90** [comment]
Feature added, close this now
