### ISSUE TITLE
Update Docs and Examples for manifest spec v0.2.0

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#517]
Follow up task for #463
With the PR merged, we are now supporting a new manifest spec v0.2.0. 
During the transition period, both spec v0.0.1 and v0.2.0 are supported, and v0.0.1 will still be the default option for `subql init`, but still we will need to update our docs and examples to using latest manifest spec.

- [x] doc.subquery.network
- [ ] subql-examples repo(s)
- [ ] tutorials and other academy resources

**Comment by jiqiang90** [comment]
This is done
