### ISSUE TITLE
Bypassing the strict JSON schema

### ISSUE THREAD

**Issue by bgodlin** [subquery/subql#522]
While trying to solve the maximum amount of indexes limitation discussed within #514 realized that there is a way to bypass the strict JSON schema. Although it solves the issue #514 for us and allows to save the flexible hierarchies (like `batchAll` transactions) we still concerned about the usage of such approach. The example below works fine:

**`schema.graphql`**
```
type HistoryElement @entity {
  ...
  detail: HistoryElementDetail
  }

type HistoryElementDetail @jsonField {
  type: String
}

```

**Mapping file fragment**

```
const record = new HistoryElement(extrinsic.extrinsic.hash.toString())

let entity = new Object();
let soraEthTransferEvent = extrinsic.events.find(e => e.event.method === 'RequestRegistered');

const { event: { data: [requestHash] } } = soraEthTransferEvent;

entity = {
            requestHash: requestHash.toString(),
            assetId: assetId.toString(),
            to: to.toString(),
            amount: formatU128ToBalance(amount.toString())
        }

record.detail = entity
```

**Graphql request return**
![image](https://user-images.githubusercontent.com/37313677/136544332-f4e3b898-fb6f-4587-b671-b1b98c2fddf4.png)

As it could be seen, although there is only one object in `HistoryElementDetail`, it is possible to save any JSON structure.

**Comment by ianhe8x** [comment]
Thanks reporting it,this is expected though not recommended,as you know typescript is not a strong type language, you can easily by pass its type check via a lot of ways, and additionally the code will be compiled to js before loaded into subql-node, means you can write js directly.
We might add some checks in the future if it is proofed as a problem.
