### ISSUE TITLE
tuto helloworld : SyntaxError: Unexpected string on the init command...

### ISSUE THREAD

**Issue by tionebDotsamapha** [subquery/subql#527]
hi everyone,

i'm beggining the helloworld tuto.
prerequists are installed : 

`echo -e "My yarn version is:" `yarn --version` "\nMy subql version is:" `subql -v`  "\nMy docker version is:" `docker -v`
My yarn version is: 0.32+git 

My subql version is: @subql/cli/0.13.0 linux-x64 node-v10.19.0 

My docker version is: Docker version 20.10.8, build 3967b7d28e`

at the first command to init 
`subql init --starter subqlHelloWorld`

i've this error : 
`SyntaxError: Unexpected string`

Thank you for your help.

**Comment by ianhe8x** [comment]
Hi, sorry we can't replicate your issue. Will have more tries to see if it is related to os. In the mean time, can you provide more about this error? like error stacks.
