### ISSUE TITLE
per scaning block is reduced 

### ISSUE THREAD

**Issue by sxlwar** [subquery/subql#529]
In the beginning, 100 blocks per scanning, if the RCP connection has reconnected, the amount of block pre-scanning will be reduced

![image](https://user-images.githubusercontent.com/20088392/137271904-328342dd-cf0f-42b1-8a68-6ea61b60df9f.png)

**Comment by ianhe8x** [comment]
That's not because of the reconnection, but the buffer queue is full. Speed of fetching doesn't represent speed of processing blocks

**Comment by sxlwar** [comment]
> That's not because of the reconnection, but the buffer queue is full. Speed of fetching doesn't represent speed of processing blocks

thx, what conditions can cause this issue?   Exist only in one of our repos, https://github.com/darwinia-network/subql-pangoro, others are normal.

**Comment by ianhe8x** [comment]
@sxlwar Can you try adding `--profiler` to subql-node, which will print some profiling info to console and shall give you some idea where time is spent.

**Comment by sxlwar** [comment]
@ianhe8x https://github.com/darwinia-network/subql-pangoro/blob/d98204bcb2ec24a4aba3e0f4bd2c619c421dba24/docker-compose.yml#L29 is that right?
