### ISSUE TITLE
 The error block can not be found in the log

### ISSUE THREAD

**Issue by sxlwar** [subquery/subql#537]
![image](https://user-images.githubusercontent.com/20088392/137658607-aac66bf3-15c0-4bec-8e71-93fd7840affb.png)

can not find the error blocks when the sync failed after a long time

**Comment by ianhe8x** [comment]
With latest version of subql-node, we should be able to report the error block height. Can you share your repo here? @jiqiang90 will follow it up.

**Comment by jiqiang90** [comment]
@sxlwar can you share a link to your project on our explorer, I will try to reproduce it
