### ISSUE TITLE
Project manifest v0.3.0 - WIP

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#539]
Moving slowly towards v1.0.0

Things adding to 0.3.0

- [ ] include subql/node and subql/query version in the manifest
- [ ] <del>dynamic ds factory</del>

**Comment by jiqiang90** [comment]
For default substrate node, in the manifest we could define as  :

```
runner: 
  - kind: subql/node # for substrate 
    version: "0.28.0"
  - kind: subql/query 
    version : "0.12.0"

```

**Comment by stwiname** [comment]
> For default substrate node, in the manifest we could define as :
> 
> ```
> runner: 
>   - kind: subql/node # for substrate 
>     version: "0.28.0"
>   - kind: subql/query 
>     version : "0.12.0"
> ```

It would be good to support semver ranges like `^` and `*`. Like here https://devhints.io/semver

**Comment by stwiname** [comment]
I'm not sure how feasible it is, but I think it would be good to try and have a general schema validation and then a layer-1 blockchain specific validation.

Currently `datasources.kind` and `datasources.mapping.handlers[n].kind` are both validated as enums. It would be good to validate as strings. And have another layer of validation specific to the layer-1 blockchain.

We kind of do this with dynamic datasources already

**Comment by jiqiang90** [comment]
Close this now, as https://github.com/subquery/subql/issues/845 is completed
