### ISSUE TITLE
Relax sandbox limitation for 

### ISSUE THREAD

**Issue by yrong** [subquery/subql#579]
IMHO sandbox security limitation aims/applies mainly to the cloud depolyment scenario, or the saas service provided by subquery cloud.   But if  locally deployment the code should be safe so the limitation may not be nessessary.  

some hack for that and if you think nessesary I may add a pr maybe some config to relax the limitation
 
https://github.com/yrong/subql-hacked/commit/8af2ff20bfc6c58a7ec4d521939342996f30d2c2

**Comment by lachlan1m** [comment]
https://github.com/subquery/subql/pull/629
