### ISSUE TITLE
Support node 16 LTS

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#620]

**Comment by wqsz7xn** [comment]
w/ node v16.13.0 only fails on timeout of [`fetchBlocks`](https://github.com/subquery/subql/blob/0be714d177fef54855a5753836276c4041c00f8f/packages/node/src/utils/substrate.ts#L194-L224) within `packages/contract-processors/src/moonbeam.spec.ts`. i'm trying to profile [`fetchBlocks`](https://github.com/subquery/subql/blob/0be714d177fef54855a5753836276c4041c00f8f/packages/node/src/utils/substrate.ts#L194-L224) to see what's making it take >5000msec

**Comment by wqsz7xn** [comment]
thought i would try profiling it with `node --inspect-brk ./node_modules/jest/bin/jest.js --watch --runInBand` but having no luck because `fetchBlocks` doesn't seem to timeout when doing so.

**Comment by ianhe8x** [comment]
I think except make sure all tests pass, we can try out our example projects under node 16.

**Comment by wqsz7xn** [comment]
![image](https://user-images.githubusercontent.com/67990210/141401943-1472f91a-bd98-4ae2-9ff4-c86f1ce9f65b.png)
whenever I profile it it seems to behave well; not sure what's up; might just be something on my end
