### ISSUE TITLE
Make use of SpecVersion in the dictionary

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#624]
Currently when we fetch a batch of blocks, for example [10001, 10030]
We compare the specVersion of block 10030 with block 10000(cached in mem), when different we fetch metadata for 10030.
Since we already built a specVersion changelogs in the dictionary, we can use the infomation from there directly.

Note that we skip using dictionary in some scenarios even it is provided, we will need to change that for specVersion.

**Comment by jiqiang90** [comment]
Close with https://github.com/subquery/subql/pull/1046
