### ISSUE TITLE
Build and make use of fat dictionary

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#625]
Currently in the dictionary we only store minimum information that helps to locate the block height of matched filters, then in fetch.service.ts we will fetch block, events again from chain node.
Rpc of chain node is considered slow and in a lot of scenario the bottleneck of indexing speed.

If we can store whole blocks and events data in the dictionary, we can fetch directly without talking to chain node. In this case hopefully we could improve indexing speed a lot.

**Comment by zhex** [comment]
just a few questions to the fat dictionary:

- the fat dictionary can speed up the data query before calling the mapping function, does it also change the way people query data in the mapping function?
- do we allow to run the dictionary in parallel?  in this case all the data should be an independent record
