### ISSUE TITLE
An error occurred running the build command

### ISSUE THREAD

**Issue by dengpan1** [subquery/subql#649]
Run the build command from the project's root directory: "yarn build"
An error occurred running the build command,

`node_modules/@polkadot/types/create/registry.d.ts:7:22 - error TS2589: Type instantiation is excessively deep and possibly infinite.

7 export declare class TypeRegistry implements Registry {

node_modules/@polkadot/util-crypto/base32/bs32.d.ts:26:51 - error TS2307: Cannot find module '../../../util/src/types' or its 
corresponding type declarations.

26 export declare const base32Encode: (value: import("../../../util/src/types").U8aLike, ipfsCompat?: boolean | undefined) => string;
node_modules/@polkadot/util-crypto/base58/bs58.d.ts:21:51 - error TS2307: Cannot find module '../../../util/src/types' or its corresponding type declarations.

21 export declare const base58Encode: (value: import("../../../util/src/types").U8aLike, ipfsCompat?: boolean | undefined) => string;
node_modules/@polkadot/util-crypto/base64/bs64.d.ts:26:51 - error TS2307: Cannot find module '../../../util/src/types' or its corresponding type declarations.

26 export declare const base64Encode: (value: import("../../../util/src/types").U8aLike, ipfsCompat?: boolean | undefined) => string;`

Has it happened to anyone?

**Comment by jiqiang90** [comment]
> Run the build command from the project's root directory: "yarn build" An error occurred running the build command,
> 
> `node_modules/@polkadot/types/create/registry.d.ts:7:22 - error TS2589: Type instantiation is excessively deep and possibly infinite.
> 
> 7 export declare class TypeRegistry implements Registry {
> 
> node_modules/@polkadot/util-crypto/base32/bs32.d.ts:26:51 - error TS2307: Cannot find module '../../../util/src/types' or its corresponding type declarations.
> 
> 26 export declare const base32Encode: (value: import("../../../util/src/types").U8aLike, ipfsCompat?: boolean | undefined) => string; node_modules/@polkadot/util-crypto/base58/bs58.d.ts:21:51 - error TS2307: Cannot find module '../../../util/src/types' or its corresponding type declarations.
> 
> 21 export declare const base58Encode: (value: import("../../../util/src/types").U8aLike, ipfsCompat?: boolean | undefined) => string; node_modules/@polkadot/util-crypto/base64/bs64.d.ts:26:51 - error TS2307: Cannot find module '../../../util/src/types' or its corresponding type declarations.
> 
> 26 export declare const base64Encode: (value: import("../../../util/src/types").U8aLike, ipfsCompat?: boolean | undefined) => string;`
> 
> Has it happened to anyone?

Hi please check this ticket https://github.com/polkadot-js/common/issues/1225, we are waiting this to be resolved. For now, you can update this in package.json to resolve the issue. 

```
  "devDependencies": {
    "@polkadot/api": "^6.9.1",
    "@subql/types": "latest",
    "typescript": "^4.5.2",
    "@subql/cli": "latest"
  },
  "resolutions": {
    "@polkadot/util-crypto": "7.8.1"
  }
```

**Comment by dengpan1** [comment]
> > Run the build command from the project's root directory: "yarn build" An error occurred running the build command,
> > `node_modules/@polkadot/types/create/registry.d.ts:7:22 - error TS2589: Type instantiation is excessively deep and possibly infinite.
> > 7 export declare class TypeRegistry implements Registry {
> > node_modules/@polkadot/util-crypto/base32/bs32.d.ts:26:51 - error TS2307: Cannot find module '../../../util/src/types' or its corresponding type declarations.
> > 26 export declare const base32Encode: (value: import("../../../util/src/types").U8aLike, ipfsCompat?: boolean | undefined) => string; node_modules/@polkadot/util-crypto/base58/bs58.d.ts:21:51 - error TS2307: Cannot find module '../../../util/src/types' or its corresponding type declarations.
> > 21 export declare const base58Encode: (value: import("../../../util/src/types").U8aLike, ipfsCompat?: boolean | undefined) => string; node_modules/@polkadot/util-crypto/base64/bs64.d.ts:26:51 - error TS2307: Cannot find module '../../../util/src/types' or its corresponding type declarations.
> > 26 export declare const base64Encode: (value: import("../../../util/src/types").U8aLike, ipfsCompat?: boolean | undefined) => string;`
> > Has it happened to anyone?
> 
> Hi please check this ticket [polkadot-js/common#1225](https://github.com/polkadot-js/common/issues/1225), we are waiting this to be resolved. For now, you can update this in package.json to resolve the issue.
> 
> ```
>   "devDependencies": {
>     "@polkadot/api": "^6.9.1",
>     "@subql/types": "latest",
>     "typescript": "^4.5.2",
>     "@subql/cli": "latest"
>   },
>   "resolutions": {
>     "@polkadot/util-crypto": "7.8.1"
>   }
> ```
Thank you, it worked!

**Comment by bianyunjian** [comment]
for my project , it works with the config below:
```
 "devDependencies": {
    "@polkadot/api": "^6.9.1",
    "@subql/cli": "latest",
    "typescript": "^4.5.2",
    "@subql/types": "latest"
  },
  "dependencies": {},
  "resolutions": {
    "@polkadot/util-crypto": "7.8.1",
    "@polkadot/api-derive": "6.8.2-18"
  }
```
