### ISSUE TITLE
deprecate subqueries table in the public db schema

### ISSUE THREAD

**Issue by zhex** [subquery/subql#651]
To support multiple subquery projects, Subquery designed a `subqueries` table to log project information in the public DB schema. This table is also used for log processed block height. Due to this being a separate record to the project DB schema, we have to stop the indexer service when we do data migration, otherwise, the data consistency issue might happen.

- Now we have the `_metadata` table for each subquery project DB schema, we can use this table to track the block height instead of the `subqueries` table. 
- Also, we can allow users to pass the schema name instead of the project name when launching a service.

If these two dependencies are removed, we will not need a `subqueries` table.

**Comment by jiqiang90** [comment]
https://github.com/subquery/subql/blob/main/packages/node/src/indexer/indexer.manager.ts#L252

https://github.com/subquery/subql/blob/main/packages/node/src/indexer/indexer.manager.ts#L186

These two share a lot properties in common. In this improvement, we don't need create project schema anymore, we want indexer read these properties from `_metadata` table directly. 

The field `nextBlockHeight` can be removed, as it always will be `lastProcessedHeight` + 1

**Comment by wqsz7xn** [comment]
I can't find where the metadata table is even being created. I need to shift the name from the `subqueries` table over to the `_metadata` table so that i can rework `getProjectSchema(name:string)`

**Comment by ianhe8x** [comment]
The major change in this task is how and where we get the project schema.
And we need to consider how project migrate to this change. We might need to keep codes related to `subqueries` table and fall back to it when _metadata or the records don't exist.

**Comment by wqsz7xn** [comment]
I'm really stuck on this. The problem that I'm facing is that in order to use the metadata within the `storeService` the `initDbSchema` has to be initialised but it that can't be done till after the db schema has been created, while I need to use `storeService` well before the schema is created. I need some guidance on this because i'm not really progressing.
This is where i've gotten with it. At the moment. It doesn't work
https://github.com/wqsz7xn/subql/commit/a9ae79495e71555dbce265e1a3bb4a8eb2f303e9

**Comment by ianhe8x** [comment]
You are right, the db ddl migration happens in different stage, because project schema is only known from the subqueries table. You will need some really smart design for it.

**Comment by jiqiang90** [comment]
To clarify:
- if node use the flag `--schema = project_xxx`, we will use this schema from db 
   - need to check the string is validate or not
   - verify if the schema is exist or not, if not , create a new one with _metadata table 
   - if schema exist, we need to use `ensureProject` to validate the project is matching with schema metadata.
- For early version project has been deployed already, if node not use the flag, we will read from public.subqueries table, and fetch the db_schema

**Comment by jiqiang90** [comment]
**Upgrade from previous version**:  

For deployment currently using `subqueries` table,  or `lastProcessedHeight` does not exist in metadata table yet. When new version node are applied, check `lastProcessedHeight` is exist in metadata or not,
  - if yes,  `nextBlockHeight` = `lastProcessedHeight` + 1 and compare , it should be greater or equal to `nextBlockHeight` record in subqueries table. 
  - if not,  use `nextBlockHeight` value from subqueries first,  `lastProcessedHeight` should be updated after each time block processed, and `nextBlockHeight` in subqueries no longer need be updated. 

**After upgrade new version**: 

Fetch and update the `nextBlockHeight` will always use the `lastProcessedHeight` from the schema's metadata table
