### ISSUE TITLE
How to query genesis block information

### ISSUE THREAD

**Issue by qwer951123** [subquery/subql#655]
in karura, some balance Infos was written at the genesis block, when I counted the user's balances through transfer events, I found some user's information was negative, then I tried to solve it in subql but failed. How can I solve it instead of writing a block handler(I use the directory, so I don't want to fetch every block info)?

**Comment by ianhe8x** [comment]
We only start indexing from block#1, you can query states from there, should be any extrinsics in block1.
The big question I think is you don't know the storage keys that have balances larger than 0. I don't have answer for that.

**Comment by ianhe8x** [comment]
I think your question is not actually for subql but for karura team, how to know the accounts list who have initial balance.
One option is reverse engineering the genesis state in chainspec. The other is to ask acala team.

**Comment by qwer951123** [comment]
Okay, Thanks for your reply, I should write a script to download the initialize status as a JSON file for use.
