### ISSUE TITLE
Documentation for Enum and Force Clean Support

### ISSUE THREAD

**Issue by jamesbayly** [subquery/subql#664]
Update the [Schema File documentation](https://doc.subquery.network/create/graphql/) to include information about the enum support

https://github.com/subquery/subql/pull/551
https://github.com/subquery/subql/pull/619

**Comment by lachlan1m** [comment]
- I can see force clean option is [here](https://doc.subquery.network/references/references/#help)
- What extra information would you like written on top of [whats here](https://doc.subquery.network/create/graphql/#entities)

**Comment by jamesbayly** [comment]
Didn't see that sorry, my docs website is cached
