### ISSUE TITLE
When subql init promote question to get endpoint from user

### ISSUE THREAD

**Issue by jiqiang90** [subquery/subql#678]

**Comment by wqsz7xn** [comment]
isn't this already being done here?
https://github.com/subquery/subql/blob/c03fe7711505760210aa4720f83321e6c540ddc9/packages/cli/src/commands/init.ts#L52-L55
also this log shows in the init for me (probably not intended?)
https://github.com/subquery/subql/blob/c03fe7711505760210aa4720f83321e6c540ddc9/packages/cli/src/commands/init.ts#L63

**Comment by jiqiang90** [comment]
> isn't this already being done here?
> 
> https://github.com/subquery/subql/blob/c03fe7711505760210aa4720f83321e6c540ddc9/packages/cli/src/commands/init.ts#L52-L55
> 
> 
> also this log shows in the init for me (probably not intended?)
> https://github.com/subquery/subql/blob/c03fe7711505760210aa4720f83321e6c540ddc9/packages/cli/src/commands/init.ts#L63

Correct. We can close this .
