### ISSUE TITLE
Why indexer is unhealthy?

### ISSUE THREAD

**Issue by TopCodeBeast** [subquery/subql#691]
I deployed some projects and it worked well so I moved this from slot to production.
After 7 days, the project says 'indexer is unhealthy, Query is healthy'.
I deployed 3 projects and all of them had the same problems.
I copied KodaDot's subquery which is running well on this, so there is no error.
What is the reason?
Why it says 'indexer is unhealthy?'

**Comment by ianhe8x** [comment]
What's your project name? We can the further discussion in our discord, since here is not the best place for issues of Hosted service.

**Comment by jamesbayly** [comment]
Closed due to inactivity
