### ISSUE TITLE
Inject blockRegistry into sandbox

### ISSUE THREAD

**Issue by jiqiang90** [subquery/subql#692]
Background: compare to previous patched api, our current inject apiAt is unable to provide method like api.createType, which is can be access from the `blockReigstry`.

```
const u8aHash = u8aToU8a('0x.....');
const registry = await api.getBlockRegistry(u8aHash);
```

We want to inject the registry into our sandbox, so user can access it from their mapping function. 

However, before implement this,  we also need to validate the registry is match with its runtime. 
If there is a runtime upgrade and type has changed , inspect return type of `registry.registry.createType` should be different with latest `api.createType`.

Resource: https://polkascan.io/kusama/runtime-type

**Comment by wqsz7xn** [comment]
Currently used polkadot js includes registry in with `api.at`
![image](https://user-images.githubusercontent.com/67990210/149230489-92883559-176b-4023-8a32-6d394c87c881.png)
