### ISSUE TITLE
Expand health service

### ISSUE THREAD

**Issue by wqsz7xn** [subquery/subql#726]
Currently the health service endpoint is very primitive, only supporting a [catch all internal server error for its endpoint](https://github.com/subquery/subql/blob/3553be9593bf29bda68271896f77af31198f4e7b/packages/node/src/meta/health.controller.ts). This health service should be expanded and be made more accurate (ie: less than a 10 block time window as is currently implemented below and with proper http status codes) https://github.com/subquery/subql/blob/cb7ebc814db13469472c54a658282ae5119d3029/packages/node/src/meta/health.service.ts#L71-L85

I personally want to be able to check the health service to see if the node is in a startup state or indexing state so that I can add a healthcheck within a docker image so that the query service can start after the indexer is properly started up and **available** (has created its schemas and is indexing _versus_ has just started up and schemas not created (if it's a new project)). 

Currently the following[ docker image ](https://gist.github.com/wqsz7xn/83348e1f84a9e5789b6b725859c82621)against a starter project will start the query service **immediately** after the node has started. As described above this is not good because the query service shows some errors and will crash and restart. Then after a while query service will successfully start (after the node service has properly gone through its start sequence). In order to achieve this we must be returning json objects and then docker side decode with something like `jq`

**Comment by ianhe8x** [comment]
Looks like the health check in docker-compose works like readiness probe in Kubernetes, while the health check we implemented is liveness probe in Kubernetes.
We can do that in the new `/ready` rpc.

**Comment by ianhe8x** [comment]
Closed by #728
