### ISSUE TITLE
Spec validation error is eaten and only visible with --debug

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#727]
When there's type mismatch in network.chaintypes, no error printed to console and the whole app just crashed, unless with --debug enabled.

The problem here is the validation of chaintypes is done in the SubqueryProject's `get chainTypes()`, the better place is `ProjectManifestVersioned -> validate()`

**Comment by wqsz7xn** [comment]
I don't think that we should move this to validate as it seems geared towards the project yaml we could expand it though? Could just add the raw parse to the try block

```typescript
      let rawChainTypes: unknown;
      let parsedChainTypes: ChainTypes;
      try {
        rawChainTypes = loadChainTypes(
          path.join(this._path, impl.network.chaintypes.file),
          this.path,
        );
        parsedChainTypes = parseChainTypes(rawChainTypes);
      } catch (e) {
        logger.error(`failed to load chaintypes file, ${e}`);
      }
      return parsedChainTypes;
    }
```

Which nicely displays the error:
```
2021-12-31T02:06:51.725Z <configure> ERROR failed to load chaintypes file, Error: failed to parse chain types.
```

**Comment by wqsz7xn** [comment]
Fixed in above pull, although we may want to move the validation logic as described in the issue in the future
