### ISSUE TITLE
add row estimate in _metadata

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#734]
In UI we show a total entities number which is fetched from graphql endpoint by adding totalCount of each entity.
For a large table doing this might slow down db significantly. 
One workaround is use count estimate provided by postgres in this case.

to be more specific:
```
type _Metadata {
        lastProcessedHeight: Int
        lastProcessedTimestamp: Date
        targetHeight: Int
        chain: String
        specName: String
        genesisHash: String
        indexerHealthy: Boolean
        indexerNodeVersion: String
        queryNodeVersion: String
        rowCountEstimate: JSONObject # {"table1": xxx, "table2": yyy}
      }


```

links: https://wiki.postgresql.org/wiki/Count_estimate

**Comment by wqsz7xn** [comment]
Added in #736
