### ISSUE TITLE
Change default port of Node or Query service

### ISSUE THREAD

**Issue by stwiname** [subquery/subql#737]
Both services default to port 3000, if users run both of these without docker then they conflict. We should change the default port of one of these (most likely the node) to another port.

This will cause issues with existing projects docker compose and require updating the project templates.

**Comment by wqsz7xn** [comment]
Agree with changing node service port rather than query as query playground that people use will autofill in the browsers. I'll bind the following ports: `node: 3001` `query: 3000`

**Comment by ianhe8x** [comment]
closed by #739
