### ISSUE TITLE
[node] expose syncing status via api

### ISSUE THREAD

**Issue by zhex** [subquery/subql#75]
a sample payload for the api  return
```
{
"syncing": true,
"finalizedBlock": 10000,
"syncedBlock": 500
}
```

**Comment by ianhe8x** [comment]
Another way is we can store these infos in a metadata table, and use graphql api to query them.

**Comment by zhex** [comment]
if we want to reuse exist query service implementation, we need to find a way to disable the list query for the metadata table. write a new API may be much simpler.
`syncing` is a computed value, inject a resolver is the same effort as create a new rest API.

**Comment by ianhe8x** [comment]
I think it is useful information for frontend app.  If the background indexing task is stucked, frontend will be aware of the issue and can have proper error handling.

**Comment by ianhe8x** [comment]
Also useful for query compositions, I assume we will put a precondition that only two fully synced query can be composited.

**Comment by zhex** [comment]
this is already implemented in the meta api
