### ISSUE TITLE
Unable to initialize the API error

### ISSUE THREAD

**Issue by sxlwar** [subquery/subql#754]
![image](https://user-images.githubusercontent.com/20088392/149705020-051afcbf-0932-4bec-82c2-636d9185603f.png)

have a plan to bump the @polkadot/api to 7.4.1? 

https://github.com/polkadot-js/api/pull/4441

**Comment by ianhe8x** [comment]
Will do that shortly.

**Comment by lachlan1m** [comment]
closed with #757

**Comment by lachlan1m** [comment]
closed with #757
