### ISSUE TITLE
[node] add elasticsearch service support for expose service logs

### ISSUE THREAD

**Issue by zhex** [subquery/subql#76]
elasticsearch is the most popular service for store log data.  we'd better add ES support directly in the indexer node service. 

e.g.:

```
yarn start -f ./projectdir --es-url=es.service:9200
```

**Comment by ianhe8x** [comment]
we can use https://github.com/pinojs/pino/blob/master/docs/transports.md#pino-elasticsearch
then it will be transparent to user who don't need the feature.

**Comment by zhex** [comment]
log solution implemented
