### ISSUE TITLE
Unable to run start:dev from subql/node with certain projects

### ISSUE THREAD

**Issue by lachlan1m** [subquery/subql#761]
For example when I try to run

`yarn start:dev -f ~/path/to/moonriver-starter`

`<ds-sandbox> ERROR not supported ds @substrate/Moonbeam`
`<subql-node> ERROR Node failed to start VMError: Module '@subql/types' is not allowed to be required. The path is outside the border!`

**Comment by ianhe8x** [comment]
Use `yarn start:prod`, it is due to `tsconfig-paths/register`, not sure if it is possible to fix.

**Comment by ianhe8x** [comment]
And we probably should publish contract-processors as a single bundled js, which maybe fix this error.

**Comment by stwiname** [comment]
I think this has been fixed now that we have `subql build` command
