### ISSUE TITLE
Doesn't work <action>.multi for api.query.staking.payee

### ISSUE THREAD

**Issue by stepanLav** [subquery/subql#764]
On versions:
"@polkadot/api": "^6",
"@subql/types": "^0.13.0",
"typescript": "^4.1.3",
"@subql/cli": "^0.18.0"

Doesn't work <action>.multi 

Was caught on the westend network on our project:
https://github.com/nova-wallet/subquery-nova/tree/bfcbc78007bdb026b14a10906860c039bec7dcf9
log:

```
2022-01-19T10:38:07.503Z <subql-node> INFO node started on port: 3000 
2022-01-19T10:38:09.647Z <fetch> INFO fetch block [2629080,2629179], total 100 blocks 
2022-01-19T10:38:19.819Z <fetch> ERROR failed to index block at height 2629080 handleReward() TypeError: api.query.staking.payee.multi is not a function
```

It was fixed by changing <action>.multi to multiQuery, but it looks strange that we can't use <action>.multi here.

**Comment by ianhe8x** [comment]
Polkadotjs's ApiAt object (the one you get from api.at(block)) doesn't support `.multi()`, so here we are.

**Comment by jiqiang90** [comment]
![Screen Shot 2022-01-20 at 2 06 48 PM](https://user-images.githubusercontent.com/10431657/150243934-a755d870-38f7-4c72-83b3-f8d6948306e9.png)
@stepanLav we provided in the subquery project is the `api.at()` object,  as you can seen from the top of image, the `api.at()` object is no longer support .multi().

**Comment by ianhe8x** [comment]
https://github.com/polkadot-js/api/issues/4473

**Comment by stepanLav** [comment]
Ok, I got it.
Thank you for response!
