### ISSUE TITLE
Use groupby in the dictionary query

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#769]
Since `@subql/query@0.11.0`, groupby aggregation is enable by default, which can be used to simulate `distinct`.

Our dictionary query can be benefit from using it. But since it depends on query service's version, we need to check the capacity first before using this feature.

**Comment by jiqiang90** [comment]
We will support `distinct` on all user entities (exclude _metadata and _poi), then we can update our dictionary query in node

**Comment by jiqiang90** [comment]
We have supported `distinct` in query, this can close now
