### ISSUE TITLE
Update availability log

### ISSUE THREAD

**Issue by fishmonger45** [subquery/subql#779]
- We sometimes get questions for subql that are solved in later versions of services, we can reduce the number of questions with a suggest to update which may solve their problem before they have to ask it
- Do a fetch from npmjs/yarnpkg to see if there are later available versions and make a log suggesting and update to if needed

Commands
- `npm list` for locally installed package, include a `-g` flag if it's installed globally. Need to do a basic regex on this to process tree, example
```
wqsz7xn@crate:~/Desktop$ npm list -g
/home/wqsz7xn/.nvm/versions/node/v16.13.1/lib
├── @subql/cli@0.19.0
├── @subql/node@0.27.2
├── @subql/query@0.10.0
├── corepack@0.10.0
├── jest@27.4.7
├── npm@8.1.2
├── typescript@4.5.4
├── vuepress@1.9.5
└── yarn@1.22.17
```
- `npm show <package> version` for latest stable version, example 
```
wqsz7xn@crate:~$ npm show @subql/node version
0.27.2
```
- Do something similar for `yarn`

**Comment by ianhe8x** [comment]
That's good idea. The latest version can be read via npmjs's api, and the local version can be accessed from our own code. I don't think call npm is good idea, there could be multiple local copy, we only need the version of the one currently used.

**Comment by wqsz7xn** [comment]
True that would be a lot better

**Comment by wqsz7xn** [comment]
Should have checked first before writing details above, could just use [update notifier](https://www.npmjs.com/package/update-notifier) which is plug and play. Don't use the `notify` function though because it creates a banner while we should just be using a single line.
