### ISSUE TITLE
hot reload schema in the query service on schema change

### ISSUE THREAD

**Issue by zhex** [subquery/subql#799]
when an indexer updated/add a table, we have to restart the query service to get the latest schema generated from the db tables. this is not convenient and can be auto-updated.

graphile provides a `watchSchema` method may help. https://github.com/graphile/graphile-engine/blob/1619878d96/packages/graphile-build/src/SchemaBuilder.js#L526

**Comment by jamesbayly** [comment]
This is creating performance impacts on query service 1.6.0 - working on a work around
