### ISSUE TITLE
Please clarify One-to-Many relationships

### ISSUE THREAD

**Issue by lamafab** [subquery/subql#860]
Hello

In the documentation, I have trouble understanding this section:

![image](https://user-images.githubusercontent.com/42901763/159562679-f26b261e-89ad-4d80-bdf8-7f89a6f882ff.png)

What is a "field point" and how does it relate to `publicAddress`? I'd just need to reference multiple `Account`'s by `ID` from `Person`. Is `@derivedFrom` a requirement in this case?

Specifically, the `sql-node` does not like this schema ("`Having a problem when syncing schema SequelizeDatabaseError: foreign key constraint "extrinsics_fields_id_fkey" cannot be implemented`"):

```
type Extrinsic @entity {
  id: ID!
  block_hash: String!
  block_nr: Int!
  timestamp: String!
  index: Int!
  name: String!
  fields: [SilField]!
  call_index: Int!
  docs: [String]!
  args: [FunctionArgument]!
}

type SilField @entity {
  id: ID!
  name: String
  type: Int!
  typeName: String
  docs: [String]!
}

type FunctionArgument @entity {
  id: ID!
  name: String!
  type: String!
  typeName: String
}

```

**Comment by lachlan1m** [comment]
Yes thanks for bring this up, documentation is being updated. As for the example 

```graphql
type Person @entity {
  id: ID!
  accounts: [Account]! @derivedFrom(field: "person") #accounts is a virtual field
}

type Account @entity {
  id: ID!
  person: Person! 
}
```

This is how you would write a one-to-many relationship. The derivedFrom allows reverse lookup enabling the one-to-many relationship to be queried in graphql.

**Comment by lamafab** [comment]
HI @lachlan1m 

Yes this works, thanks. By running `yarn codegen`, the `Account` type will then have a `personId` field and in `Person` there's no direct reference in `Account`. Also note that I had to wipe my local db first before I got this working.

I'm just writing this stuff for anyone else who has this issue.
