### ISSUE TITLE
Support ssl on postgre connect

### ISSUE THREAD

**Issue by zjb0807** [subquery/subql#868]
https://github.com/brianc/node-postgres/blob/master/packages/pg-pool/README.md#create

**Comment by darwinsubramaniam** [comment]
Hi, how is the progress on this issue?

**Comment by darwinsubramaniam** [comment]
Hi @bighammerw ,
I am made some changes on the fork , but still have not tested it.
https://github.com/darwinsubramaniam/subql -> method used is using environment variable

**Comment by bighammerw** [comment]
hi darwin thanks i will have a look for this issue

**Comment by jamesbayly** [comment]
@darwinsubramaniam can you make a PR so we can review?

**Comment by darwinsubramaniam** [comment]
> @darwinsubramaniam can you make a PR so we can review?

HI @jamesbayly , surely

**Comment by darwinsubramaniam** [comment]
Hi @jamesbayly and @bighammerw , 

Could you please kindly , guide me how to test the features. I could not figure out how can test it. It would be nice if you guide me on that, future bugfix or any help required in I will be able to contribute as well.

**Comment by darwinsubramaniam** [comment]
Hi @jamesbayly  and @bighammerw ,

Figure out how to run the subql-node locally using the source code, I found out that to enable SSL is not as simple as just making the ssl to be true, 

It is also should carry the ca cert at minimum to enable correct authentication to the SSL enabled postgres.  - reference https://stackoverflow.com/questions/43948920/how-to-connect-via-ssl-to-sequelize-db

making modification to the code to so USER can pass is the full path for the cert for now , later maybe can improve more on that. 
Marked the PR as Work In Progress.
