### ISSUE TITLE
Topic filters in EVM do not work properly.

### ISSUE THREAD

**Issue by Lpaydat** [subquery/subql#908]
According to https://university.subquery.network/build/substrate-evm.html.
I follow the instructions in the documentation and the example (https://github.com/subquery/tutorials-frontier-evm-starter/tree/moonriver).

It appears that event filters are not working properly.

This one worked perfectly.
```yaml
- Transfer(address indexed from,address indexed to,uint256 value)
## topics[1] to topics[3] are the indexed values
- null
- null
- null
```

However, this one does not since it cannot be matched to anything.
```yaml
- Transfer(address indexed from,address indexed to,uint256 value)
## topics[1] to topics[3] are the indexed values
- null
- "0xF0d40B2813BeE4C0e359AfD161d9Bb92a6204844"  # I got this address from the above filter results
- null
```

While it is mentioned in the sample project.yaml file that we may use the OR filter (https://github.com/subquery/tutorials-frontier-evm-starter/blob/moonriver/project.yaml#L49), but when I attempted to use the OR filter, it threw an error (Invalid Frontier event filter.)

```yaml
## Example of OR filter, will capture Transfer or Approval events
- - 'Transfer(address indexed from,address indexed to,uint256 value)'
  - 'Approval(address indexed owner, address indexed spender, uint256 value)'
```

**Comment by jamesbayly** [comment]
@stwiname  we should update the docs if we do anything to resolve this here

**Comment by stwiname** [comment]
Thanks @Lpaydat. Can you please share what network and contract address is being used so I can reproduce?

I think we may have dropped support for the OR filter because of some other issue. The second example should be a valid use case though, will look at fixing that.

**Comment by Lpaydat** [comment]
@stwiname Sorry for the delayed response.

Here is the network and contract address that I used.

Network: https://api.subquery.network/sq/subquery/moonriver-dictionary
Contract Address: 0x6bd193ee6d2104f14f94e2ca6efefae561a4334b

**Comment by stwiname** [comment]
There doesn't seem to be a transaction for the contract `0x6bd193ee6d2104f14f94e2ca6efefae561a4334b` that matches 
```yaml
- Transfer(address indexed from,address indexed to,uint256 value)
## topics[1] to topics[3] are the indexed values
- null
- "0xF0d40B2813BeE4C0e359AfD161d9Bb92a6204844"  # I got this address from the above filter results
- null
 ```

https://moonriver.subscan.io/account/0x6bd193ee6d2104f14f94e2ca6efefae561a4334b?tab=erc20_transfer

So I believe this is behaving correctly.

As for the OR filter, this is not supported an I have updated the tutorial project

**Comment by Lpaydat** [comment]
@stwiname 
You are correct; it is working properly. (I made a stupid mistake and used the address from the transaction rather than the ERC20 transfer in the topic)
