### ISSUE TITLE
Events are processed three times in latest indexer

### ISSUE THREAD

**Issue by shengda** [subquery/subql#996]
### Context
We do a daily and hourly stats on our events with Subquery.
### Error
The stats data we get is all three times of the correct values. We check the logs and find that, with the latest v35 indexer, all events are processed three times. When we switch back to v33, the issue is gone.

We can replicate this issue in both local environment and Subquery servers.

**Comment by stwiname** [comment]
Hey @shengda, can you please try `0.35.2-0` it should have been fixed with https://github.com/subquery/subql/pull/994

**Comment by jiqiang90** [comment]
This can be closed now
